SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acs].[DeliverabilityCodeGetByCode]
	@Code char(1)
AS
BEGIN
	SET NOCOUNT ON;
	    
	SELECT 
		DELIVERABILITYCODE_ID
		, DELIVERABILITYCODE_CODE
		, DELIVERABILITYCODE_DESCRIPTION
		, DELIVERABILITYCODE_TYPEID
	FROM
		[acs].[DeliverabilityCodes]
	WHERE
		DELIVERABILITYCODE_CODE = @Code
	ORDER BY
		DELIVERABILITYCODE_ID;
END
GO