SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acs].[NixieRecordsGetBySegmentID]
	@ID	int
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT
		acs.[RECORD_ID]
		,acs.[RECORD_ACSTYPEID]
		,acs.[RECORD_CAPTURETYPEID]
		,acs.[RECORD_DELIVERABILITYCODEID]
		,acs.[RECORD_FEENOTIFICATIONTYPEID]
		,acs.[RECORD_FULFILLMENTDATE]
		,acs.[RECORD_HARDCOPYFLAG]
		,acs.[RECORD_IDTAG]
		,acs.[RECORD_IMPB]
		,acs.[RECORD_MAILACTIONCODEID]
		,acs.[RECORD_MAILERID]
		,acs.[RECORD_MAILPIECEID]
		,acs.[RECORD_MAILSHAPEID]
		,acs.[RECORD_NOTIFICATIONTYPEID]
		,acs.[RECORD_POSTAGEDUE]
		,acs.[RECORD_POSTALSERVICESITEID]
		,acs.[RECORD_PROCESSINGTYPEID]	
	FROM
		[acs].[NixieRecords] AS acs
		INNER JOIN [dbo].[MailPieces] AS p
			ON acs.RECORD_MAILPIECEID = p.MAILPIECE_ID
	WHERE
		p.MAILPIECE_SEGMENTID = @ID
	ORDER BY 
		acs.RECORD_ID;
END
GO