SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acs].[NixieRecordsGetCountByMailPieceID]
	@ID	int
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT
		COUNT([RECORD_ID])
	FROM
		[acs].[NixieRecords]		
	WHERE
		RECORD_MAILPIECEID = @ID;
END
GO