SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acs].[CoaRecordGetByID]
	@ID	int
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT
	[RECORD_ID]
	, [RECORD_ACSTYPEID]
    , [RECORD_CAPTURETYPEID]
	, [RECORD_COMPANYNAME] 
	, [RECORD_DELIVERABILITYCODEID]
	, [RECORD_EFFECTIVEDATE]
	, [RECORD_FEENOTIFICATIONTYPEID]
	, [RECORD_FIRSTNAME]
    , [RECORD_FULFILLMENTDATE]
    , [RECORD_HARDCOPYFLAG]
    , [RECORD_IDTAG]
    , [RECORD_IMPB]
	, [RECORD_LASTNAME]
    , [RECORD_MADEAVAILABLE]
    , [RECORD_MAILACTIONCODEID]
    , [RECORD_MAILERID]
	, [RECORD_MAILPIECEID]
    , [RECORD_MAILSHAPEID]
	, [RECORD_MOVETYPEID]
	, [RECORD_NAMEPREFIX]
	, [RECORD_NAMESUFFIX]
	, [RECORD_NEWADDRESSTYPEID]
	, [RECORD_NEWCHECKDIGIT]
	, [RECORD_NEWCITY]
	, [RECORD_NEWDELIVERYPOINT]
	, [RECORD_NEWPOSTDIRECTIONAL]
	, [RECORD_NEWPREDIRECTIONAL]
	, [RECORD_NEWPRIMARYNUMBER]
	, [RECORD_NEWSECONDARYNUMBER]
	, [RECORD_NEWSTATE]
	, [RECORD_NEWSTREETNAME]
	, [RECORD_NEWSTREETSUFFIX]
	, [RECORD_NEWUNITDESIGNATOR]
	, [RECORD_NEWURBANIZATION]
	, [RECORD_NEWZIPCODE]
	, [RECORD_NEWZIPCODEADDON]
	, [RECORD_NOTIFICATIONTYPEID]
	, [RECORD_OLDADDRESSTYPEID]
	, [RECORD_OLDCITY]
	, [RECORD_OLDPOSTDIRECTIONAL]
	, [RECORD_OLDPREDIRECTIONAL]
	, [RECORD_OLDPRIMARYNUMBER]
	, [RECORD_OLDSECONDARYNUMBER]
	, [RECORD_OLDSTATE]
	, [RECORD_OLDSTREETNAME]
	, [RECORD_OLDSTREETSUFFIX]
	, [RECORD_OLDUNITDESIGNATOR]
	, [RECORD_OLDURBANIZATION]
	, [RECORD_OLDZIPCODE]
	, [RECORD_POSTAGEDUE]
	, [RECORD_POSTALSERVICESITEID]
	, [RECORD_PRIVATEMAILBOX]
    , [RECORD_PROCESSINGTYPEID]
	FROM
		[acs].[CoaRecords]
	WHERE
		RECORD_ID = @ID;
END
GO