SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acs].[DeliverabilityCodesGet]
	
AS
BEGIN
	SET NOCOUNT ON;
	    
	SELECT 
		DELIVERABILITYCODE_ID
		, DELIVERABILITYCODE_CODE
		, DELIVERABILITYCODE_DESCRIPTION
		, DELIVERABILITYCODE_TYPEID
	FROM
		[acs].[DeliverabilityCodes]
	ORDER BY
		DELIVERABILITYCODE_ID;
END
GO