SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acxiom].[ZipCodeGetByID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		ZIPCODE_ID
		, ZIPCODE_AVERAGEAGE
		, ZIPCODE_CITY
		, ZIPCODE_INCOME
		, ZIPCODE_LATITUDE
		, ZIPCODE_LONGITUDE
		, ZIPCODE_MKTMED
		, ZIPCODE_PERCENTCHILD
		, ZIPCODE_STATE
		, CONVERT(varbinary(MAX), ZIPCODE_WKB) AS [ZIPCODE_WKB]
		, ZIPCODE_WKT		
	FROM
		[acxiom].[ZipCodes]
	WHERE
		ZIPCODE_ID = @ID
END
GO