SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acxiom].[OrderZipCodeGetByID]
	@ID			int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		ZIPCODE_ID		
		, ZIPCODE_CREATED
		, ZIPCODE_CREATEDBYID
		, ZIPCODE_NAME		
		, ZIPCODE_ZIPCODE
		, ZIPCODE_ROWVERSION
	FROM
		[acxiom].[OrderZipCodes]	
	WHERE
		ZIPCODE_ID = @ID
	ORDER BY
		ZIPCODE_ID;
END
GO