SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [acxiom].[CarrierRoutesGetByZipCodeID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		CRRT_ID
		, CRRT_AVERAGEAGE
		, CRRT_BOXES
		, CRRT_BUSINESS
		, CRRT_CRRT
		, CRRT_INCOME
		, CRRT_LATITUDE
		, CRRT_LONGITUDE
		, CRRT_MFDU
		, CRRT_MKTMED
		, CRRT_PERCENTCHILD
		, CRRT_SFDU
		, CRRT_TRLR
		, CONVERT(varbinary(MAX), CRRT_WKB) AS [CRRT_WKB]
		, CRRT_WKT
		, CRRT_ZIPCODEID		
	FROM
		[acxiom].[CarrierRoutes]
	WHERE
		CRRT_ZIPCODEID = @ID
END
GO