SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[GeoTimeZonesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   pmurphy using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[GeoTimeZonesGetAll]
-- Date Generated: Thursday, March 10, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GeoTimeZonesGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[TimeZoneWkt],
	[TimeZoneWkb],
	[ZoneId]
FROM
	[dbo].[geo_TimeZones]

--endregion

GO