SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingTiersetCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTiersetCreate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingTiersetCreate]
	@Tiersetid int,
	@Currencyid int,
	@Setup decimal(18, 4),
	@Base decimal(18, 4),
	@Percent decimal(18, 4),
	@Paycycle varchar(500),
	@Pricemodel varchar(500),
	@Writedatetime datetime,
	@Moddatetime datetime,
	@Currencysymbol varchar(50),
	@Currencyiso4217 varchar(50),
	@Itemid int,
	@Setupformatted varchar(50),
	@Baseformatted varchar(50),
	@Percentformatted varchar(50),
	@Pricemodeldesc varchar(500)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingTiersets] (
	[TiersetId],
	[CurrencyId],
	[Setup],
	[Base],
	[Percent],
	[Paycycle],
	[PriceModel],
	[WriteDatetime],
	[ModDatetime],
	[CurrencySymbol],
	[CurrencyIso4217],
	[ItemId],
	[SetupFormatted],
	[BaseFormatted],
	[PercentFormatted],
	[PriceModelDesc]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Tiersetid,
	@Currencyid,
	@Setup,
	@Base,
	@Percent,
	@Paycycle,
	@Pricemodel,
	@Writedatetime,
	@Moddatetime,
	@Currencysymbol,
	@Currencyiso4217,
	@Itemid,
	@Setupformatted,
	@Baseformatted,
	@Percentformatted,
	@Pricemodeldesc
)

--endregion

GO