SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NdcServiceAreaGetByID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		NDCSERVICEAREA_ID
		, NDCSERVICEAREA_END
		, NDCSERVICEAREA_NDCID
		, NDCSERVICEAREA_START
    FROM
		[dbo].[NDCServiceAreas]
	WHERE
		NDCSERVICEAREA_ID = @ID;
END
GO