SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[JobStageRoleDeleteByID] 
	@ID int
AS
	
	DELETE tblJobStageRoles WHERE JOBSTAGEROLE_ID = @ID;
	
	IF @@ROWCOUNT > 0
		RETURN 0;
	ELSE
		RETURN 1;
GO