SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[ClientRelationshipUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ClientRelationshipUpdate]
-- Date Generated: Friday, March 3, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ClientRelationshipUpdate]
@Version				timestamp,
	@Id int,
	@Created datetime,
	@Createdbyid int,
  @DisabledDate DATETIME,
	@Expiration datetime,
	@Parentclientid int,
	@Partnerclientid int,
  @RelationshipState INT,
	@Relationshiptype int
    
AS

SET NOCOUNT ON

UPDATE [dbo].[ClientRelationships] SET
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
  DisabledDate = @DisabledDate,
	[Expiration] = @Expiration,
	[ParentClientId] = @Parentclientid,
	[PartnerClientId] = @Partnerclientid,
  RelationshipState = @RelationshipState,
	[RelationshipType] = @Relationshiptype
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO