SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[WizardTemporaryJsonUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[WizardTemporaryJsonUpdate]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[WizardTemporaryJsonUpdate]
	@Id int,
	@Clientid int,
	@Json varchar(max),
	@Userid int
    
AS

SET NOCOUNT ON

UPDATE [dbo].[Wizard_TemporaryJson] SET
	[ClientId] = @Clientid,
	[Json] = @Json,
	[UserId] = @Userid
    OUTPUT inserted.Id AS [ID]
WHERE
	[Id] = @Id

--endregion

GO