SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[AssignmentGetByJobIDByUserID]
	@JobID int,
	@UserID int
AS
BEGIN
	
	SET NOCOUNT ON;
	
	SELECT
		ASSIGNMENT_ID,
		ASSIGNMENT_JOBID,
		ASSIGNMENT_USERID,
		ASSIGNMENT_ROWVERSION
	FROM 
		Assignments 
	WHERE 
		(ASSIGNMENT_JOBID = @JobID) AND 
		(ASSIGNMENT_USERID = @UserID);
END
GO