SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_PrintKeysGetCountsCountByMailDateRange] (  
  @Effort		char(1)		= NULL
  , @DateFrom	datetime	= NULL
  , @DateTo		datetime	= NULL 
  , @GroupByDate	bit = NULL 
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT COUNT(*) FROM
	(
	SELECT 
		COUNT(t.PRINTKEY) AS x
	FROM 
	(
		SELECT 
			'1' AS RECORDTYPE
			, m.MAILRECORD_PRINTKEY AS PRINTKEY
			, m.MAILRECORD_EFFORT AS EFFORT
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_BATCHDATE END AS BATCHDATE
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_MAILDATE END AS MAILDATE
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_TRANSACTIONDATE END AS TRANSACTIONDATE
        FROM 
			[dbo].[colpenn_MailRecords] AS m
        WHERE 
			(@DateFrom IS NULL OR m.MAILRECORD_MAILDATE >= @DateFrom) 
			AND (@DateTo IS NULL OR m.MAILRECORD_MAILDATE <= @DateTo)
			AND (@Effort IS NULL OR @Effort = '' OR m.MAILRECORD_EFFORT = @Effort)
         
         UNION ALL
         
		SELECT 
			'2' AS RECORDTYPE
			, r.REJECTRECORD_PRINTKEY AS PRINTKEY
			, r.REJECTRECORD_EFFORT AS EFFORT
			, r.REJECTRECORD_BATCHDATE AS BATCHDATE 
			, r.REJECTRECORD_MAILDATE AS MAILDATE
			, r.REJECTRECORD_TRANSACTIONDATE AS TRANSACTIONDATE
        FROM 
			[dbo].[colpenn_RejectRecords] AS r
         WHERE 
			(@DateFrom IS NULL OR r.REJECTRECORD_MAILDATE >= @DateFrom) 
			AND (@DateTo IS NULL OR r.REJECTRECORD_MAILDATE <= @DateTo)
			AND (@Effort IS NULL OR @Effort = '' OR r.REJECTRECORD_EFFORT = @Effort)
        ) t
	GROUP BY
			PRINTKEY,
			EFFORT,
			CASE @GroupByDate WHEN 1 THEN t.TRANSACTIONDATE END,
			CASE @GroupByDate WHEN 1 THEN t.MAILDATE END,
			CASE @GroupByDate WHEN 1 THEN t.BATCHDATE END
	) x
;
	
END
GO