SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_MailRecordsGetDateCountByBatchDateRange] (
  @From	datetime	= NULL
  , @To		datetime	= NULL  
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		MAILRECORD_BATCHDATE AS [DATE]
		, COUNT(*) AS [COUNT]
	FROM 
		[dbo].[colpenn_MailRecords] 
	WHERE
		(@From IS NULL OR MAILRECORD_BATCHDATE >= @From)
		AND (@To IS NULL OR MAILRECORD_BATCHDATE <= @To)
	GROUP BY
		MAILRECORD_BATCHDATE
END
GO