SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[ActiveUsersGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ActiveUsersGetAll]
-- Date Generated: Monday, June 5, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ActiveUsersGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Expiration],
	[UserId],
	[Created],
	[CreatedById],
  [RowVersion] 
FROM
	[dbo].[ActiveUsers]

--endregion

GO