SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailUnsubscribeLogInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailUnsubscribeLogInsert]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailUnsubscribeLogInsert]
	@Event varchar(50),
	@Recipient varchar(500),
	@Domain varchar(500),
	@Ip varchar(50),
	@Country varchar(500),
	@Region varchar(500),
	@City varchar(500),
	@Useragent varchar(500),
	@Devicetype varchar(50),
	@Clienttype varchar(50),
	@Clientname varchar(50),
	@Clientos varchar(50),
	@Campaignid varchar(50),
	@Campaignname varchar(500),
	@Tag varchar(100),
	@Mailinglist varchar(500),
	@SendId int,
	
	@Timestamp varchar(50),
	@Token varchar(100),
	@Signature varchar(500),
	@Bodyplaintext varchar(4000)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[mailgun_UnsubscribeLog] (
	[Event],
	[Recipient],
	[Domain],
	[Ip],
	[Country],
	[Region],
	[City],
	[UserAgent],
	[DeviceType],
	[ClientType],
	[ClientName],
	[ClientOs],
	[CampaignId],
	[CampaignName],
	[Tag],
	[MailingList],
	[SendId],
	
	[Timestamp],
	[Token],
	[Signature],
	[BodyPlainText]
) 
OUTPUT		
		inserted.Id AS [ID], NULL AS [VERSION]
VALUES (
	@Event,
	@Recipient,
	@Domain,
	@Ip,
	@Country,
	@Region,
	@City,
	@Useragent,
	@Devicetype,
	@Clienttype,
	@Clientname,
	@Clientos,
	@Campaignid,
	@Campaignname,
	@Tag,
	@Mailinglist,
	@SendId,
	
	@Timestamp,
	@Token,
	@Signature,
	@Bodyplaintext
)

--endregion
GO