SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[ActiveUserCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ActiveUserCreate]
-- Date Generated: Monday, June 5, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ActiveUserCreate]
	@Expiration datetime,
	@Userid int,
	@Created datetime,
	@Createdbyid INT
  

AS

SET NOCOUNT ON

INSERT INTO [dbo].[ActiveUsers] (
	[Expiration],
	[UserId],
	[Created],
	[CreatedById]
) 
OUTPUT		
		inserted.Id AS ID, inserted.[RowVersion]  AS [VERSION]
VALUES (
	@Expiration,
	@Userid,
	@Created,
	@Createdbyid
)

--endregion

GO