SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BulkServiceDiscountGetByServiceIDByQuantity]
	@ID			int,
	@Quantity	int
AS
	SET NOCOUNT ON;
	
	SELECT
		DISCOUNT_ID,
		DISCOUNT_HIGHTHRESHOLD,
		DISCOUNT_LOWTHRESHOLD,
		DISCOUNT_PERCENT,
		DISCOUNT_SERVICEID,		
		DISCOUNT_UNITPRICE,
		DISCOUNT_ROWVERSION
	FROM 
		BulkServiceDiscounts 
	WHERE 
		(DISCOUNT_ID = @ID) AND
		((DISCOUNT_LOWTHRESHOLD <= @Quantity) AND 
			(DISCOUNT_HIGHTHRESHOLD >= @Quantity));
GO