SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingChargeOverRawLogCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverRawLogCreate]
-- Date Generated: Tuesday, May 2, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverRawLogCreate]
	@Rawrequest varchar(max),
	@Created datetime,
	@Createdbyid int,
	@Chargeoverlogitemid int

AS

SET NOCOUNT ON

INSERT INTO [dbo].[Billing_ChargeOverRawLog] (
	[RawRequest],
	[Created],
	[CreatedById],
	[ChargeOverLogItemId]
) 
OUTPUT		
		inserted.Id AS ID,NULL AS [Version]
VALUES (
	@Rawrequest,
	@Created,
	@Createdbyid,
	@Chargeoverlogitemid
)

--endregion

GO