SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryItemImageGetByItemIDByIndex]
	@ItemID			int
	, @Index		int	
	, @IsThumbnail	bit
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT
		INVENTORYITEMIMAGE_ID
		, INVENTORYITEMIMAGE_CONTENTTYPE
		, INVENTORYITEMIMAGE_DATA
		, INVENTORYITEMIMAGE_FILEEXTENSION
		, INVENTORYITEMIMAGE_INDEX
		, INVENTORYITEMIMAGE_INVENTORYITEMID
		, INVENTORYITEMIMAGE_ISTHUMBNAIL
		, INVENTORYITEMIMAGE_LASTUPDATED
	FROM
		[dbo].[InventoryItemImages]
	WHERE
		INVENTORYITEMIMAGE_INDEX = @Index
		AND INVENTORYITEMIMAGE_INVENTORYITEMID = @ItemID
		AND INVENTORYITEMIMAGE_ISTHUMBNAIL = @IsThumbnail;
END
GO