SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailDatFilesetGetByID] 
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		MAILDATFILESET_ID
		, MAILDATFILESET_CONTENTTYPE
		, MAILDATFILESET_DATA
		, MAILDATFILESET_DATETIME
		, MAILDATFILESET_FILENAME
		, MAILDATFILESET_JOBID
    FROM
		[dbo].[MailDatFilesets]
	WHERE
		MAILDATFILESET_ID = @ID
	ORDER BY
		MAILDATFILESET_ID;
END
GO