SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


--region [dbo].[SendGridNewsletterGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[SendGridNewsletterGetById]
-- Date Generated: Monday, September 21, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[SendGridNewsletterGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[NewsletterUserListId],
	[NewsletterSendId]
FROM
	[dbo].[SendGridNewsletters]
WHERE
	[Id] = @Id

--endregion
GO