SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[CommentThreadCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[CommentThreadCreate]
-- Date Generated: Tuesday, May 23, 2017
------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[CommentThreadCreate]
	AS

SET NOCOUNT ON

INSERT INTO [dbo].[CommentThreads]
OUTPUT		
		inserted.Id AS ID, NULL AS [Version]
 DEFAULT VALUES
--endregion

GO