SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailDropLogUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailDropLogUpdate]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailDropLogUpdate]
	@Id int,
	@Event varchar(50),
	@Recipient varchar(500),
	@Domain varchar(500),
	@Messageheaders varchar(4000),
	@MessageId varchar(100),
	@Reason varchar(500),
	@Code varchar(500),
	@Description varchar(1000),
	@SendId int,
	
	@Timestamp varchar(50),
	@Token varchar(50),
	@Signature varchar(500)
AS

SET NOCOUNT ON

UPDATE [dbo].[mailgun_DropLog] SET
	[Event] = @Event,
	[Recipient] = @Recipient,
	[Domain] = @Domain,
	[MessageHeaders] = @Messageheaders,
	[MessageId] = @MessageId,
	[Reason] = @Reason,
	[Code] = @Code,
	[Description] = @Description,
	[SendId] = @SendId,
	
	[Timestamp] = @Timestamp,
	[Token] = @Token,
	[Signature] = @Signature
WHERE
	[Id] = @Id

--endregion
GO