SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[UserImageDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[UserImageDeleteById]
-- Date Generated: Wednesday, July 5, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[UserImageDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[UserImages]
WHERE
	[Id] = @Id

--endregion

GO