SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailReportByJobIDGroupByNdc] 
	@ID			int	
AS
BEGIN
	SET NOCOUNT ON;
	
	--DECLARE #MailPieces TABLE (
	--	[MAILPIECE_ID] [int] PRIMARY KEY NOT NULL,
	--	[MAILPIECE_ADDRESS1] [nvarchar](60) NULL,
	--	[MAILPIECE_ADDRESS2] [nvarchar](60) NULL,
	--	[MAILPIECE_ADDRESS3] [nvarchar](60) NULL,
	--	[MAILPIECE_BARCODE] [char](31) NOT NULL,
	--	[MAILPIECE_CITY] [nvarchar](20) NULL,
	--	[MAILPIECE_COMPANY] [nvarchar](50) NULL,
	--	[MAILPIECE_FIRSTNAME] [nvarchar](20) NULL,
	--	[MAILPIECE_GROUPID] [nvarchar](25) NULL,
	--	[MAILPIECE_INDIVIDUALID] [nvarchar](25) NULL,
	--	[MAILPIECE_LASTNAME] [nvarchar](20) NULL,
	--	[MAILPIECE_PACKAGEID] [int] NOT NULL,
	--	[MAILPIECE_SCFSERVICEAREAID] [int] NOT NULL,
	--	[MAILPIECE_STATE] [char](2) NULL,
	--	[MAILPIECE_TITLE] [nvarchar](50) NULL,
	--	[MAILPIECE_ZIPCODE] [char](9) NULL,
	--	[PACKAGE_ID] int NOT NULL,
	--	[PACKAGE_DROPDATE] datetime NOT NULL,
	--	[PACKAGE_JOBID] int NOT NULL
	--);
	
	CREATE TABLE #MailPieces (
		[MAILPIECE_ID] [int] NOT NULL,
		[MAILPIECE_ADDRESS1] [nvarchar](60) NULL,
		[MAILPIECE_ADDRESS2] [nvarchar](60) NULL,
		[MAILPIECE_ADDRESS3] [nvarchar](60) NULL,
		[MAILPIECE_BARCODE] [char](31) NOT NULL,
		[MAILPIECE_CITY] [nvarchar](20) NULL,
		[MAILPIECE_COMPANY] [nvarchar](50) NULL,
		[MAILPIECE_FIRSTNAME] [nvarchar](20) NULL,
		[MAILPIECE_GROUPID] [nvarchar](25) NULL,
		[MAILPIECE_INDIVIDUALID] [nvarchar](25) NULL,
		[MAILPIECE_LASTNAME] [nvarchar](20) NULL,
		[MAILPIECE_PACKAGEID] [int] NOT NULL,
		[MAILPIECE_SCFSERVICEAREAID] [int] NOT NULL,
		[MAILPIECE_STATE] [char](2) NULL,
		[MAILPIECE_TITLE] [nvarchar](50) NULL,
		[MAILPIECE_ZIPCODE] [char](9) NULL,
		[PACKAGE_ID] int NOT NULL,
		[PACKAGE_DROPDATE] datetime NOT NULL,
		[PACKAGE_JOBID] int NOT NULL,
		CONSTRAINT [PK_MailPieces] PRIMARY KEY CLUSTERED 
		(
			[MAILPIECE_ID] ASC
		)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]		
	);
	
	INSERT INTO #MailPieces
	(
		MAILPIECE_ID
		, MAILPIECE_ADDRESS1
		, MAILPIECE_ADDRESS2
		, MAILPIECE_ADDRESS3
		, MAILPIECE_BARCODE
		, MAILPIECE_CITY
		, MAILPIECE_COMPANY
		, MAILPIECE_FIRSTNAME
		, MAILPIECE_GROUPID
		, MAILPIECE_INDIVIDUALID
		, MAILPIECE_LASTNAME
		, MAILPIECE_PACKAGEID
		, MAILPIECE_SCFSERVICEAREAID
		, MAILPIECE_STATE
		, MAILPIECE_TITLE
		, MAILPIECE_ZIPCODE
		, PACKAGE_ID
		, PACKAGE_DROPDATE
		, PACKAGE_JOBID
	)
	SELECT
		m.MAILPIECE_ID
		, m.MAILPIECE_ADDRESS1
		, m.MAILPIECE_ADDRESS2
		, m.MAILPIECE_ADDRESS3
		, m.MAILPIECE_BARCODE
		, m.MAILPIECE_CITY
		, m.MAILPIECE_COMPANY
		, m.MAILPIECE_FIRSTNAME
		, m.MAILPIECE_GROUPID
		, m.MAILPIECE_INDIVIDUALID
		, m.MAILPIECE_LASTNAME
		, m.MAILPIECE_PACKAGEID
		, m.MAILPIECE_SCFSERVICEAREAID
		, m.MAILPIECE_STATE
		, m.MAILPIECE_TITLE
		, m.MAILPIECE_ZIPCODE
		, p.PACKAGE_ID
		, p.PACKAGE_DROPDATE
		, p.PACKAGE_JOBID
	FROM
		[dbo].[MailPieces] AS m
		INNER JOIN [dbo].[Packages] AS p
			ON m.MAILPIECE_PACKAGEID = p.PACKAGE_ID
	WHERE
		p.PACKAGE_JOBID = @ID;
	
	SELECT
		s.SCF_NDCID 
		, COUNT(*) AS COUNT
	FROM
		--[dbo].[MailPieces] AS m			
		--INNER JOIN [dbo].[Packages] AS p			
		--	ON m.MAILPIECE_PACKAGEID = p.PACKAGE_ID
		#MailPieces AS m
		INNER JOIN [dbo].[SCFServiceAreas] AS sa
			ON m.MAILPIECE_SCFSERVICEAREAID = sa.SCFSERVICEAREA_ID
		INNER JOIN [dbo].[SCFs] AS s
			ON sa.SCFSERVICEAREA_SCFID = s.SCF_ID				
	GROUP BY
		s.SCF_NDCID
	ORDER BY
		s.SCF_NDCID;
		
	SELECT
		scf.SCF_NDCID
		, COUNT(DISTINCT scans.MAILPIECESCAN_MAILPIECEID) AS COUNT
	FROM
		[dbo].[MailPieceScans] AS scans
		--INNER JOIN [dbo].[MailPieces] AS p
		--	ON scans.MAILPIECESCAN_MAILPIECEID = p.MAILPIECE_ID
		INNER JOIN #MailPieces AS m
			ON scans.MAILPIECESCAN_MAILPIECEID = m.MAILPIECE_ID
		INNER JOIN [dbo].Packages AS pkg
			ON m.MAILPIECE_PACKAGEID = pkg.PACKAGE_ID
		INNER JOIN [dbo].[SCFServiceAreas] as scfAreas
			ON m.MAILPIECE_SCFSERVICEAREAID = scfAreas.SCFSERVICEAREA_ID
		INNER JOIN [dbo].[SCFs] AS scf
			ON scfAreas.SCFSERVICEAREA_SCFID = scf.SCF_ID		
	--WHERE		
	--	pkg.PACKAGE_JOBID = @ID
	GROUP BY
		scf.SCF_NDCID
	ORDER BY
		scf.SCF_NDCID;
		
	SELECT
		scf.SCF_NDCID
		, COUNT(DISTINCT scans.MAILPIECESCAN_MAILPIECEID) AS COUNT
	FROM
		[dbo].[MailPieceScans] AS scans
		INNER JOIN [dbo].[Operations] AS o
			ON scans.MAILPIECESCAN_OPERATIONID = o.OPERATION_ID
		--INNER JOIN [dbo].[MailPieces] AS p
		--	ON scans.MAILPIECESCAN_MAILPIECEID = p.MAILPIECE_ID
		--INNER JOIN [dbo].Packages AS pkg
		--	ON p.MAILPIECE_PACKAGEID = pkg.PACKAGE_ID
		INNER JOIN #MailPieces AS m
			ON scans.MAILPIECESCAN_MAILPIECEID = m.MAILPIECE_ID
		INNER JOIN [dbo].[SCFServiceAreas] as scfAreas
			ON m.MAILPIECE_SCFSERVICEAREAID = scfAreas.SCFSERVICEAREA_ID
		INNER JOIN [dbo].[SCFs] AS scf
			ON scfAreas.SCFSERVICEAREA_SCFID = scf.SCF_ID				
	WHERE		
		o.OPERATION_CUTOFF IS NOT NULL
		--AND pkg.PACKAGE_JOBID = @ID
	GROUP BY
		scf.SCF_NDCID
	ORDER BY
		scf.SCF_NDCID;
		
	SELECT
		scf.SCF_NDCID
		, AVG(DATEDIFF(MINUTE, m.PACKAGE_DROPDATE, scans.MAILPIECESCAN_DATETIME)) AS [AVG MINUTES]
	FROM
		--[dbo].[MailPieces] AS p			
		#MailPieces AS m
		INNER JOIN [dbo].[MailPieceScans] AS scans		
			ON scans.MAILPIECESCAN_ID = 
		(
			SELECT TOP 1
				s.MAILPIECESCAN_ID 
			FROM
				[dbo].[MailPieceScans] AS s			
			INNER JOIN [dbo].[Operations] AS o
				ON s.MAILPIECESCAN_OPERATIONID = o.OPERATION_ID
			WHERE
				o.OPERATION_CUTOFF IS NOT NULL
				--AND s.MAILPIECESCAN_MAILPIECEID = p.MAILPIECE_ID
				AND s.MAILPIECESCAN_MAILPIECEID = m.MAILPIECE_ID
			ORDER BY
				s.MAILPIECESCAN_DATETIME
		)
		--INNER JOIN [dbo].Packages AS pkg
		--	ON p.MAILPIECE_PACKAGEID = pkg.PACKAGE_ID
		INNER JOIN [dbo].[SCFServiceAreas] as scfAreas
			ON m.MAILPIECE_SCFSERVICEAREAID = scfAreas.SCFSERVICEAREA_ID
		INNER JOIN [dbo].[SCFs] AS scf
			ON scfAreas.SCFSERVICEAREA_SCFID = scf.SCF_ID				
	--WHERE				
	--	pkg.PACKAGE_JOBID = @ID
	GROUP BY
		scf.SCF_NDCID
	ORDER BY
		scf.SCF_NDCID;	
	
	DECLARE @ScansTable TABLE
	(
		SCAN_DATETIME datetime --PRIMARY KEY CLUSTERED
	);

	INSERT INTO @ScansTable (SCAN_DATETIME)
	SELECT DISTINCT
		MAILPIECESCAN_DATETIME
	FROM
		[dbo].[MailPieces] AS p			
		INNER JOIN [dbo].[MailPieceScans] AS scans
			ON scans.MAILPIECESCAN_ID = 
		(
			SELECT TOP 1
				s.MAILPIECESCAN_ID 
			FROM
				[dbo].[MailPieceScans] AS s			
			INNER JOIN [dbo].[Operations] AS o
				ON s.MAILPIECESCAN_OPERATIONID = o.OPERATION_ID
			WHERE
				o.OPERATION_CUTOFF IS NOT NULL
				AND s.MAILPIECESCAN_MAILPIECEID = p.MAILPIECE_ID
			ORDER BY
				s.MAILPIECESCAN_DATETIME
		)
		INNER JOIN [dbo].Packages AS pkg
			ON p.MAILPIECE_PACKAGEID = pkg.PACKAGE_ID				
	WHERE				
		pkg.PACKAGE_JOBID = @ID;
		
	DECLARE @StartDate datetime;	
	SET @StartDate = (SELECT DATEADD(dd, 0, DATEDIFF(dd, 0, MIN(SCAN_DATETIME)))FROM @ScansTable);	
	DECLARE @EndDate datetime;
	SET @EndDate = (SELECT DATEADD(dd, 1, DATEDIFF(dd, 0, MAX(SCAN_DATETIME)))FROM @ScansTable);

	SELECT
		scf.SCF_NDCID
		, DATEADD(dd, 0, DATEDIFF(dd, 0, MAX(MAILPIECESCAN_DATETIME))) AS [DATE]
		, COUNT(scans.MAILPIECESCAN_MAILPIECEID) AS COUNT
	FROM
		[dbo].[MailPieces] AS p			
		INNER JOIN [dbo].[MailPieceScans] AS scans
			ON scans.MAILPIECESCAN_ID = 
		(
			SELECT TOP 1
				s.MAILPIECESCAN_ID 
			FROM
				[dbo].[MailPieceScans] AS s			
			INNER JOIN [dbo].[Operations] AS o
				ON s.MAILPIECESCAN_OPERATIONID = o.OPERATION_ID
			WHERE
				o.OPERATION_CUTOFF IS NOT NULL
				AND s.MAILPIECESCAN_MAILPIECEID = p.MAILPIECE_ID
			ORDER BY
				s.MAILPIECESCAN_DATETIME
		)
		INNER JOIN [dbo].Packages AS pkg
			ON p.MAILPIECE_PACKAGEID = pkg.PACKAGE_ID
		INNER JOIN [dbo].[SCFServiceAreas] as scfAreas
			ON p.MAILPIECE_SCFSERVICEAREAID = scfAreas.SCFSERVICEAREA_ID
		INNER JOIN [dbo].[SCFs] AS scf
			ON scfAreas.SCFSERVICEAREA_SCFID = scf.SCF_ID		
	WHERE
		pkg.PACKAGE_JOBID = @ID
		AND (scans.MAILPIECESCAN_DATETIME >= @StartDate AND scans.MAILPIECESCAN_DATETIME <= @EndDate)
	GROUP BY
		scf.SCF_NDCID 
		, DATEADD(dd, 0, DATEDIFF(dd, 0, MAILPIECESCAN_DATETIME)) 
	ORDER BY
		scf.SCF_NDCID, [DATE];
END
GO