SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingInvoiceUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingInvoiceUpdate]
-- Date Generated: Monday, April 24, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingInvoiceUpdate]
@Version				timestamp,
	@Id int,
	@Amount decimal(18, 4),
	@Clientid int,
	@Created datetime,
	@Createdbyid int,
	@Invoicebegindate datetime,
	@Invoiceenddate datetime,
	@Usage int,
	@Paymentstatus int,
	@Providerinvoiceid varchar(50)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingInvoice] SET
	[Amount] = @Amount,
	[ClientId] = @Clientid,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[InvoiceBeginDate] = @Invoicebegindate,
	[InvoiceEndDate] = @Invoiceenddate,
	[Usage] = @Usage,
	[PaymentStatus] = @Paymentstatus,
	[ProviderInvoiceId] = @Providerinvoiceid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO