SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingTierCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTierCreate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingTierCreate]
	@Tierid int,
	@Tiersetid int,
	@Unitfrom decimal(18, 4),
	@Unitto decimal(18, 4),
	@Amount decimal(18, 4)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingTier] (
	[TierId],
	[TiersetId],
	[UnitFrom],
	[UnitTo],
	[Amount]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Tierid,
	@Tiersetid,
	@Unitfrom,
	@Unitto,
	@Amount
)

--endregion

GO