SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_RejectRecordsGetPrintKeyCountsByTransactionDateRange] (
  @DateFrom	datetime	= NULL
  , @DateTo		datetime	= NULL  
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		REJECTRECORD_PRINTKEY AS PRINTKEY
		, NULL AS PRINTKEY_EFFORT
		, COUNT(*) AS PRINTKEY_COUNT
	FROM 
		[dbo].[colpenn_RejectRecords] 
	WHERE
		(@DateFrom IS NULL OR REJECTRECORD_TRANSACTIONDATE >= @DateFrom)
		AND (@DateTo IS NULL OR REJECTRECORD_TRANSACTIONDATE <= @DateTo)
	GROUP BY
		REJECTRECORD_PRINTKEY
END
GO