SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryNotificationSubscriberGetByID] 	
	@ID int
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT 
		INVENTORYNOTIFICATIONSUBSCRIBER_ID
		, INVENTORYNOTIFICATIONSUBSCRIBER_EVENTS
		, INVENTORYNOTIFICATIONSUBSCRIBER_INVENTORYITEMID
		, INVENTORYNOTIFICATIONSUBSCRIBER_USERID
	FROM
		[dbo].[InventoryNotificationSubscribers]
	WHERE
		INVENTORYNOTIFICATIONSUBSCRIBER_ID = @ID;
	
END
GO