SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ComminglersGetAutoComplete]
	@ID				int 
	, @Substring	nvarchar(255)
AS
BEGIN
			
	SET NOCOUNT ON;

    WITH CTE 
	AS
	(
		(SELECT
			co.COMMINGLER_ID
			, co.COMMINGLER_ADDRESS1
			, co.COMMINGLER_ADDRESS2			
			, co.COMMINGLER_CITY
			, co.COMMINGLER_CONTACT
			, co.COMMINGLER_EMAIL			
			, co.COMMINGLER_FAX
			, co.COMMINGLER_INTERNAL
			, co.COMMINGLER_LEGALNAME
			, co.COMMINGLER_NAME
			, co.COMMINGLER_PARENTID
			, co.COMMINGLER_PHONE
			, co.COMMINGLER_POSTALCODE
			, co.COMMINGLER_PUBLIC
			, co.COMMINGLER_REGION
			, co.COMMINGLER_SHORTNAME
			, co.COMMINGLER_URL
			, co.COMMINGLER_ROWVERSION
		FROM [dbo].[Comminglers] AS co
			INNER JOIN [dbo].[ComminglerClients] AS c
				ON co.COMMINGLER_ID = c.COMMINGLERCLIENT_COMMINGLERID
			INNER JOIN [dbo].[Relationships] AS r
				ON c.COMMINGLERCLIENT_CLIENTID = r.RELATIONSHIP_CLIENTID
		WHERE 
			co.COMMINGLER_PARENTID IS NULL
			AND (r.RELATIONSHIP_USERID = @ID)

			UNION
		
		SELECT 
			co.COMMINGLER_ID
			, co.COMMINGLER_ADDRESS1
			, co.COMMINGLER_ADDRESS2
			, co.COMMINGLER_CITY
			, co.COMMINGLER_CONTACT
			, co.COMMINGLER_EMAIL
			, co.COMMINGLER_FAX
			, co.COMMINGLER_INTERNAL
			, co.COMMINGLER_LEGALNAME
			, co.COMMINGLER_NAME
			, co.COMMINGLER_PARENTID
			, co.COMMINGLER_PHONE
			, co.COMMINGLER_POSTALCODE
			, co.COMMINGLER_PUBLIC
			, co.COMMINGLER_REGION
			, co.COMMINGLER_SHORTNAME
			, co.COMMINGLER_URL
			, co.COMMINGLER_ROWVERSION
		FROM [dbo].[Comminglers] AS co
			INNER JOIN [dbo].[ComminglerClients] AS c
				ON co.COMMINGLER_ID = c.COMMINGLERCLIENT_COMMINGLERID
			INNER JOIN [dbo].[Users] AS u
				ON c.COMMINGLERCLIENT_ID = u.USER_CLIENT_ID
		WHERE 
			u.USER_USERID = @ID
		)
			
		UNION ALL

		SELECT 
			co.COMMINGLER_ID
			, co.COMMINGLER_ADDRESS1
			, co.COMMINGLER_ADDRESS2			
			, co.COMMINGLER_CITY
			, co.COMMINGLER_CONTACT
			, co.COMMINGLER_EMAIL			
			, co.COMMINGLER_FAX
			, co.COMMINGLER_INTERNAL
			, co.COMMINGLER_LEGALNAME
			, co.COMMINGLER_NAME
			, co.COMMINGLER_PARENTID
			, co.COMMINGLER_PHONE
			, co.COMMINGLER_POSTALCODE
			, co.COMMINGLER_PUBLIC
			, co.COMMINGLER_REGION
			, co.COMMINGLER_SHORTNAME
			, co.COMMINGLER_URL
			, co.COMMINGLER_ROWVERSION			
		FROM [dbo].[Comminglers] AS co
			INNER JOIN [dbo].[ComminglerClients] AS c
				ON co.COMMINGLER_ID = c.COMMINGLERCLIENT_COMMINGLERID
			INNER JOIN [dbo].[Relationships] AS r
				ON c.COMMINGLERCLIENT_CLIENTID = r.RELATIONSHIP_CLIENTID			
			INNER JOIN CTE
				ON CTE.COMMINGLER_ID = co.COMMINGLER_PARENTID
		WHERE 
			co.COMMINGLER_PARENTID IS NOT NULL
			AND r.RELATIONSHIP_USERID = @ID
	)	
	SELECT 
		COMMINGLER_ID
		, COMMINGLER_ADDRESS1
		, COMMINGLER_ADDRESS2			
		, COMMINGLER_CITY
		, COMMINGLER_CONTACT
		, COMMINGLER_EMAIL			
		, COMMINGLER_FAX
		, COMMINGLER_INTERNAL
		, COMMINGLER_LEGALNAME
		, COMMINGLER_NAME
		, COMMINGLER_PARENTID
		, COMMINGLER_PHONE
		, COMMINGLER_POSTALCODE
		, COMMINGLER_PUBLIC
		, COMMINGLER_REGION
		, COMMINGLER_SHORTNAME
		, COMMINGLER_URL
		, COMMINGLER_ROWVERSION
	FROM 
		CTE		
	WHERE
		COMMINGLER_NAME LIKE '%' + @Substring + '%'
		OR COMMINGLER_SHORTNAME LIKE '%' + @Substring + '%'
END
GO