SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MachineGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT 
		MACHINE_ID
		, MACHINE_CODE
		, MACHINE_DESCRIPTION
	FROM 
		[dbo].[Machines]
	WHERE
		MACHINE_ID = @ID
END
GO