SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailBannedDomainInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailBannedDomainInsert]
-- Date Generated: Tuesday, November 3, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailBannedDomainInsert]
	@Domain nvarchar(4000)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[mailgun_BannedDomains] (
	[Domain]
) 
OUTPUT		
		inserted.Id AS ID
VALUES (
	@Domain
)

--endregion
GO