SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DistrictGetByID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		DISTRICT_ID
		, DISTRICT_CODE
		, DISTRICT_NAME
	FROM
		[dbo].[Districts]
	WHERE
		DISTRICT_ID = @ID;
END
GO