SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[UserImageCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[UserImageCreate]
-- Date Generated: Wednesday, July 5, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[UserImageCreate]
	@Classname varchar(200),
	@Contenttypeid int,
	@Compressed bit,
	@Created datetime,
	@Createdbyid int,
	@Data varbinary(max),
	@Description nvarchar(200),
	@Name nvarchar(2000),
	@Size bigint,
	@Typeid int,
	@Uploaded datetime

AS

SET NOCOUNT ON

INSERT INTO [dbo].[UserImages] (
	[ClassName],
	[ContentTypeId],
	[Compressed],
	[Created],
	[CreatedById],
	[Data],
	[Description],
	[Name],
	[Size],
	[TypeId],
	[Uploaded]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Classname,
	@Contenttypeid,
	@Compressed,
	@Created,
	@Createdbyid,
	@Data,
	@Description,
	@Name,
	@Size,
	@Typeid,
	@Uploaded
)

--endregion

GO