SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PostalCodeFormatsGet]
	@ID	int = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		FORMAT_ID
		, FORMAT_COUNTRYID
		, FORMAT_FORMATSTRING
		, FORMAT_PATTERN
	FROM
		[dbo].[PostalCodeFormats]
	WHERE
		FORMAT_COUNTRYID = CASE WHEN @ID IS NULL THEN FORMAT_COUNTRYID ELSE @ID END;
	
END
GO