SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[SubscriberDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[SubscriberDeleteById]
-- Date Generated: Tuesday, May 19, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[SubscriberDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Subscribers]
WHERE
	[Id] = @Id

--endregion
GO