SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProjectsGetByClientID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		PROJECT_ID
		, PROJECT_CLIENTID
		, PROJECT_PARENTID
		, PROJECT_NAME
		, PROJECT_ROWVERSION 
	FROM 
		[dbo].[Projects]
	WHERE
		PROJECT_CLIENTID = @ID
	ORDER BY
		PROJECT_ID;
END
GO