SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ExceptionItemGetByID]
	@ID					int
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT
		EXCEPTION_ID
		, EXCEPTION_DATA
		, EXCEPTION_DATETIME
		, EXCEPTION_EXCEPTIONSTACK
		, EXCEPTION_HOSTNAME
		, EXCEPTION_IPADDRESS
		, EXCEPTION_MESSAGE
		, EXCEPTION_QUERY
		, EXCEPTION_RESPONSESTATUS
		, EXCEPTION_SERVERNAME
		, EXCEPTION_SOURCE
		, EXCEPTION_TARGET
		, EXCEPTION_TYPE
		, EXCEPTION_URL
		, EXCEPTION_USERAGENT
		, EXCEPTION_USERID
	FROM 
		Exceptions 
	WHERE 
		EXCEPTION_ID = @ID;
END
GO