SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptsGetByTextSearchItemCode] 
  @Substring NVARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
    DISTINCT
		INVENTORYRECEIPT_ID,			
			INVENTORYRECEIPT_CREATED,
			INVENTORYRECEIPT_CREATEDBYID,
			INVENTORYRECEIPT_DESCRIPTION,					
			INVENTORYRECEIPT_RECEIVED,
			INVENTORYRECEIPT_RECEIVEDBY,		
			INVENTORYRECEIPT_SHIPCOMPANY,
			INVENTORYRECEIPT_SUPPLIERCOMPANY,			
			INVENTORYRECEIPT_ROWVERSION
	FROM 
		[dbo].[InventoryReceipts]
    INNER JOIN dbo.InventoryReceiptItems iri ON iri.INVENTORYRECEIPTITEM_RECEIPTID = INVENTORYRECEIPT_ID
    INNER JOIN dbo.InventoryItems ii ON ii.ID = iri.INVENTORYRECEIPTITEM_ITEMID
	WHERE 
		CONTAINS(ii.Code, @Substring)
END
GO