SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingTierGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTierGetById]
-- Date Generated: Friday, June 16, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingTierGetByTierId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[TierId],
	[UnitFrom],
	[UnitTo],
	[Amount]
FROM
	[dbo].[BillingTier]
WHERE
	[TierId] = @Id

--endregion
GO