SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_PsiSlipsGetByDateRange]
	@From	date = NULL
	, @To	date = NULL
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		PSISLIP_ID
		, PSISLIP_CONTENTTYPE
		, PSISLIP_DATA
		, PSISLIP_DATE
		, PSISLIP_FILENAME
		, PSISLIP_UPLOADED
    FROM
		[dbo].[colpenn_PsiSlips]
	WHERE
		(@From IS NULL OR PSISLIP_DATE >= @From)
		AND (@To IS NULL OR PSISLIP_DATE <= @To)
	ORDER BY
		PSISLIP_ID;
END
GO