SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailPieceScanGetByID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT
		MAILPIECESCAN_ID
		, MAILPIECESCAN_CREATED
		, MAILPIECESCAN_DATETIME
		, MAILPIECESCAN_FACILITYID
		, MAILPIECESCAN_MAILPIECEID
		, MAILPIECESCAN_OPERATIONID
	FROM
		[dbo].[MailPieceScans]
	WHERE
		MAILPIECESCAN_ID = @ID;
END
GO