SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[MailStreamCreate] 	
	@Name nvarchar(50)
AS
BEGIN

	SET NOCOUNT ON;
	
	IF EXISTS(SELECT MAILSTREAM_ID FROM MailStreams WHERE MAILSTREAM_NAME = @Name)
		RETURN 0;

	INSERT MailStreams
	(
		MAILSTREAM_NAME
	) 
	OUTPUT		
		inserted.MAILSTREAM_ID AS ID, NULL AS [VERSION]
	VALUES 
	(
		@Name
	);
END
GO