SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[OptionsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[OptionsGetAll]
-- Date Generated: Wednesday, October 12, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[OptionsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[UserId],
	[Json],
	[RowVersion]
FROM
	[dbo].[Options]

--endregion

GO