SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[UsersGetActiveByClientIDByRelationship]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
DECLARE @CLIENT_ID INT;
  SELECT @CLIENT_ID = USER_CLIENT_ID FROM dbo.Users u WHERE u.USER_USERID = @ID;
  DECLARE @CLIENT_TYPE INT;
  SELECT @CLIENT_TYPE = CLIENT_TYPE FROM dbo.Clients WHERE CLIENT_ID = @CLIENT_ID;

IF @CLIENT_TYPE = 16 OR @CLIENT_TYPE IS NULL
    BEGIN
    SELECT DISTINCT
		USER_USERID
		, USER_ADDRESS1
		, USER_ADDRESS2
		, USER_CITY
		, USER_CLIENT_ID
		, USER_CREATED
		, USER_CREATEDBY_ID
		, USER_DEFAULTURL		
		, USER_FAX
    		, USER_FIRSTNAME
		, USER_INACTIVELOGOUT
		, USER_LASTNAME
		, USER_LOCKEDOUT		
		, USER_PHONE
		, USER_POSTALCODE
		, USER_REGION
		, USER_ROLES
		, USER_SECONDARY_EMAIL
		, USER_USERNAME
		, USER_ROWVERSION
      , r.RELATIONSHIP_USERID
    FROM 
		[dbo].[Users] u
	INNER JOIN [dbo].[Clients] AS c
				ON (u.USER_CLIENT_ID = c.CLIENT_ID)
			INNER JOIN [dbo].[Relationships] AS r
				ON r.RELATIONSHIP_CLIENTID = c.CLIENT_ID
      WHERE r.RELATIONSHIP_USERID = @ID
					--AND c.CLIENT_ID = r.RELATIONSHIP_CLIENTID
      
  END
ELSE
  BEGIN
SELECT DISTINCT
		u.USER_USERID
		, u.USER_ADDRESS1
		, u.USER_ADDRESS2
		, u.USER_CITY
		, u.USER_CLIENT_ID
		, u.USER_CREATED
		, u.USER_CREATEDBY_ID
		, u.USER_DEFAULTURL		
		, u.USER_FAX
		, u.USER_FIRSTNAME
		, u.USER_INACTIVELOGOUT
		, u.USER_LASTNAME
		, u.USER_LOCKEDOUT		
		, u.USER_PHONE
		, u.USER_POSTALCODE
		, u.USER_REGION
		, u.USER_ROLES
		, u.USER_SECONDARY_EMAIL
		, u.USER_USERNAME
		, u.USER_ROWVERSION
  
    FROM 
		[dbo].[Users] AS u  
  LEFT JOIN dbo.ClientRelationships cr ON cr.ParentClientId = u.USER_CLIENT_ID OR cr.PartnerClientId = u.USER_CLIENT_ID
  INNER JOIN dbo.Clients c ON c.CLIENT_ID = cr.PartnerClientId OR cr.ParentClientId = c.CLIENT_ID
  INNER JOIN dbo.Users cRu ON cRu.USER_CLIENT_ID = c.CLIENT_ID OR cRu.USER_CLIENT_ID = @CLIENT_ID
  INNER JOIN dbo.ActiveUsers au ON au.UserId = cRu.USER_USERID
  WHERE cr.ParentClientId = @CLIENT_ID OR cr.PartnerClientId = @CLIENT_ID
  --AND cRu.USER_LOCKEDOUT != 1 

  END

END
GO