SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RelationshipGetByClientIDByUserID] 
	@ClientID	int,
	@UserID		int
AS
BEGIN		
    SET NOCOUNT ON;

	SELECT
		RELATIONSHIP_ID
		, RELATIONSHIP_CLIENTID
		, RELATIONSHIP_USERID
		, RELATIONSHIP_ROWVERSION
	FROM 
		Relationships 
	WHERE 
		(RELATIONSHIP_CLIENTID = @ClientID)	AND 
		(RELATIONSHIP_USERID = @UserID)
	ORDER BY 
		RELATIONSHIP_ID;
END
GO