SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[EmailContactInfoUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailContactInfoUpdate]
-- Date Generated: Wednesday, May 13, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailContactInfoUpdate]
	@Id int,
	@Address varchar(200),
	@Subscriberid int
AS

SET NOCOUNT ON

UPDATE [dbo].[EmailContactInfo] SET
	[Address] = @Address,
	[SubscriberId] = @Subscriberid
WHERE
	[Id] = @Id

--endregion
GO