SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailPhaseGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT 
		MAILPHASE_ID
		, MAILPHASE_DESCRIPTION
	FROM 
		[dbo].[MailPhases]
	WHERE
		MAILPHASE_ID = @ID
END
GO