SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InternalUsersGetAutocomplete]
	@ID				int
	, @Substring	nvarchar(255)
AS
BEGIN
			
	SET NOCOUNT ON;

    
	SELECT 
		USER_USERID
		, USER_ADDRESS1
		, USER_ADDRESS2
		, USER_CITY
		, USER_CLIENT_ID
		, USER_CREATED
		, USER_CREATEDBY_ID
		, USER_DEFAULTURL		
		, USER_FAX
    		, USER_FIRSTNAME
		, USER_INACTIVELOGOUT
		, USER_LASTNAME
		, USER_LOCKEDOUT		
		, USER_PHONE
		, USER_POSTALCODE
		, USER_REGION
		, USER_ROLES
		, USER_SECONDARY_EMAIL
		, USER_USERNAME
		, USER_ROWVERSION
	FROM 
		[dbo].[Users] As u		
		INNER JOIN dbo.Clients as c
			ON c.CLIENT_ID = u.USER_CLIENT_ID				
	WHERE
		(u.USER_DISPLAYNAME LIKE '%' + @Substring + '%'
		OR u.USER_USERNAME LIKE '%' + @Substring + '%')
		AND c.CLIENT_INTERNAL = 1
		
				
END
GO