SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailDropLogGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailDropLogGetById]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailDropLogGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Event],
	[Recipient],
	[Domain],
	[MessageId],
	[MessageHeaders],
	[Reason],
	[Code],
	[Description],
	[SendId],
	
	[Timestamp],
	[Token],
	[Signature]
FROM
	[dbo].[mailgun_DropLog]
WHERE
	[Id] = @Id

--endregion
GO