SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


--region [dbo].[SendGridEventInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[SendGridEventInsert]
-- Date Generated: Monday, September 21, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[SendGridEventInsert]
	@Category varchar(100),
	@Email varchar(400),
	@Eventid varchar(100),
	@Eventname varchar(50),
	@Groupid int,
	@Ip varchar(50),
	@Messageid varchar(50),
	@Newsletterid int,
	@Reason varchar(50),
	@Response varchar(50),
	@Sendat int,
	@SmtpId varchar(200),
	@Status varchar(50),
	@Systemid int,
	@Timestamp int,
	@Type varchar(50),
	@Url varchar(500),
	@Useragent varchar(500),
	@Created DateTime,
	@SendId int
AS

SET NOCOUNT ON

INSERT INTO [dbo].[SendGridEvents] (
	[Category],
	[Email],
	[EventId],
	[EventName],
	[GroupId],
	[Ip],
	[MessageId],
	[NewsletterId],
	[Reason],
	[Response],
	[SendAt],
	[SmtpId],
	[Status],
	[SystemId],
	[TimeStamp],
	[Type],
	[Url],
	[UserAgent],
	Created,
	SendId
) 
OUTPUT		
		inserted.Id AS ID
VALUES (
	@Category,
	@Email,
	@Eventid,
	@Eventname,
	@Groupid,
	@Ip,
	@Messageid,
	@Newsletterid,
	@Reason,
	@Response,
	@Sendat,
	@Smtpid,
	@Status,
	@Systemid,
	@Timestamp,
	@Type,
	@Url,
	@Useragent,
	@Created,
	@SendId
)

--endregion
GO