SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[OptionUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[OptionUpdate]
-- Date Generated: Wednesday, October 12, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[OptionUpdate]
@Version				timestamp,
	@Id int,
	@Userid int,
	@Json varchar(max)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[Options] SET
	[UserId] = @Userid,
	[Json] = @Json
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO