SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WarehouseGetByID]
	@ID		int
AS
BEGIN
	
	SET NOCOUNT ON;
	
	SELECT
		WAREHOUSE_ID
		, WAREHOUSE_CLIENTLOCATIONID
		, WAREHOUSE_NAME
		, WAREHOUSE_ROWVERSION
	FROM 
		Warehouses 
	WHERE WAREHOUSE_ID = @ID;
END
GO