SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingServiceLogDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingServiceLogDeleteById]
-- Date Generated: Wednesday, May 31, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingServiceLogDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[BillingServiceLog]
WHERE
	[Id] = @Id

--endregion

GO