SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PostageUsageItemsGetByJobID]
	@ID	int
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT 
		ui.POSTAGEUSAGEITEM_ID
		, ui.POSTAGEUSAGEITEM_DATETIME		
		, ui.POSTAGEUSAGEITEM_PACKAGEID
		, ui.POSTAGEUSAGEITEM_QUANTITY
		, ui.POSTAGEUSAGEITEM_RATE
		, ui.POSTAGEUSAGEITEM_ROWVERSION
	FROM 
		[dbo].[PostageUsageItems] AS ui
		INNER JOIN [dbo].[Packages] AS p
			ON ui.POSTAGEUSAGEITEM_PACKAGEID = p.PACKAGE_ID
	WHERE 
		p.PACKAGE_JOBID = @ID
	ORDER BY
		ui.POSTAGEUSAGEITEM_ID;
		
END
GO