SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[JobStageRoleCreate]
	@RoleID			int,
	@StageGUID	uniqueidentifier
AS
BEGIN

	SET NOCOUNT ON;
	
	IF EXISTS(SELECT JOBSTAGEROLE_ID FROM tblJobStageRoles 
			  WHERE (JOBSTAGEROLE_ROLEID = @RoleID) AND
					(JOBSTAGEROLE_STAGEGUID = @StageGuid))
		RETURN -1;
		
	INSERT tblJobStageRoles
	(
		JOBSTAGEROLE_ROLEID,
		JOBSTAGEROLE_STAGEGUID
	)
	OUTPUT
		inserted.JOBSTAGEROLE_ID AS ID, inserted.JOBSTAGEROLE_ROWVERSION AS [VERSION]
	VALUES
	(
		@RoleID,
		@StageGUID
	);
END
GO