SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingTierUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTierUpdate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingTierUpdate]
@Version				timestamp,
	@Id int,
	@Tierid int,
	@Tiersetid int,
	@Unitfrom decimal(18, 4),
	@Unitto decimal(18, 4),
	@Amount decimal(18, 4)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingTier] SET
	[TierId] = @Tierid,
	[TiersetId] = @Tiersetid,
	[UnitFrom] = @Unitfrom,
	[UnitTo] = @Unitto,
	[Amount] = @Amount
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO