SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[EmailContactInfosGetBySubscriberId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailContactInfosGetBySubscriberId]
-- Date Generated: Wednesday, May 13, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailContactInfosGetBySubscriberId]
	@Subscriberid int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Address],
	[SubscriberId],
	[Rowversion]
FROM
	[dbo].[EmailContactInfo]
WHERE
	[SubscriberId] = @SubscriberId

--endregion
GO