SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ComminglerClientLocationGetByComminglerIDByValue]	
	@ComminglerID	int
	, @Value		int
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT 
		COMMINGLERLOCATION_ID		
		, COMMINGLERLOCATION_COMMINGLERID
		, COMMINGLERLOCATION_LOCATIONID
		, COMMINGLERLOCATION_VALUE
	FROM 
		[dbo].[ComminglerClientLocations]
	WHERE
		(COMMINGLERLOCATION_VALUE = @Value)
		AND ((COMMINGLERLOCATION_COMMINGLERID = @ComminglerID));
END
GO