SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingItemUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingItemUpdate]
-- Date Generated: Friday, June 16, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingItemUpdate]
@Version				timestamp,
	@Id int,
	@Itemid int,
	@Itemtype varchar(500),
	@Tiersetid int,
	@Name varchar(500),
	@Description varchar(500),
	@Units varchar(50),
	@Enabled bit,
	@Accountingsku varchar(500),
	@Token varchar(50),
	@Custom1 varchar(500),
	@Custom2 varchar(500),
	@Custom3 varchar(500),
	@Writedatetime datetime,
	@Moddatetime datetime,
	@Unitsplural varchar(50),
	@Expirerecurs varchar(50),
	@Trialrecurs varchar(50)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingItems] SET
	[ItemId] = @Itemid,
	[ItemType] = @Itemtype,
	[TiersetId] = @Tiersetid,
	[Name] = @Name,
	[Description] = @Description,
	[Units] = @Units,
	[Enabled] = @Enabled,
	[AccountingSku] = @Accountingsku,
	[Token] = @Token,
	[Custom1] = @Custom1,
	[Custom2] = @Custom2,
	[Custom3] = @Custom3,
	[WriteDateTime] = @Writedatetime,
	[ModDateTime] = @Moddatetime,
	[UnitsPlural] = @Unitsplural,
	[ExpireRecurs] = @Expirerecurs,
	[TrialRecurs] = @Trialrecurs
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO