SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryAdjustmentsGetByItemIDByDateRange] 
	@ID		int
	, @From	datetime = NULL
	, @To	datetime = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ADJUSTMENT_ID
		, ADJUSTMENT_ADJUSTMENT
		, ADJUSTMENT_CREATED
		, ADJUSTMENT_CREATEDBYID
		, ADJUSTMENT_DESCRIPTION			
		, ADJUSTMENT_INVENTORYITEMID
		, ADJUSTMENT_ROWVERSION
	FROM 
		[dbo].[InventoryAdjustments] 
	WHERE 
		(ADJUSTMENT_INVENTORYITEMID = @ID)
		AND (@From IS NULL OR ADJUSTMENT_CREATED >= @From)
		AND (@To IS NULL OR ADJUSTMENT_CREATED <= @To)
	ORDER BY 
		ADJUSTMENT_ID;
END
GO