SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProcessTypeGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT 
		PROCESSTYPE_ID
		, PROCESSTYPE_DESCRIPTION
	FROM 
		[dbo].[ProcessTypes]
	WHERE
		PROCESSTYPE_ID = @ID
END
GO