SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CustomPagesGetByClientIDs]
	@IDs varchar(100)
AS
BEGIN
	
	SET NOCOUNT ON;
    
	SELECT 
		c.CUSTOMPAGE_ID
		, c.CUSTOMPAGE_CLIENTID
		, c.CUSTOMPAGE_DESCRIPTION
		, c.CUSTOMPAGE_TITLE
		, c.CUSTOMPAGE_URL
		, c.CUSTOMPAGE_ROWVERSION
	FROM 
		[dbo].[CustomPages] AS c
		INNER JOIN IntegerListToTable(@IDs) AS i 
			ON c.CUSTOMPAGE_CLIENTID = i.number
	ORDER BY 
		c.CUSTOMPAGE_ID;
END
GO