SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptsGetByItemIDByDateRange] 
	@ID			int
	, @From		datetime = NULL
	, @To		datetime = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		INVENTORYRECEIPT_ID,			
		INVENTORYRECEIPT_CREATED,
		INVENTORYRECEIPT_CREATEDBYID,
		INVENTORYRECEIPT_DESCRIPTION,			
		INVENTORYRECEIPT_RECEIVED,
		INVENTORYRECEIPT_RECEIVEDBY,		
		INVENTORYRECEIPT_SHIPCOMPANY,
		INVENTORYRECEIPT_SUPPLIERCOMPANY,			
		INVENTORYRECEIPT_ROWVERSION
	FROM 
		[dbo].[InventoryReceipts]
    INNER JOIN dbo.InventoryReceiptItems iri ON iri.INVENTORYRECEIPTITEM_RECEIPTID = INVENTORYRECEIPT_ID
	WHERE 
		(INVENTORYRECEIPTITEM_ITEMID = @ID)
		AND (@From IS NULL OR INVENTORYRECEIPT_RECEIVED >= @From)
		AND (@To IS NULL OR INVENTORYRECEIPT_RECEIVED <= @To)
	ORDER BY
		INVENTORYRECEIPT_ID;

END
GO