SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RelationshipGetByID] 
	@ID int
AS
BEGIN
		
    SET NOCOUNT ON;

	SELECT
		RELATIONSHIP_ID
		, RELATIONSHIP_CLIENTID
		, RELATIONSHIP_USERID
		, RELATIONSHIP_ROWVERSION
	FROM 
		Relationships 
	WHERE 
		RELATIONSHIP_ID = @ID;
END
GO