SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingChargeOverRawLogsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverRawLogsGetAll]
-- Date Generated: Tuesday, May 2, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverRawLogsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[RawRequest],
	[Created],
	[CreatedById],
	[ChargeOverLogItemId]
FROM
	[dbo].[Billing_ChargeOverRawLog]

--endregion

GO