SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptItemUpdate]
	@ID int, 
  @ItemId INT,
	@ReceiptID int,
	@ContainerTypeID int,
  @Note     VARCHAR(MAX) = NULL,
	@NumContainers int,
	@PerContainer INT,
  @Version					timestamp
AS
BEGIN
	
	UPDATE 
		[dbo].[InventoryReceiptItems]
	SET
		INVENTORYRECEIPTITEM_RECEIPTID = @ReceiptID
		, INVENTORYRECEIPTITEM_CONTAINERTYPEID = @ContainerTypeID
		, INVENTORYRECEIPTITEM_CONTAINERS = @NumContainers
		, INVENTORYRECEIPTITEM_CONTAINERCOUNT = @PerContainer
    , INVENTORYRECEIPTITEM_ITEMID = @ItemId
    , INVENTORYRECEIPTITEM_NOTE = @Note
	OUTPUT
		inserted.INVENTORYRECEIPTITEM_ID AS ID, inserted.INVENTORYRECEIPTITEM_ROWVERSION AS [VERSION]
	WHERE
		INVENTORYRECEIPTITEM_ID = @ID
    AND INVENTORYRECEIPTITEM_ROWVERSION = @Version;	
END
GO