SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RegionGetByID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		REGION_ID
		, REGION_CODE
		, REGION_COUNTRYID
		, REGION_NAME
	FROM 
		[dbo].[Regions]	
	WHERE 
		REGION_ID = @ID;
END
GO