SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PostageUsageItemsGetByPackageIDByDateRange]
	@ID		int
	, @From datetime = NULL
	, @To	datetime = NULL
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT 
		ui.POSTAGEUSAGEITEM_DATETIME			
		, ui.POSTAGEUSAGEITEM_PACKAGEID
		, ui.POSTAGEUSAGEITEM_QUANTITY
		, ui.POSTAGEUSAGEITEM_RATE
		, ui.POSTAGEUSAGEITEM_ROWVERSION
	FROM 
		[dbo].[PostageUsageItems] AS ui		
	WHERE 
		(ui.POSTAGEUSAGEITEM_PACKAGEID = @ID)
		AND (@From IS NULL OR ui.POSTAGEUSAGEITEM_DATETIME <= @From)
		AND (@To IS NULL OR ui.POSTAGEUSAGEITEM_DATETIME >= @To)
	ORDER BY
		ui.POSTAGEUSAGEITEM_ID;
END
GO