SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingTiersGetByTiersetIdPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTiersGetByTiersetIdPaged]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------


CREATE PROCEDURE [dbo].[BillingTiersGetByTiersetIdPaged]
	@Id int
,
    @PageNumber INT = 1,
    @PageSize   INT = 10
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


;WITH pg AS
  (
    SELECT Id
      FROM [dbo].[BillingTier] main
      WHERE 	[TiersetId] = @Id

      ORDER BY Id
      OFFSET @PageSize * (@PageNumber - 1) ROWS
      FETCH NEXT @PageSize ROWS ONLY
  )
  SELECT 	
	[sub].[Id],
	[sub].[TierId],
	[sub].[TiersetId],
	[sub].[UnitFrom],
	[sub].[UnitTo],
	[sub].[Amount],
	[sub].[Rowversion]
  FROM [dbo].[BillingTier] sub
  WHERE EXISTS (SELECT 1 FROM pg WHERE pg.Id = sub.Id)
  ORDER BY sub.Id OPTION (RECOMPILE);

--endregion

GO