SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingItemDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingItemDeleteById]
-- Date Generated: Friday, June 16, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingItemDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[BillingItems]
WHERE
	[Id] = @Id

--endregion

GO