SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[AssignmentsGet] 
	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ASSIGNMENT_ID
		, ASSIGNMENT_JOBID
		, ASSIGNMENT_USERID
		, ASSIGNMENT_ROWVERSION
	FROM 
		[dbo].[Assignments]
	ORDER BY 
		ASSIGNMENT_ID;
END
GO