SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProjectGetByID]
	@ID Int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		PROJECT_ID
		, PROJECT_CLIENTID
		, PROJECT_PARENTID
		, PROJECT_NAME
		, PROJECT_ROWVERSION 
	FROM 
		[dbo].[Projects]
	WHERE 
		PROJECT_ID = @ID;
END
GO