SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProjectInventoryItemGetByID]
	@ID Int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		PROJECTINVENTORYITEM_ID
		, PROJECTINVENTORYITEM_ITEMID
		, PROJECTINVENTORYITEM_PROJECTID
	FROM 
		[dbo].[ProjectInventoryItems]
	WHERE 
		PROJECTINVENTORYITEM_ID = @ID;
END
GO