SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailSegmentsFindPaged2]	
	@ClientIDs	varchar(4000) = NULL
	, @JobIDs		varchar(4000) = NULL
	, @Name		nvarchar(200) = NULL
	, @From		datetime = NULL	
	, @To		datetime = NULL
	, @PageNumber	int = 1
	, @PageSize	int = 100
	
AS
BEGIN
    SET NOCOUNT ON;
		
    SELECT 
	   j. *
	   , m.*
	   , s.MAILSEGMENT_ID
	   , s.MAILSEGMENT_ACCESSIBILITYLEVELID		
	   , s.MAILSEGMENT_BILLINGSTATUS
	   , s.MAILSEGMENT_COMMINGLERID
	   , s.MAILSEGMENT_COMPLETEMAIL
	   , s.MAILSEGMENT_CREATED
	   , s.MAILSEGMENT_CREATEDBYID
	   , s.MAILSEGMENT_CRIDID
	   , s.MAILSEGMENT_DATADUE
	   , s.MAILSEGMENT_DESCRIPTION
	   , s.MAILSEGMENT_DESTINATIONANALYSIS
	   , s.MAILSEGMENT_DROPDATE
	   , s.MAILSEGMENT_ENTRYPOINT
	   , s.MAILSEGMENT_ESTQTY		
	   , s.MAILSEGMENT_FIRSTFINALIZESCANID
	   , s.MAILSEGMENT_FIRSTSCANID		
	   , s.MAILSEGMENT_COMMINGLERSEGMENTID	
	   , s.MAILSEGMENT_JOBID
	   , s.MAILSEGMENT_LASTFINALIZESCANID		
	   , s.MAILSEGMENT_LASTSCANID
	   , s.MAILSEGMENT_ISMAILANYWHERE
	   , s.MAILSEGMENT_MAILANYWHEREACCTNO
	   , s.MAILSEGMENT_MATERIALDUE		
	   , s.MAILSEGMENT_MATCHMAIL
	   , s.MAILSEGMENT_METERRATE
	   , s.MAILSEGMENT_NAME		
	   , s.MAILSEGMENT_NONPROFIT	
	   , s.MAILSEGMENT_OUTGOING		
	   , s.MAILSEGMENT_PIECEHEIGHT
	   , s.MAILSEGMENT_PIECELENGTH
	   , s.MAILSEGMENT_PIECETHICKNESS
	   , s.MAILSEGMENT_PIECETYPEID
	   , s.MAILSEGMENT_PIECEWEIGHT		
	   , s.MAILSEGMENT_POSTAGEAPPLIEDID
	   , s.MAILSEGMENT_POSTALCLASSID			
	   , s.MAILSEGMENT_PERMITID
	   , s.MAILSEGMENT_PRESORTED
	   , s.MAILSEGMENT_MAILSTREAMID
	   , s.MAILSEGMENT_SEGMENTTYPEID		
	   , s.MAILSEGMENT_SPECIALPREPARATION
	   , s.MAILSEGMENT_TARGETDATE
	   , s.MAILSEGMENT_TRACKINGTYPEID
	   , s.MAILSEGMENT_ROWVERSION	
    FROM
	   [job].[Jobs] AS j
	   INNER JOIN [dbo].[Jobs] AS m
		  ON j.JOB_ID = m.JOB_JOBID 
	   INNER JOIN [dbo].[MailSegments] AS s
		  ON m.JOB_ID = s.MAILSEGMENT_JOBID
    WHERE
	   (@ClientIDs IS NULL OR @ClientIDs = '' OR j.JOB_ID IN (
		  SELECT
				m.JOB_ID
		  FROM 
				[dbo].[Jobs] AS m
				INNER JOIN IntegerListToTable(@ClientIDs) AS i 
				    ON j.JOB_CLIENTID = i.number
	   ))
	   AND (@JobIDs IS NULL OR @JobIDs = '' OR j.JOB_ID IN (
		  SELECT
				JOB_ID
		  FROM 
				[dbo].[Jobs] AS j
				INNER JOIN IntegerListToTable(@JobIDs) AS i 
				    ON j.JOB_ID = i.number
	   ))
	   AND (@From IS NULL OR MAILSEGMENT_DROPDATE >= @From)			
	   AND (@To IS NULL OR MAILSEGMENT_DROPDATE <= @To)			
	   AND (@Name IS NULL OR @Name = '' OR j.JOB_NAME LIKE '%' + @Name + '%' OR m.JOB_NAME LIKE '%' + @Name + '%' OR MAILSEGMENT_NAME LIKE '%' + @Name + '%')
    ORDER BY MAILSEGMENT_ID
    OFFSET @PageSize * (@PageNumber - 1) ROWS
    FETCH NEXT @PageSize ROWS ONLY

END
GO