SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailLevelGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT 
		MAILLEVEL_ID
		, MAILLEVEL_DESCRIPTION
	FROM 
		[dbo].[MailLevels]
	WHERE
		MAILLEVEL_ID = @ID
END
GO