SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingInvoicesGetByClientId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingInvoicesGetByClientId]
-- Date Generated: Tuesday, April 18, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingInvoicesGetByClientIdByDate]
	@Id INT,
  @To DATETIME,
  @From DATETIME
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Amount],
	[ClientId],
	[Created],
	[CreatedById],
	[InvoiceBeginDate],
	[InvoiceEndDate],
	[Usage],
	[PaymentStatus],
  [ProviderInvoiceId],
  [RowVersion]
FROM
	[dbo].[BillingInvoice]
WHERE
	[ClientId] = @Id AND InvoiceBeginDate BETWEEN @To AND @From

--endregion
GO