SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LogItemsGetByDateRange] 
	@From	datetime
	, @To	datetime
AS
BEGIN
	
	SET NOCOUNT ON;

    SELECT
		LOG_ID
		, LOG_ACTION
		, LOG_DATETIME
		, LOG_IPADDRESS
		, LOG_IPCITYNAME
		, LOG_IPCOUNTRYCODE
		, LOG_IPLATITUDE
		, LOG_IPLONGITUDE
		, LOG_IPPOSTALCODE
		, LOG_IPREGIONCODE
		, LOG_MESSAGE
		, LOG_QUERY
		, LOG_SCREEN
		, LOG_SERVERNAME
		, LOG_SESSIONID
		, LOG_SEVERITY
		, LOG_URL
		, LOG_USERAGENT
		, LOG_USERID		
	FROM 
		[dbo].[Log] 
	WHERE 
		LOG_DATETIME BETWEEN @From AND @To;
END
GO