SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_RejectFlagsGetCountsByTransactionDateRange] (  
	@Effort			char(1)		= NULL
	, @DateFrom		datetime	= NULL
	, @DateTo		datetime	= NULL 
	, @GroupByDate	bit = NULL	
)
AS
BEGIN
	SET NOCOUNT ON;
			
	SELECT		 
		r.REJECTRECORD_FLAG AS FLAG
		, r.REJECTRECORD_REASON AS REASON
		, r.REJECTRECORD_EFFORT AS EFFORT
		, Count(*) AS [COUNT]
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_BATCHDATE END AS BATCHDATE
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_MAILDATE END AS MAILDATE
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_TRANSACTIONDATE END AS TRANSACTIONDATE				
	FROM	
		[dbo].[colpenn_RejectRecords] AS r
	WHERE 
		(@DateFrom IS NULL OR r.REJECTRECORD_TRANSACTIONDATE >= @DateFrom) 
		AND (@DateTo IS NULL OR r.REJECTRECORD_TRANSACTIONDATE <= @DateTo)
		AND (@Effort IS NULL OR @Effort = '' OR r.REJECTRECORD_EFFORT = @Effort)			
	GROUP BY			
		r.REJECTRECORD_FLAG
		, r.REJECTRECORD_REASON
		, r.REJECTRECORD_EFFORT
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_TRANSACTIONDATE END
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_MAILDATE END
		, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_BATCHDATE END;	
END
GO