SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WarehouseShelvesGet]

AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT		
		SHELF_ID
		, SHELF_BAYID
		, SHELF_VERTICALPOS
		, SHELF_ROWVERSION
	FROM 
		WarehouseShelves;
END
GO