SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[WizardTemporaryJsonsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[WizardTemporaryJsonsGetAll]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[WizardTemporaryJsonsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ClientId],
	[Json],
	[UserId]
FROM
	[dbo].[Wizard_TemporaryJson]

--endregion

GO