SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usps_MailSegmentsGetActiveScanningByUserID]
	@ID				int
	, @DateTime		datetime
	, @Threshold	int = 7
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT 
		seg.MAILSEGMENT_ID
		, seg.MAILSEGMENT_ACCESSIBILITYLEVELID		
		, seg.MAILSEGMENT_COMMINGLERID
		, seg.MAILSEGMENT_COMPLETEMAIL
		, seg.MAILSEGMENT_CREATED
		, seg.MAILSEGMENT_CREATEDBYID
		, seg.MAILSEGMENT_DATADUE
		, seg.MAILSEGMENT_DESCRIPTION
		, seg.MAILSEGMENT_DESTINATIONANALYSIS
		, seg.MAILSEGMENT_DROPDATE
		, seg.MAILSEGMENT_ENTRYPOINT
		, seg.MAILSEGMENT_ESTQTY		
		, seg.MAILSEGMENT_FIRSTFINALIZESCANID
		, seg.MAILSEGMENT_FIRSTSCANID		
		, seg.MAILSEGMENT_JOBID
		, seg.MAILSEGMENT_LASTFINALIZESCANID		
		, seg.MAILSEGMENT_LASTSCANID
		, seg.MAILSEGMENT_MATERIALDUE		
		, seg.MAILSEGMENT_MATCHMAIL
		, seg.MAILSEGMENT_METERRATE
		, seg.MAILSEGMENT_NAME		
		, seg.MAILSEGMENT_NONPROFIT	
		, seg.MAILSEGMENT_OUTGOING		
		, seg.MAILSEGMENT_PIECEHEIGHT
		, seg.MAILSEGMENT_PIECELENGTH
		, seg.MAILSEGMENT_PIECETHICKNESS
		, seg.MAILSEGMENT_PIECETYPEID
		, seg.MAILSEGMENT_PIECEWEIGHT		
		, seg.MAILSEGMENT_POSTAGEAPPLIEDID
		, seg.MAILSEGMENT_POSTALCLASSID			
		, seg.MAILSEGMENT_PERMITID
		, seg.MAILSEGMENT_PRESORTED
		, seg.MAILSEGMENT_MAILSTREAMID
		, seg.MAILSEGMENT_SEGMENTTYPEID		
		, seg.MAILSEGMENT_SPECIALPREPARATION
		, seg.MAILSEGMENT_TARGETDATE
		, seg.MAILSEGMENT_TRACKINGTYPEID
		, ( SELECT SUM(DISTINCT VERSION_TRIGGEREVENT) 
			FROM [usps].[MailSegmentEmailVersions] 
			WHERE VERSION_SEGMENTID = seg.MAILSEGMENT_ID
		  ) 
		  AS MAILSEGMENT_TRIGGEREVENTS				
		, seg.MAILSEGMENT_ROWVERSION
	FROM
		[dbo].[Jobs] AS m
		INNER JOIN [job].[Jobs] AS j
			ON m.JOB_JOBID = j.JOB_ID
		INNER JOIN [dbo].[Clients] AS c
			ON j.JOB_CLIENTID = c.CLIENT_ID
		INNER JOIN [dbo].[Relationships]
			ON RELATIONSHIP_USERID = @ID
				AND c.CLIENT_ID = RELATIONSHIP_CLIENTID
		INNER JOIN [dbo].[MailSegments] AS seg
			ON m.JOB_ID = seg.MAILSEGMENT_JOBID
		INNER JOIN [dbo].[MailPieceScans] AS s
			ON s.MAILPIECESCAN_ID = seg.MAILSEGMENT_LASTSCANID
	WHERE
		DATEDIFF(DAY, MAILPIECESCAN_DATETIME, GETUTCDATE()) < @Threshold
	ORDER BY
		s.MAILPIECESCAN_DATETIME DESC

END
GO