SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptItemsGetByItemIDByDateRange] 
	@ID			int
	, @From		datetime = NULL
	, @To		datetime = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		INVENTORYRECEIPTITEM_ID
		, INVENTORYRECEIPTITEM_CONTAINERCOUNT
		, INVENTORYRECEIPTITEM_CONTAINERS
		, INVENTORYRECEIPTITEM_CONTAINERTYPEID
    , INVENTORYRECEIPTITEM_ITEMID
    , INVENTORYRECEIPTITEM_NOTE
		, INVENTORYRECEIPTITEM_RECEIPTID
    ,INVENTORYRECEIPTITEM_ROWVERSION
	FROM 
		[dbo].[InventoryReceiptItems]
    INNER JOIN dbo.InventoryReceipts ir ON ir.INVENTORYRECEIPT_ID = INVENTORYRECEIPTITEM_RECEIPTID
	WHERE 
		(INVENTORYRECEIPTITEM_ITEMID = @ID)
		AND (@From IS NULL OR ir.INVENTORYRECEIPT_RECEIVED >= @From)
		AND (@To IS NULL OR ir.INVENTORYRECEIPT_RECEIVED <= @To)
	ORDER BY
		INVENTORYRECEIPT_ID;

END
GO