SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailSpamLogInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailSpamLogInsert]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailSpamLogInsert]
	@Messageid varchar(100),
	@Event varchar(50),
	@Recipient varchar(500),
	@Domain varchar(500),
	@Messageheaders varchar(4000),
	@Campaignid varchar(50),
	@Campaignname varchar(500),
	@Tag varchar(100),
	@Mailinglist varchar(500),
	@SendId int,
	
	@Timestamp varchar(50),
	@Token varchar(100),
	@Signature varchar(500)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[mailgun_SpamLog] (
	[MessageId],
	[Event],
	[Recipient],
	[Domain],
	[MessageHeaders],
	[CampaignId],
	[CampaignName],
	[Tag],
	[MailingList],
	[SendId],
	
	[TimeStamp],
	[Token],
	[Signature]
) 
OUTPUT		
		inserted.Id AS [ID], NULL AS [VERSION]
VALUES (
	@Messageid,
	@Event,
	@Recipient,
	@Domain,
	@Messageheaders,
	@Campaignid,
	@Campaignname,
	@Tag,
	@Mailinglist,
	@SendId,
	
	@Timestamp,
	@Token,
	@Signature
)

--endregion
GO