SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingChargeOverRawLogUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverRawLogUpdate]
-- Date Generated: Tuesday, May 2, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverRawLogUpdate]
	@Id int,
	@Rawrequest varchar(max),
	@Created datetime,
	@Createdbyid int,
	@Chargeoverlogitemid int
    
AS

SET NOCOUNT ON

UPDATE [dbo].[Billing_ChargeOverRawLog] SET
	[RawRequest] = @Rawrequest,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[ChargeOverLogItemId] = @Chargeoverlogitemid
    OUTPUT inserted.Id AS [ID]
WHERE
	[Id] = @Id

--endregion

GO