SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ExceptionItemsGet]
	
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		EXCEPTION_ID
		, EXCEPTION_DATA
		, EXCEPTION_DATETIME
		, EXCEPTION_EXCEPTIONSTACK
		, EXCEPTION_HOSTNAME
		, EXCEPTION_IPADDRESS
		, EXCEPTION_MESSAGE
		, EXCEPTION_QUERY
		, EXCEPTION_RESPONSESTATUS
		, EXCEPTION_SERVERNAME
		, EXCEPTION_SOURCE
		, EXCEPTION_TARGET
		, EXCEPTION_TYPE
		, EXCEPTION_URL
		, EXCEPTION_USERAGENT
		, EXCEPTION_USERID
	FROM
		Exceptions
	ORDER BY
		EXCEPTION_ID;
END
GO