SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[EstimateServiceItemGetByID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		ESTIMATESERVICE_ID
		, ESTIMATESERVICE_DESCRIPTION
		, ESTIMATESERVICE_ESTIMATEID
		, ESTIMATESERVICE_EXTENDEDPRICE
		, ESTIMATESERVICE_QUANTITY
		, ESTIMATESERVICE_SERVICENAME
		, ESTIMATESERVICE_SERVICETYPEID
		, ESTIMATESERVICE_UNITPRICE
		, ESTIMATESERVICE_ROWVERSION
	FROM
		[dbo].[EstimateServiceItems]
	WHERE 
		(ESTIMATESERVICE_ID = @ID);	
END
GO