SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CustomPageGetByURL]
	@Url nvarchar(2000)
AS
BEGIN
	
	SET NOCOUNT ON;
    
	SELECT 
		c.CUSTOMPAGE_ID
		, c.CUSTOMPAGE_CLIENTID
		, c.CUSTOMPAGE_DESCRIPTION
		, c.CUSTOMPAGE_TITLE
		, c.CUSTOMPAGE_URL
		, c.CUSTOMPAGE_ROWVERSION
	FROM 
		[dbo].[CustomPages] AS c
	WHERE
		c.CUSTOMPAGE_URL = @Url
	ORDER BY 
		c.CUSTOMPAGE_ID;
END
GO