SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptsGetByClientID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		DISTINCT INVENTORYRECEIPT_ID,			
			INVENTORYRECEIPT_CREATED,
			INVENTORYRECEIPT_CREATEDBYID,
			INVENTORYRECEIPT_DESCRIPTION,			
			INVENTORYRECEIPT_RECEIVED,
			INVENTORYRECEIPT_RECEIVEDBY,		
			INVENTORYRECEIPT_SHIPCOMPANY,
			INVENTORYRECEIPT_SUPPLIERCOMPANY,			
			INVENTORYRECEIPT_ROWVERSION
	FROM 
		[dbo].[InventoryReceipts] AS r
    INNER JOIN dbo.InventoryReceiptItems iri ON iri.INVENTORYRECEIPTITEM_RECEIPTID = INVENTORYRECEIPT_ID
		INNER JOIN [dbo].[InventoryItems] AS i
			ON iri.INVENTORYRECEIPTITEM_ITEMID = i.[ID]
	WHERE 
		i.[ClientID] = @ID 
	
END
GO