SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailSegmentGetPieceCountFromSequenceRange]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	    
	;WITH CTE AS
	(
		SELECT TOP 1
			(SEQUENCE_ENDVALUE - SEQUENCE_STARTVALUE) + 1 AS [COUNT]
		FROM
			[usps].[MailSegmentSequences] AS seq
		WHERE
			SEQUENCE_SEGMENTID = @ID
		ORDER BY SEQUENCE_ID DESC
	)
	SELECT
		COALESCE(SUM(CTE.COUNT), 0)
	FROM
		CTE;
END
GO