SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptDeleteByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	DELETE 
		[dbo].[InventoryReceipts]
	WHERE
		INVENTORYRECEIPT_ID = @ID

	IF @@ROWCOUNT > 0 
		RETURN 0
	ELSE
		RETURN 1
END
GO