SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingInvoiceInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingInvoiceInsert]
-- Date Generated: Monday, April 24, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingInvoiceInsert]
	@Amount decimal(18, 4),
	@Clientid int,
	@Created datetime,
	@Createdbyid int,
	@Invoicebegindate datetime,
	@Invoiceenddate datetime,
	@Usage int,
	@Paymentstatus int,
	@Providerinvoiceid varchar(50)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingInvoice] (
	[Amount],
	[ClientId],
	[Created],
	[CreatedById],
	[InvoiceBeginDate],
	[InvoiceEndDate],
	[Usage],
	[PaymentStatus],
	[ProviderInvoiceId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Amount,
	@Clientid,
	@Created,
	@Createdbyid,
	@Invoicebegindate,
	@Invoiceenddate,
	@Usage,
	@Paymentstatus,
	@Providerinvoiceid
)

--endregion

GO