SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptItemsGetByClientID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		INVENTORYRECEIPTITEM_ID
		, INVENTORYRECEIPTITEM_CONTAINERCOUNT
		, INVENTORYRECEIPTITEM_CONTAINERS
		, INVENTORYRECEIPTITEM_CONTAINERTYPEID
    , INVENTORYRECEIPTITEM_ITEMID
    , INVENTORYRECEIPTITEM_NOTE
		, INVENTORYRECEIPTITEM_RECEIPTID
    ,INVENTORYRECEIPTITEM_ROWVERSION
	FROM 
		[dbo].[InventoryReceiptItems] AS iri
		INNER JOIN [dbo].[InventoryItems] AS i
			ON iri.INVENTORYRECEIPTITEM_ITEMID = i.[ID]
	WHERE 
		i.[ClientID] = @ID 
	
END
GO