SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PostageTypesGet]
	
AS
BEGIN
	
	SET NOCOUNT ON;
	
	SELECT
		POSTAGETYPE_ID
		, POSTAGETYPE_ATTRIBUTES
		, POSTAGETYPE_NAME
	FROM 
		[dbo].[PostageTypes]
	ORDER BY
		POSTAGETYPE_ID;
END
GO