SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ClientsGetPaged] 
	@Page			int,
	@RowsPerPage	int
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @StartRow int,
			@EndRow int

	SET @StartRow = ((@Page - 1) * @RowsPerPage) + 1;
	SET @EndRow = @StartRow + @RowsPerPage - 1;

	SELECT
		CLIENT_ID
		, CLIENT_ADDRESS1
		, CLIENT_ADDRESS2
		, CLIENT_BRANDED
		, CLIENT_CITY
		, CLIENT_CONTACT
		, CLIENT_CREATED
		, CLIENT_CREATEDBYID
		, CLIENT_EMAIL
		, CLIENT_FAVICON
		, CLIENT_FAX
		, CLIENT_INTERNAL
		, CLIENT_LEGALNAME
		, CLIENT_NAME
		, CLIENT_NONPROFITAUTH
		, CLIENT_PARENTID
		, CLIENT_PHONE
		, CLIENT_POSTALCODE
		, CLIENT_REGION
		, CLIENT_SHORTNAME
		, CLIENT_STYLESHEET
		, CLIENT_SUBDOMAIN
		, CLIENT_URL
    , CLIENT_TYPE
		, CLIENT_VENDOR
		, CLIENT_ROWVERSION
	FROM 
	(
		SELECT ROW_NUMBER() OVER (ORDER BY CLIENT_ID) AS ResultNum, 
			CLIENT_ID
			, CLIENT_ADDRESS1
			, CLIENT_ADDRESS2
			, CLIENT_BRANDED
			, CLIENT_CITY
			, CLIENT_CONTACT
			, CLIENT_CREATED
			, CLIENT_CREATEDBYID
			, CLIENT_EMAIL
			, CLIENT_FAVICON
			, CLIENT_FAX
			, CLIENT_INTERNAL
			, CLIENT_LEGALNAME
			, CLIENT_NAME
			, CLIENT_NONPROFITAUTH
			, CLIENT_PARENTID
			, CLIENT_PHONE
			, CLIENT_POSTALCODE
			, CLIENT_REGION
      , CLIENT_TYPE
			, CLIENT_SHORTNAME
			, CLIENT_STYLESHEET
			, CLIENT_SUBDOMAIN
			, CLIENT_URL
			, CLIENT_VENDOR
			, CLIENT_ROWVERSION
		FROM [dbo].[Clients]
	) AS NumberResults
	WHERE 
	ResultNum BETWEEN @StartRow AND @EndRow;
	
END
GO