SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingCategoryCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingCategoryCreate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingCategoryCreate]
	@Categoryid int,
	@Itemid int,
	@Name varchar(50)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingCategories] (
	[CategoryId],
	[ItemId],
	[Name]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Categoryid,
	@Itemid,
	@Name
)

--endregion

GO