SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[ClientsGetCountByParentID]
	@ID	int = NULL
AS
BEGIN
	
	SET NOCOUNT ON;
	
	SELECT 
		COUNT(CLIENT_ID) 
	FROM 
		[dbo].[Clients]
	WHERE
		(@ID IS NULL AND CLIENT_PARENTID IS NULL)
		OR (CLIENT_PARENTID = @ID);
END
GO