SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[CommentThreadGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[CommentThreadGetById]
-- Date Generated: Tuesday, May 23, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[CommentThreadGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id]
FROM
	[dbo].[CommentThreads]
WHERE
	[Id] = @Id

--endregion

GO