SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingTiersetsGetByItemIdByModDatetime]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTiersetsGetByItemIdByModDatetime]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------


CREATE PROCEDURE [dbo].[BillingTiersetsGetByItemIdByModDatetime]
    @To DATETIME,
    @From DATETIME,
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[TiersetId],
	[CurrencyId],
	[Setup],
	[Base],
	[Percent],
	[Paycycle],
	[PriceModel],
	[WriteDatetime],
	[ModDatetime],
	[CurrencySymbol],
	[CurrencyIso4217],
	[ItemId],
	[SetupFormatted],
	[BaseFormatted],
	[PercentFormatted],
	[PriceModelDesc],
	[RowVersion]
FROM
	[dbo].[BillingTiersets]
WHERE
    ModDatetime  BETWEEN @From AND @To AND 	[ItemId] = @Id


--endregion

GO