SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingSubscriptionUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingSubscriptionUpdate]
-- Date Generated: Monday, June 26, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingSubscriptionUpdate]
@Version				timestamp,
	@Id int,
	@Allotted int,
	@Clientid int,
	@Created datetime,
	@Createdbyid int,
	@Cyclestartdate datetime,
	@Lastinvoiceddate datetime,
	@Lastupdated datetime,
	@Minimumqty int,
	@Minimumrate decimal(18, 6),
	@Monthspercycle int,
	@Overagerate decimal(18, 6),
	@Paycycle int,
	@Productid int,
	@Productprice decimal(18, 4),
	@Providerid int,
	@Remaining int,
	@Seats int,
	@Seatitemid int,
	@Seatprice decimal(18, 4),
	@Usagealertssent int,
	@Usagealertthreshold int,
	@Usageid int,
	@Users int
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingSubscriptions] SET
	[Allotted] = @Allotted,
	[ClientId] = @Clientid,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[CycleStartDate] = @Cyclestartdate,
	[LastInvoicedDate] = @Lastinvoiceddate,
	[LastUpdated] = @Lastupdated,
	[MinimumQty] = @Minimumqty,
	[MinimumRate] = @Minimumrate,
	[MonthsPerCycle] = @Monthspercycle,
	[OverageRate] = @Overagerate,
	[PayCycle] = @Paycycle,
	[ProductId] = @Productid,
	[ProductPrice] = @Productprice,
	[ProviderId] = @Providerid,
	[Remaining] = @Remaining,
	[Seats] = @Seats,
	[SeatItemId] = @Seatitemid,
	[SeatPrice] = @Seatprice,
	[UsageAlertsSent] = @Usagealertssent,
	[UsageAlertThreshold] = @Usagealertthreshold,
	[UsageId] = @Usageid,
	[Users] = @Users
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO