SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SystemAlertsGetByDate]
	@DateTime	datetime
AS
BEGIN	
	
	SET NOCOUNT ON;
	
	SELECT
		ALERT_ID
		, ALERT_DISPLAYEND
		, ALERT_DISPLAYSTART
		, ALERT_MESSAGE
		, ALERT_POSTED
		, ALERT_POSTEDBYID
		, ALERT_TITLE		
	FROM 
		[dbo].[SystemAlerts] 
	WHERE 
		(ALERT_DISPLAYSTART <= @DateTime) AND (ALERT_DISPLAYEND >= @DateTime)
	ORDER BY
		ALERT_ID; 	
END
GO