SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_RejectRecordsGetPrintKeyCounts]
	@TransactionDate	bit = NULL	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		COUNT(*) AS PRINTKEY_COUNT
		, REJECTRECORD_PRINTKEY	AS PRINTKEY	
		, NULL AS PRINTKEY_EFFORT
		, CASE @TransactionDate WHEN 1 THEN REJECTRECORD_TRANSACTIONDATE END AS PRINTKEY_TRANSACTIONDATE		
	FROM
		[dbo].[colpenn_RejectRecords]
	GROUP BY
		REJECTRECORD_PRINTKEY
		, CASE @TransactionDate WHEN 1 THEN REJECTRECORD_TRANSACTIONDATE END		
	;
END
GO