SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingInvoicesGetByCreatedById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingInvoicesGetByCreatedById]
-- Date Generated: Monday, April 24, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingInvoicesGetByCreatedById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Amount],
	[ClientId],
	[Created],
	[CreatedById],
	[InvoiceBeginDate],
	[InvoiceEndDate],
	[Usage],
	[PaymentStatus],
	[ProviderInvoiceId],
	[Rowversion]
FROM
	[dbo].[BillingInvoice]
WHERE
	[CreatedById] = @Id

--endregion

GO