SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptGetLastByItemID] 
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT TOP 1
		INVENTORYRECEIPT_ID,			
			INVENTORYRECEIPT_CREATED,
			INVENTORYRECEIPT_CREATEDBYID
			INVENTORYRECEIPT_DESCRIPTION,			
			INVENTORYRECEIPT_RECEIVED,
			INVENTORYRECEIPT_RECEIVEDBY,		
			INVENTORYRECEIPT_SHIPCOMPANY,
			INVENTORYRECEIPT_SUPPLIERCOMPANY,			
			INVENTORYRECEIPT_ROWVERSION
    FROM
		[dbo].[InventoryReceipts]
      INNER JOIN dbo.InventoryReceiptItems iri ON iri.INVENTORYRECEIPTITEM_RECEIPTID = INVENTORYRECEIPT_ID
    WHERE 
		INVENTORYRECEIPTITEM_ITEMID = @ID
    ORDER BY 
		INVENTORYRECEIPT_RECEIVED DESC;
END
GO