SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RelationshipsGet] 	
AS
BEGIN		
    SET NOCOUNT ON;

	SELECT
		RELATIONSHIP_ID
		, RELATIONSHIP_CLIENTID
		, RELATIONSHIP_USERID
		, RELATIONSHIP_ROWVERSION
	FROM 
		Relationships 
	ORDER BY 
		RELATIONSHIP_ID;
END
GO