SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RelationshipsGetByClientID] 
	@ID int
AS
BEGIN
		
    SET NOCOUNT ON;

	SELECT 
		RELATIONSHIP_ID
		, RELATIONSHIP_CLIENTID
		, RELATIONSHIP_USERID
		, RELATIONSHIP_ROWVERSION 
	FROM 
		Relationships 
	WHERE 
		RELATIONSHIP_CLIENTID = @ID
	ORDER BY 
		RELATIONSHIP_ID;
END
GO