SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[CommentDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[CommentDeleteById]
-- Date Generated: Tuesday, May 23, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[CommentDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Comments]
WHERE
	[Id] = @Id

--endregion

GO