SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_CoverageCodesGetCountsCountByMailDateRange] (  
  @Effort		char(1)		= NULL
  , @DateFrom	datetime	= NULL
  , @DateTo		datetime	= NULL 
  , @GroupByDate	bit = NULL 
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT COUNT(*) FROM
	(
	SELECT 
		COUNT(t.COVERAGECODE) AS x
	FROM 
	(
		SELECT 
			'1' AS RECORDTYPE
			, m.MAILRECORD_COVERAGECODE AS COVERAGECODE
			, m.MAILRECORD_EFFORT AS EFFORT
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_BATCHDATE END AS BATCHDATE
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_MAILDATE END AS MAILDATE
			, CASE @GroupByDate WHEN 1 THEN m.MAILRECORD_TRANSACTIONDATE END AS TRANSACTIONDATE
        FROM 
			colpenn_MailRecords AS m
        WHERE 
			(@DateFrom IS NULL OR m.MAILRECORD_MAILDATE >= @DateFrom) 
			AND (@DateTo IS NULL OR m.MAILRECORD_MAILDATE <= @DateTo)
			AND (@Effort IS NULL OR @Effort = '' OR m.MAILRECORD_EFFORT = @Effort)
         
         UNION ALL
         
		SELECT 
			'2' AS RECORDTYPE
			, r.REJECTRECORD_COVERAGECODE AS COVERAGECODE
			, r.REJECTRECORD_EFFORT AS EFFORT
			, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_BATCHDATE END AS BATCHDATE
			, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_MAILDATE END AS MAILDATE
			, CASE @GroupByDate WHEN 1 THEN r.REJECTRECORD_TRANSACTIONDATE END AS TRANSACTIONDATE
        FROM 
			colpenn_RejectRecords AS r
         WHERE 
			(@DateFrom IS NULL OR r.REJECTRECORD_MAILDATE >= @DateFrom) 
			AND (@DateTo IS NULL OR r.REJECTRECORD_MAILDATE <= @DateTo)
			AND (@Effort IS NULL OR @Effort = '' OR r.REJECTRECORD_EFFORT = @Effort)
        ) t
	GROUP BY
			COVERAGECODE,
			EFFORT,
			CASE @GroupByDate WHEN 1 THEN t.TRANSACTIONDATE END,
			CASE @GroupByDate WHEN 1 THEN t.MAILDATE END,
			CASE @GroupByDate WHEN 1 THEN t.BATCHDATE END
	) x
;
	
END
GO