SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ComminglerClientsGetByClientId]
	@ID int
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT 
		COMMINGLERCLIENT_ID
		, COMMINGLERCLIENT_CLIENTID
		, COMMINGLERCLIENT_COMMINGLERID
		, COMMINGLERCLIENT_NONPROFITRATE
		, COMMINGLERCLIENT_STANDARDRATE
		, COMMINGLERCLIENT_VALUE
		, COMMINGLERCLIENT_ROWVERSION
	FROM 
		[dbo].[ComminglerClients]
	WHERE
		COMMINGLERCLIENT_CLIENTID = @ID;
END
GO