SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[LogItemGetUserLastLoginByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

    DECLARE @LogItemID int;
		
    SET @LogItemID = (SELECT TOP 1 LOG_ID FROM [dbo].[Log]
    WHERE
		(LOG_ACTION = 1) AND
		(LOG_USERID = @ID)
	ORDER BY LOG_DATETIME DESC);
	
	SELECT
		LOG_ID
		, LOG_ACTION		
		, LOG_DATETIME
		, LOG_IPADDRESS
		, LOG_IPCITYNAME
		, LOG_IPCOUNTRYCODE
		, LOG_IPLATITUDE
		, LOG_IPLONGITUDE
		, LOG_IPPOSTALCODE
		, LOG_IPREGIONCODE
		, LOG_MESSAGE
		, LOG_QUERY
		, LOG_SCREEN
		, LOG_SERVERNAME
		, LOG_SESSIONID
		, LOG_SEVERITY
		, LOG_URL
		, LOG_USERAGENT
		, LOG_USERID		
	FROM [dbo].[Log]
	WHERE
		LOG_ID = @LogItemID;
END
GO