SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ClientServiceDiscountsGetByClientID] 
	@ID int
AS
BEGIN

	SET NOCOUNT ON;

	SELECT 
		DISCOUNT_ID
		, DISCOUNT_CLIENTID
		, DISCOUNT_PRICEMINIMUM
		, DISCOUNT_PERCENT
		, DISCOUNT_SERVICEID		
		, DISCOUNT_UNITPRICE
		, DISCOUNT_ROWVERSION
	FROM 
		[dbo].[ClientServiceDiscounts]
	WHERE 
		DISCOUNT_CLIENTID = @ID
	ORDER BY 
		DISCOUNT_ID;
END
GO