SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingServiceLogGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingServiceLogGetById]
-- Date Generated: Thursday, April 13, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingServiceLogGetLast]
	
  AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT TOP(1)
	[Id],
	[Created],
	[CreatedById],
	[ProcessStartTime],
	[ProcessEndTime],
	[ProcessStatus],
	[SegmentsProcessed],
	[RowVersion]
FROM
	[dbo].[BillingServiceLog]
  WHERE ProcessStatus = 2
ORDER BY ProcessEndTime DESC

--endregion
GO