SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PieceTypeGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		PIECETYPE_ID,
		PIECETYPE_NAME,
		PIECETYPE_ROWVERSION
	FROM 
		PieceTypes 
	WHERE 
		PIECETYPE_ID = @ID;
END
GO