SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[GeoCongressionalDistrictGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   pmurphy using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[GeoCongressionalDistrictGetById]
-- Date Generated: Thursday, March 10, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GeoCongressionalDistrictGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[FipsId],
	[CongressionalWkt],
	[CongressionalWkb],
	[StateFipsId],
	[GeoId],
	[Name],
	[Lsad],
	[SessionCode],
	[mtfcc],
	[FunctionalStatus],
	[LandArea],
	[WaterArea],
	[InteriorLat],
	[InteriorLon]
FROM
	[dbo].[geo_CongressionalDistricts]
WHERE
	[Id] = @Id

--endregion

GO