SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ClientsGetAutoCompleteWriteAccess]
	@ID				int 
	, @Substring	nvarchar(255)
AS
BEGIN
			
	SET NOCOUNT ON;
	
DECLARE @CLIENT_ID int;
DECLARE @CLIENT_TYPE INT;

	SELECT @CLIENT_ID = USER_CLIENT_ID FROM dbo.Users WHERE USER_USERID = @ID;
  SELECT @CLIENT_TYPE = CLIENT_TYPE FROM dbo.Clients WHERE CLIENT_ID = @CLIENT_ID;

IF @CLIENT_TYPE = 16 OR @CLIENT_TYPE IS NULL
  BEGIN
	SELECT 
		CLIENT_ID
			, CLIENT_ADDRESS1
			, CLIENT_ADDRESS2
			, CLIENT_BRANDED
			, CLIENT_CITY
			, CLIENT_CONTACT
			, CLIENT_CREATED
			, CLIENT_CREATEDBYID
			, CLIENT_EMAIL
			, CLIENT_FAVICON
			, CLIENT_FAX
			, CLIENT_INTERNAL
			, CLIENT_LEGALNAME
			, CLIENT_NAME
			--, CLIENT_NONPROFITAUTH
			, CLIENT_PARENTID
			, CLIENT_PHONE
			, CLIENT_POSTALCODE
			, CLIENT_REGION
			, CLIENT_SHORTNAME
			, CLIENT_STYLESHEET
			, CLIENT_SUBDOMAIN
      , CLIENT_TYPE
			, CLIENT_URL
			, CLIENT_VENDOR
			, CLIENT_ROWVERSION
	FROM 
		[dbo].[Clients] AS c
		INNER JOIN [dbo].[Relationships] AS r
			ON c.CLIENT_ID = r.RELATIONSHIP_CLIENTID
				AND r.RELATIONSHIP_USERID = @ID
	WHERE
		CLIENT_NAME LIKE '%' + @Substring + '%'
		OR CLIENT_SHORTNAME LIKE '%' + @Substring + '%'
    END
ELSE
  BEGIN
  	SELECT DISTINCT
		CLIENT_ID
			, CLIENT_ADDRESS1
			, CLIENT_ADDRESS2
			, CLIENT_BRANDED
			, CLIENT_CITY
			, CLIENT_CONTACT
			, CLIENT_CREATED
			, CLIENT_CREATEDBYID
			, CLIENT_EMAIL
			, CLIENT_FAVICON
			, CLIENT_FAX
			, CLIENT_INTERNAL
			, CLIENT_LEGALNAME
			, CLIENT_NAME
			--, CLIENT_NONPROFITAUTH
			, CLIENT_PARENTID
			, CLIENT_PHONE
			, CLIENT_POSTALCODE
			, CLIENT_REGION
			, CLIENT_SHORTNAME
			, CLIENT_STYLESHEET
			, CLIENT_SUBDOMAIN
      , CLIENT_TYPE
			, CLIENT_URL
			, CLIENT_VENDOR
			, CLIENT_ROWVERSION
      
	FROM 
		[dbo].[Clients] AS c
		INNER JOIN dbo.ClientRelationships cr ON (cr.ParentClientId = c.CLIENT_ID OR cr.PartnerClientId = c.CLIENT_ID)
			
	WHERE
      ((cr.ParentClientId = @CLIENT_ID AND cr.RelationshipType = 2) OR (cr.ParentClientId = @CLIENT_ID AND cr.RelationshipType = 8) OR (cr.PartnerClientId = @CLIENT_ID AND cr.RelationshipType = 8)) AND cr.RelationshipState = 1 AND
		(CLIENT_NAME LIKE '%' + @Substring + '%'
		OR CLIENT_SHORTNAME LIKE '%' + @Substring + '%')
  END
END 
GO