SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[StampTypeGetByID]
	@ID int
AS
BEGIN
	
	SET NOCOUNT ON;
		
	SELECT
		STAMPTYPE_ID
		, STAMPTYPE_NAME
		, STAMPTYPE_ROWVERSION
	FROM 
		[dbo].[StampTypes]
	WHERE 
		STAMPTYPE_ID = @ID;
END
GO