SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptsGetByItemID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT
		INVENTORYRECEIPT_ID,			
			INVENTORYRECEIPT_CREATED,
			INVENTORYRECEIPT_CREATEDBYID,
			INVENTORYRECEIPT_DESCRIPTION,					
			INVENTORYRECEIPT_RECEIVED,
			INVENTORYRECEIPT_RECEIVEDBY,		
			INVENTORYRECEIPT_SHIPCOMPANY,
			INVENTORYRECEIPT_SUPPLIERCOMPANY,			
			INVENTORYRECEIPT_ROWVERSION
	FROM 
		[dbo].[InventoryReceipts]
    INNER JOIN dbo.InventoryReceiptItems iri ON iri.INVENTORYRECEIPTITEM_RECEIPTID = INVENTORYRECEIPT_ID
	WHERE 
		INVENTORYRECEIPTITEM_ITEMID = @ID;	
END
GO