SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_PsiSlipsGet]

AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		PSISLIP_ID
		, PSISLIP_CONTENTTYPE
		, PSISLIP_DATA
		, PSISLIP_DATE
		, PSISLIP_FILENAME
		, PSISLIP_UPLOADED
	FROM
		[dbo].[colpenn_PsiSlips]		
	ORDER BY
		PSISLIP_ID;
END
GO