SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[WizardTemporaryJsonsGetByUserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[WizardTemporaryJsonsGetByUserId]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[WizardTemporaryJsonsGetByUserIdByClientId]
	@UserId INT,
  @ClientId Int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ClientId],
	[Json],
	[UserId]
FROM
	[dbo].[Wizard_TemporaryJson]
WHERE
	[UserId] = @UserId AND [ClientId] = @ClientId

--endregion
GO