SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[ClientInvitationDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ClientInvitationDeleteById]
-- Date Generated: Wednesday, May 17, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ClientInvitationDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[ClientInvitation]
WHERE
	[Id] = @Id

--endregion

GO