SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DistrictGetByCode]
	@Code char(3)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		DISTRICT_ID
		, DISTRICT_CODE
		, DISTRICT_NAME
	FROM
		[dbo].[Districts]
	WHERE
		DISTRICT_CODE = @Code;
END
GO