SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[_MailPieceGetByTrackingCode]
	@TrackingCode			char(20)
	, @ExpirationThreshold	int	= NULL
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT TOP 1
		MAILPIECE_ID		
		, MAILPIECE_ADDRESS1
		, MAILPIECE_ADDRESS2
		, MAILPIECE_ADDRESS3		
		, MAILPIECE_CITY
		, MAILPIECE_COMPANY
		, MAILPIECE_CRRT
		, MAILPIECE_DELIVERYDATE			
		, MAILPIECE_FINALIZESCANID
		, MAILPIECE_FIRSTNAME
		, MAILPIECE_FIRSTSCANID
		, MAILPIECE_FORWARDSCANID
		, MAILPIECE_GROUPID
		, MAILPIECE_INDIVIDUALID
		, MAILPIECE_LASTNAME
		, MAILPIECE_LASTSCANID
		, MAILPIECE_SEGMENTID
		, MAILPIECE_RETURNSCANID
		, MAILPIECE_ROUTINGCODE
		, MAILPIECE_SCFID
		, MAILPIECE_STATE
		, MAILPIECE_TITLE
		, MAILPIECE_TRACKINGCODE
		, MAILPIECE_ZIPCODE
		, MAILPIECE_ZIPCODEEXT		
	FROM			
		[dbo].[MailPieces] As p
		INNER JOIN [dbo].[MailSegments] AS s
			ON p.MAILPIECE_SEGMENTID = p.MAILPIECE_SEGMENTID
	WHERE
		MAILPIECE_TRACKINGCODE = @TrackingCode
		AND 
		(
			@ExpirationThreshold IS NULL
			OR @ExpirationThreshold >= DATEDIFF(DAY, s.MAILSEGMENT_DROPDATE, GETUTCDATE())
		)
	ORDER BY
		MAILPIECE_ID DESC;
	
END
GO