SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingItemCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingItemCreate]
-- Date Generated: Friday, June 16, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingItemCreate]
	@Itemid int,
	@Itemtype varchar(500),
	@Tiersetid int,
	@Name varchar(500),
	@Description varchar(500),
	@Units varchar(50),
	@Enabled bit,
	@Accountingsku varchar(500),
	@Token varchar(50),
	@Custom1 varchar(500),
	@Custom2 varchar(500),
	@Custom3 varchar(500),
	@Writedatetime datetime,
	@Moddatetime datetime,
	@Unitsplural varchar(50),
	@Expirerecurs varchar(50),
	@Trialrecurs varchar(50)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingItems] (
	[ItemId],
	[ItemType],
	[TiersetId],
	[Name],
	[Description],
	[Units],
	[Enabled],
	[AccountingSku],
	[Token],
	[Custom1],
	[Custom2],
	[Custom3],
	[WriteDateTime],
	[ModDateTime],
	[UnitsPlural],
	[ExpireRecurs],
	[TrialRecurs]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Itemid,
	@Itemtype,
	@Tiersetid,
	@Name,
	@Description,
	@Units,
	@Enabled,
	@Accountingsku,
	@Token,
	@Custom1,
	@Custom2,
	@Custom3,
	@Writedatetime,
	@Moddatetime,
	@Unitsplural,
	@Expirerecurs,
	@Trialrecurs
)

--endregion

GO