SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingServiceLogGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingServiceLogGetById]
-- Date Generated: Wednesday, May 31, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingServiceLogGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Created],
	[CreatedById],
	[Message],
	[ProcessStartTime],
	[ProcessEndTime],
	[ProcessStatus],
	[SegmentsProcessed],
	[StackTrace],
	[RowVersion]
FROM
	[dbo].[BillingServiceLog]
WHERE
	[Id] = @Id

--endregion

GO