SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailSegmentsGetUnbilled]
	
AS
BEGIN
	SET NOCOUNT ON;

UPDATE ms SET ms.MAILSEGMENT_BILLINGSTATUS = 1 
  FROM dbo.MailSegments ms 
  INNER JOIN dbo.MailPieces mp ON mp.MAILPIECE_SEGMENTID = ms.MAILSEGMENT_ID
  INNER JOIN dbo.MailPieceScans mps ON mps.MAILPIECESCAN_MAILPIECEID = mp.MAILPIECE_ID
  WHERE ms.MAILSEGMENT_BILLINGSTATUS = 0

    UPDATE s SET MAILSEGMENT_BILLINGSTATUS = 2
    OUTPUT 
		inserted.MAILSEGMENT_ID
		, inserted.MAILSEGMENT_ACCESSIBILITYLEVELID		
    , inserted.MAILSEGMENT_BILLINGSTATUS
    , inserted.MAILSEGMENT_BILLINGINVOICEID
      , inserted.MAILSEGMENT_COMMENTTHREADID
		, inserted.MAILSEGMENT_COMMINGLERID
		, inserted.MAILSEGMENT_COMPLETEMAIL
		, inserted.MAILSEGMENT_CREATED
		, inserted.MAILSEGMENT_CREATEDBYID
		, inserted.MAILSEGMENT_CRIDID
		, inserted.MAILSEGMENT_DATADUE
		, inserted.MAILSEGMENT_DESCRIPTION
		, inserted.MAILSEGMENT_DESTINATIONANALYSIS
		, inserted.MAILSEGMENT_DROPDATE
		, inserted.MAILSEGMENT_ENTRYPOINT
		, inserted.MAILSEGMENT_ESTQTY		
		, inserted.MAILSEGMENT_FIRSTFINALIZESCANID
		, inserted.MAILSEGMENT_FIRSTSCANID		
		, inserted.MAILSEGMENT_COMMINGLERSEGMENTID
		, inserted.MAILSEGMENT_JOBID
		, inserted.MAILSEGMENT_LASTFINALIZESCANID		
		, inserted.MAILSEGMENT_LASTSCANID
		, inserted.MAILSEGMENT_ISMAILANYWHERE
		, inserted.MAILSEGMENT_MAILANYWHEREACCTNO
		, inserted.MAILSEGMENT_MATERIALDUE		
		, inserted.MAILSEGMENT_MATCHMAIL
		, inserted.MAILSEGMENT_METERRATE
		, inserted.MAILSEGMENT_NAME		
		, inserted.MAILSEGMENT_NONPROFIT	
		, inserted.MAILSEGMENT_OUTGOING		
		, inserted.MAILSEGMENT_PIECEHEIGHT
		, inserted.MAILSEGMENT_PIECELENGTH
		, inserted.MAILSEGMENT_PIECETHICKNESS
		, inserted.MAILSEGMENT_PIECETYPEID
		, inserted.MAILSEGMENT_PIECEWEIGHT		
		, inserted.MAILSEGMENT_POSTAGEAPPLIEDID
		, inserted.MAILSEGMENT_POSTALCLASSID			
		, inserted.MAILSEGMENT_PERMITID
		, inserted.MAILSEGMENT_PRESORTED
		, inserted.MAILSEGMENT_MAILSTREAMID
		, inserted.MAILSEGMENT_SEGMENTTYPEID		
		, inserted.MAILSEGMENT_SPECIALPREPARATION
		, inserted.MAILSEGMENT_TARGETDATE
		, inserted.MAILSEGMENT_TRACKINGTYPEID
		, inserted.MAILSEGMENT_ROWVERSION	
	FROM 
		[dbo].[MailSegments] AS s
	WHERE
		s.MAILSEGMENT_BILLINGSTATUS = 1
END
GO