SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[InventoryReceiptItemsGetByClientIDPaged] 
	@ID				int
	, @Page			int
	, @RowsPerPage	int
AS
BEGIN
	
	SET NOCOUNT ON;
		
	DECLARE @StartRow int,
		@EndRow int;

	SET @StartRow = ((@Page - 1) * @RowsPerPage) + 1;
	SET @EndRow = @StartRow + @RowsPerPage - 1;

	SELECT * FROM (
		SELECT 
			ROW_NUMBER() OVER (ORDER BY INVENTORYRECEIPTITEM_ID DESC, ir.INVENTORYRECEIPT_RECEIVED DESC) AS ResultNum
		,	INVENTORYRECEIPTITEM_ID
		, INVENTORYRECEIPTITEM_CONTAINERCOUNT
		, INVENTORYRECEIPTITEM_CONTAINERS
		, INVENTORYRECEIPTITEM_CONTAINERTYPEID
    , INVENTORYRECEIPTITEM_ITEMID
      , INVENTORYRECEIPTITEM_NOTE
		, INVENTORYRECEIPTITEM_RECEIPTID
      ,INVENTORYRECEIPTITEM_ROWVERSION
		FROM 
			[dbo].[InventoryReceiptItems]
      INNER JOIN dbo.InventoryReceipts ir ON INVENTORYRECEIPTITEM_RECEIPTID = ir.INVENTORYRECEIPT_ID
      
		WHERE INVENTORYRECEIPTITEM_ID IN (
			SELECT 
				ir.INVENTORYRECEIPT_ID
			FROM 
				[dbo].[InventoryReceiptItems] AS iri
        INNER JOIN dbo.InventoryReceipts ir ON iri.INVENTORYRECEIPTITEM_RECEIPTID = ir.INVENTORYRECEIPT_ID
				INNER JOIN [dbo].[InventoryItems] AS i
					ON iri.INVENTORYRECEIPTITEM_ITEMID = i.[ID]
			WHERE 
				i.[ClientID] = @ID))		
		AS NumberResults
	WHERE ResultNum BETWEEN @StartRow AND @EndRow;	
END
GO