SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProjectsGetCountByClientID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		COUNT(PROJECT_ID)
	FROM 
		[dbo].[Projects]
	WHERE
		PROJECT_CLIENTID = @ID;
END
GO