SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[JobStageRolesGetByRoleID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT * FROM tblJobStageRoles WHERE JOBSTAGEROLE_ROLEID = @ID;
END
GO