SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


--region [dbo].[SendGridNewsletterUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[SendGridNewsletterUpdate]
-- Date Generated: Monday, September 21, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[SendGridNewsletterUpdate]
	@Id int,
	@Newsletteruserlistid int,
	@Newslettersendid int
AS

SET NOCOUNT ON

UPDATE [dbo].[SendGridNewsletters] SET
	[NewsletterUserListId] = @Newsletteruserlistid,
	[NewsletterSendId] = @Newslettersendid
WHERE
	[Id] = @Id

--endregion
GO