SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_MailRecordsGetCoverageCodes] 
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		DISTINCT(MAILRECORD_COVERAGECODE) AS COVERAGECODE		
	FROM 
		[dbo].[colpenn_MailRecords] 	
	ORDER BY 
		MAILRECORD_COVERAGECODE;
END
GO