SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[JobsGetByClientIDs]
	@IDs varchar(100)	
AS
BEGIN
	
	SET NOCOUNT ON;
    
    SELECT
		m.JOB_ID
		, m.JOB_ACCESSIBILITYLEVEL
      , m.JOB_COMMENTTHREADID
		, m.JOB_CAMPAIGNID
		, m.JOB_COMMINGLERJOBID
		, m.JOB_CONTACT
		, m.JOB_CREATED
		, m.JOB_CREATEDBYID		
		, m.JOB_DATADUE
		, COALESCE(( 
			SELECT
				MIN(s.MAILSEGMENT_DROPDATE)
			FROM
				[dbo].[MailSegments] AS s
			WHERE
				s.MAILSEGMENT_JOBID = m.JOB_ID
		), m.JOB_DROPDATE) AS JOB_DROPDATE
		, m.JOB_ESTIMATEDQUANTITY
		, m.JOB_MATERIALDUE
		, m.JOB_NAME
		, m.JOB_JOBID
      , m.JOB_LETTERSHOPID
		, m.JOB_PONUMBER
		, m.JOB_PRIORITYID
		, m.JOB_REFERENCE
		, m.JOB_SHORTNAME
		, m.JOB_ROWVERSION 
	FROM 
		[dbo].[Jobs] AS m
		INNER JOIN [job].[Jobs] AS j
			ON m.JOB_JOBID = j.JOB_ID
		INNER JOIN IntegerListToTable(@IDs) AS i 
			ON j.JOB_CLIENTID = i.number			
	ORDER BY
		m.JOB_ID;
END
GO