SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingServiceLogCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingServiceLogCreate]
-- Date Generated: Wednesday, May 31, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingServiceLogCreate]
	@Created datetime,
	@Createdbyid int,
	@Message varchar(max),
	@Processstarttime datetime,
	@Processendtime datetime,
	@Processstatus int,
	@Segmentsprocessed int,
	@Stacktrace varchar(max)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[BillingServiceLog] (
	[Created],
	[CreatedById],
	[Message],
	[ProcessStartTime],
	[ProcessEndTime],
	[ProcessStatus],
	[SegmentsProcessed],
	[StackTrace]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Created,
	@Createdbyid,
	@Message,
	@Processstarttime,
	@Processendtime,
	@Processstatus,
	@Segmentsprocessed,
	@Stacktrace
)

--endregion

GO