SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[AssignmentsGetByUserID]
	@ID int
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT
		ASSIGNMENT_ID,
		ASSIGNMENT_JOBID,
		ASSIGNMENT_USERID,
		ASSIGNMENT_ROWVERSION
	FROM 
		Assignments 
	WHERE 
		ASSIGNMENT_USERID = @ID 
	ORDER BY 
		ASSIGNMENT_ID;
END
GO