SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[ClientCreationRequestDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ClientCreationRequestDeleteById]
-- Date Generated: Friday, August 19, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ClientCreationRequestDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[ClientCreationRequests]
WHERE
	[Id] = @Id

--endregion

GO