SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SystemAlertGetByID]
	@ID	int
	
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		ALERT_ID
		, ALERT_DISPLAYEND
		, ALERT_DISPLAYSTART
		, ALERT_MESSAGE
		, ALERT_POSTED
		, ALERT_POSTEDBYID
		, ALERT_TITLE		
	FROM 
		[dbo].[SystemAlerts] 
	WHERE  
		ALERT_ID = @ID;
END
GO