SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingTiersetUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingTiersetUpdate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingTiersetUpdate]
@Version				timestamp,
	@Id int,
	@Tiersetid int,
	@Currencyid int,
	@Setup decimal(18, 4),
	@Base decimal(18, 4),
	@Percent decimal(18, 4),
	@Paycycle varchar(500),
	@Pricemodel varchar(500),
	@Writedatetime datetime,
	@Moddatetime datetime,
	@Currencysymbol varchar(50),
	@Currencyiso4217 varchar(50),
	@Itemid int,
	@Setupformatted varchar(50),
	@Baseformatted varchar(50),
	@Percentformatted varchar(50),
	@Pricemodeldesc varchar(500)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingTiersets] SET
	[TiersetId] = @Tiersetid,
	[CurrencyId] = @Currencyid,
	[Setup] = @Setup,
	[Base] = @Base,
	[Percent] = @Percent,
	[Paycycle] = @Paycycle,
	[PriceModel] = @Pricemodel,
	[WriteDatetime] = @Writedatetime,
	[ModDatetime] = @Moddatetime,
	[CurrencySymbol] = @Currencysymbol,
	[CurrencyIso4217] = @Currencyiso4217,
	[ItemId] = @Itemid,
	[SetupFormatted] = @Setupformatted,
	[BaseFormatted] = @Baseformatted,
	[PercentFormatted] = @Percentformatted,
	[PriceModelDesc] = @Pricemodeldesc
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO