SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailTypeGetByID] 
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT 
		MAILTYPE_ID
		, MAILTYPE_DESCRIPTION
	FROM 
		[dbo].[MailTypes]
	WHERE
		MAILTYPE_ID = @ID
END
GO