SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[ClientInvitationCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ClientInvitationCreate]
-- Date Generated: Wednesday, May 17, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ClientInvitationCreate]
	@Clientid int,
	@Clienttypeid int,
	@Created datetime,
	@Createdbyid int,
	@Expiration datetime,
	@Invitationstate int,
	@Partnerclientid int,
	@Partneremail nvarchar(200),
	@Placesid varchar(500),
	@Relationshiptype int

AS

SET NOCOUNT ON

INSERT INTO [dbo].[ClientInvitation] (
	[ClientId],
	[ClientTypeId],
	[Created],
	[CreatedById],
	[Expiration],
	[InvitationState],
	[PartnerClientId],
	[PartnerEmail],
	[PlacesId],
	[RelationshipType]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Clientid,
	@Clienttypeid,
	@Created,
	@Createdbyid,
	@Expiration,
	@Invitationstate,
	@Partnerclientid,
	@Partneremail,
	@Placesid,
	@Relationshiptype
)

--endregion

GO