SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailUnsubscribeLogUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailUnsubscribeLogUpdate]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailUnsubscribeLogUpdate]
	@Id int,
	@Event varchar(50),
	@Recipient varchar(500),
	@Domain varchar(500),
	@Ip varchar(50),
	@Country varchar(500),
	@Region varchar(500),
	@City varchar(500),
	@Useragent varchar(500),
	@Devicetype varchar(50),
	@Clienttype varchar(50),
	@Clientname varchar(50),
	@Clientos varchar(50),
	@Campaignid varchar(50),
	@Campaignname varchar(500),
	@Tag varchar(100),
	@Mailinglist varchar(500),
	@SendId int,
	
	@Timestamp varchar(50),
	@Token varchar(100),
	@Signature varchar(500),
	@Bodyplaintext varchar(4000)
AS

SET NOCOUNT ON

UPDATE [dbo].[mailgun_UnsubscribeLog] SET
	[Event] = @Event,
	[Recipient] = @Recipient,
	[Domain] = @Domain,
	[Ip] = @Ip,
	[Country] = @Country,
	[Region] = @Region,
	[City] = @City,
	[UserAgent] = @Useragent,
	[DeviceType] = @Devicetype,
	[ClientType] = @Clienttype,
	[ClientName] = @Clientname,
	[ClientOs] = @Clientos,
	[CampaignId] = @Campaignid,
	[CampaignName] = @Campaignname,
	[Tag] = @Tag,
	[MailingList] = @Mailinglist,
	[SendId] = @SendId,
	
	[Timestamp] = @Timestamp,
	[Token] = @Token,
	[Signature] = @Signature,
	[BodyPlainText] = @Bodyplaintext
WHERE
	[Id] = @Id

--endregion
GO