SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[NdcServiceAreasGet]
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		NDCSERVICEAREA_ID
		, NDCSERVICEAREA_END
		, NDCSERVICEAREA_NDCID
		, NDCSERVICEAREA_START
    FROM
		[dbo].[NDCServiceAreas];	
END
GO