SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[ClientInvitationsGetByInvitationState]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[ClientInvitationsGetByInvitationState]
-- Date Generated: Friday, March 3, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[ClientInvitationsGetByInvitationState]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ClientId],
	[Created],
	[CreatedById],
	[Expiration],
	[InvitationState],
	[PartnerClientId],
	[PartnerEmail],
	[PlacesId],
	[RelationshipType],
	[Rowversion]
FROM
	[dbo].[ClientInvitation]
WHERE
	[InvitationState] = @Id

--endregion

GO