SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingChargeOverLogUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverLogUpdate]
-- Date Generated: Tuesday, February 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverLogUpdate]
	@Id int,
	@Contextstr varchar(50),
	@Contextid int,
	@Created datetime,
	@Createdbyid int,
	@Eventstr varchar(50),
	@Securitytoken varchar(50),
	@Package varchar(max),
	@Baseobj varchar(max),
	@Billingpackage varchar(max),
	@Bulk varchar(max),
	@Invoice varchar(50),
	@Item varchar(max),
	@Lineitem varchar(max),
	@Transaction varchar(max),
	@Customer varchar(max),
	@User varchar(max)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[Billing_ChargeOverLog] SET
	[ContextStr] = @Contextstr,
	[ContextId] = @Contextid,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[EventStr] = @Eventstr,
	[SecurityToken] = @Securitytoken,
	[Package] = @Package,
	[BaseObj] = @Baseobj,
	[BillingPackage] = @Billingpackage,
	[Bulk] = @Bulk,
	[Invoice] = @Invoice,
	[Item] = @Item,
	[LineItem] = @Lineitem,
	[Transaction] = @Transaction,
	[Customer] = @Customer,
	[User] = @User
    OUTPUT inserted.Id AS [ID]
WHERE
	[Id] = @Id

--endregion

GO