SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[BillingItemsGetByWriteDateTimeBetween]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingItemsGetByWriteDateTimeBetween]
-- Date Generated: Friday, June 16, 2017
------------------------------------------------------------------------------------------------------------------------


CREATE PROCEDURE [dbo].[BillingItemsGetByWriteDateTimeBetween]
    @To DATETIME,
    @From DATETIME
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ItemId],
	[ItemType],
	[TiersetId],
	[Name],
	[Description],
	[Units],
	[Enabled],
	[AccountingSku],
	[Token],
	[Custom1],
	[Custom2],
	[Custom3],
	[WriteDateTime],
	[ModDateTime],
	[UnitsPlural],
	[ExpireRecurs],
	[TrialRecurs],
	[RowVersion]
FROM
	[dbo].[BillingItems]
WHERE
    WriteDateTime BETWEEN @From AND @To 

--endregion

GO