SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[UserImagesGetByTypeIdByCreated]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[UserImagesGetByTypeIdByCreated]
-- Date Generated: Wednesday, July 5, 2017
------------------------------------------------------------------------------------------------------------------------


CREATE PROCEDURE [dbo].[UserImagesGetByTypeIdByCreated]
    @To DATETIME,
    @From DATETIME,
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ClassName],
	[ContentTypeId],
	[Compressed],
	[Created],
	[CreatedById],
	[Data],
	[Description],
	[Name],
	[Size],
	[TypeId],
	[Uploaded],
	[RowVersion]
FROM
	[dbo].[UserImages]
WHERE
    Created  BETWEEN @From AND @To AND 	[TypeId] = @Id


--endregion

GO