SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[MailPieceGetByID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT
		m.MAILPIECE_ID
		, m.MAILPIECE_ADDRESS1
		, m.MAILPIECE_ADDRESS2
		, m.MAILPIECE_ADDRESS3		
		, m.MAILPIECE_CITY
		, m.MAILPIECE_COMPANY
		, m.MAILPIECE_CRRT
		, m.MAILPIECE_DELIVERYDATE
		, m.MAILPIECE_FINALIZESCANID
		, m.MAILPIECE_FIRSTNAME
		, m.MAILPIECE_FIRSTSCANID
		, m.MAILPIECE_FORWARDSCANID
		, m.MAILPIECE_GROUPID
		, m.MAILPIECE_INDIVIDUALID
		, m.MAILPIECE_LASTNAME
		, m.MAILPIECE_LASTSCANID
		, m.MAILPIECE_SEGMENTID
		, m.MAILPIECE_RETURNSCANID
		, m.MAILPIECE_ROUTINGCODE
		, m.MAILPIECE_SCFID
		, m.MAILPIECE_STATE
		, m.MAILPIECE_TARGETID
		, m.MAILPIECE_TITLE
		, m.MAILPIECE_TRACKINGCODE
		, m.MAILPIECE_ZIPCODE
		, m.MAILPIECE_ZIPCODEEXT		
	FROM
		[dbo].[MailPieces] AS m
	WHERE
		m.MAILPIECE_ID = @ID;
END
GO