SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingCategoryUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingCategoryUpdate]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingCategoryUpdate]
@Version				timestamp,
	@Id int,
	@Categoryid int,
	@Itemid int,
	@Name varchar(50)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingCategories] SET
	[CategoryId] = @Categoryid,
	[ItemId] = @Itemid,
	[Name] = @Name
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO