SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailDeliveryLogInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailDeliveryLogInsert]
-- Date Generated: Monday, November 2, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailDeliveryLogInsert]
	@Event varchar(50),
	@Recipient varchar(500),
	@Domain varchar(500),
	@Messageheaders varchar(4000),
	@Messageid varchar(500),
	@SendId int,	
	@Timestamp varchar(50),
	@Token varchar(100),
	@Signature varchar(100),
	@Bodyplaintext varchar(4000)

AS

SET NOCOUNT ON

INSERT INTO [dbo].[mailgun_DeliveryLog] (
	[Event],
	[Recipient],
	[Domain],
	[MessageHeaders],
	[MessageId],
	[SendId],	
	[Timestamp],
	[Token],
	[Signature],
	[BodyPlainText]
) 
OUTPUT		
		inserted.Id AS [ID], NULL AS [VERSION]
VALUES (
	@Event,
	@Recipient,
	@Domain,
	@Messageheaders,
	@Messageid,
	@SendId,	
	@Timestamp,
	@Token,
	@Signature,
	@Bodyplaintext
)

--endregion
GO