SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingCategoriesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingCategoriesGetAll]
-- Date Generated: Monday, June 19, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingCategoriesGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[CategoryId],
	[ItemId],
	[Name],
	[Rowversion]
FROM
	[dbo].[BillingCategories]

--endregion

GO