SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WarehouseBaysGetBySectionID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		BAY_ID
		, BAY_DESCRIPTION
		, BAY_NUMBER
		, BAY_SECTIONID
		, BAY_ROWVERSION
	FROM WarehouseBays
	WHERE
		(BAY_SECTIONID = @ID);
END
GO