SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BulkServiceDiscountsGetByServiceID]
	@ID			int
AS
	SET NOCOUNT ON;
	
	SELECT
		DISCOUNT_ID,
		DISCOUNT_HIGHTHRESHOLD,
		DISCOUNT_LOWTHRESHOLD,
		DISCOUNT_PERCENT,
		DISCOUNT_SERVICEID,		
		DISCOUNT_UNITPRICE,
		DISCOUNT_ROWVERSION
	FROM
		BulkServiceDiscounts
	WHERE 
		DISCOUNT_SERVICEID = @ID
	ORDER BY 
		DISCOUNT_ID;;
GO