SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_RejectRecordsGetDateCountByTransactionDateRange] (
  @From	datetime	= NULL
  , @To		datetime	= NULL  
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		REJECTRECORD_TRANSACTIONDATE AS [DATE]
		, COUNT(*) AS [COUNT]
	FROM 
		[dbo].[colpenn_RejectRecords] 
	WHERE
		(@From IS NULL OR REJECTRECORD_TRANSACTIONDATE >= @From)
		AND (@To IS NULL OR REJECTRECORD_TRANSACTIONDATE <= @To)
	GROUP BY
		REJECTRECORD_TRANSACTIONDATE
END
GO