SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingChargeOverRawLogGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverRawLogGetById]
-- Date Generated: Tuesday, May 2, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverRawLogGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[RawRequest],
	[Created],
	[CreatedById],
	[ChargeOverLogItemId]
FROM
	[dbo].[Billing_ChargeOverRawLog]
WHERE
	[Id] = @Id

--endregion

GO