SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingServiceLogUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingServiceLogUpdate]
-- Date Generated: Wednesday, May 31, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingServiceLogUpdate]
@Version				timestamp,
	@Id int,
	@Created datetime,
	@Createdbyid int,
	@Message varchar(max),
	@Processstarttime datetime,
	@Processendtime datetime,
	@Processstatus int,
	@Segmentsprocessed int,
	@Stacktrace varchar(max)
    
AS

SET NOCOUNT ON

UPDATE [dbo].[BillingServiceLog] SET
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[Message] = @Message,
	[ProcessStartTime] = @Processstarttime,
	[ProcessEndTime] = @Processendtime,
	[ProcessStatus] = @Processstatus,
	[SegmentsProcessed] = @Segmentsprocessed,
	[StackTrace] = @Stacktrace
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO