SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[EmailBannedDomainUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[EmailBannedDomainUpdate]
-- Date Generated: Tuesday, November 3, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[EmailBannedDomainUpdate]
	@Id int,
	@Domain nvarchar(4000)
AS

SET NOCOUNT ON

UPDATE [dbo].[mailgun_BannedDomains] SET
	[Domain] = @Domain
WHERE
	[Id] = @Id

--endregion
GO