SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WarehousesGetByClientLocationID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		WAREHOUSE_ID
		, WAREHOUSE_CLIENTLOCATIONID
		, WAREHOUSE_NAME
		, WAREHOUSE_ROWVERSION
	FROM 
		dbo.Warehouses
	WHERE
		WAREHOUSE_CLIENTLOCATIONID = @ID;
END
GO