SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ProjectsGetCountByParentID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		COUNT(PROJECT_ID)		
	FROM 
		[dbo].[Projects]
	WHERE
		PROJECT_PARENTID = @ID;
END
GO