SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[colpenn_SourceRecordsGetDateCountByTransactionDateRange] (
  @From	datetime	= NULL
  , @To		datetime	= NULL  
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		SOURCERECORD_TRANSACTIONDATE AS [DATE]
		, COUNT(*) AS [COUNT]
	FROM 
		[dbo].[colpenn_SourceRecords] 
	WHERE
		(@From IS NULL OR SOURCERECORD_TRANSACTIONDATE >= @From)
		AND (@To IS NULL OR SOURCERECORD_TRANSACTIONDATE <= @To)
	GROUP BY
		SOURCERECORD_TRANSACTIONDATE
END
GO