SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [dbo].[BillingChargeOverLogGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[BillingChargeOverLogGetById]
-- Date Generated: Tuesday, February 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[BillingChargeOverLogGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ContextStr],
	[ContextId],
	[Created],
	[CreatedById],
	[EventStr],
	[SecurityToken],
	[Package],
	[BaseObj],
	[BillingPackage],
	[Bulk],
	[Invoice],
	[Item],
	[LineItem],
	[Transaction],
	[Customer],
	[User]
FROM
	[dbo].[Billing_ChargeOverLog]
WHERE
	[Id] = @Id

--endregion

GO