SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[AddressCustomPropertyGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[AddressCustomPropertyGetById]
-- Date Generated: Monday, June 29, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[AddressFieldGetByAddressIdAndType]
	@AddressId int,
	@Type varchar(50)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	ecp.[Id],
	ecp.[Name],
	ecp.[AddressId],
	ecp.[TypeId],
	ecp.[Value],
	ecp.[Rowversion]
FROM
	[email].[AddressCustomProperties] as ecp
	INNER JOIN dbo.CustomPropertyTypes cpt on cpt.Id = ecp.TypeId
WHERE
	ecp.AddressId = @AddressId and cpt.Name = @Type

--endregion
GO