SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[InsertSubscriberAddress]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[InsertSubscriberAddress]
-- Date Generated: Monday, May 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[InsertSubscriberAddress]
	@Subscriberid int,
	@Addressid int,
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [email].[SubscriberAddresses] (
	[SubscriberId],
	[AddressId]
) VALUES (
	@Subscriberid,
	@Addressid
)

SET @Id = SCOPE_IDENTITY()

--endregion
GO