SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[AddressCustomPropertyGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[AddressCustomPropertyGetById]
-- Date Generated: Monday, June 29, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[AddressFieldGetByAddressIdAndTypeId]
	@AddressId int,
	@TypeId int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	ecp.[Id],
	ecp.[Name],
	ecp.[AddressId],
	ecp.[TypeId],
	ecp.[Value],
	ecp.[Rowversion]
FROM
	[email].[AddressCustomProperties] as ecp
WHERE
	ecp.AddressId = @AddressId and ecp.TypeId = @TypeId

--endregion
GO