SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[SelectSubscriberAddressesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[SelectSubscriberAddressesAll]
-- Date Generated: Monday, May 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[SelectSubscriberAddressesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[SubscriberId],
	[AddressId]
FROM
	[email].[SubscriberAddresses]

--endregion
GO