SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[DeleteSubscriberAddressesByAddressId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[DeleteSubscriberAddressesByAddressId]
-- Date Generated: Monday, May 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[DeleteSubscriberAddressesByAddressId]
	@Addressid int
AS

SET NOCOUNT ON

DELETE FROM [email].[SubscriberAddresses]
WHERE
	[AddressId] = @Addressid
GO