SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[DeleteSubscriberAddressesBySubscriberId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[DeleteSubscriberAddressesBySubscriberId]
-- Date Generated: Monday, May 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[DeleteSubscriberAddressesBySubscriberId]
	@Subscriberid int
AS

SET NOCOUNT ON

DELETE FROM [email].[SubscriberAddresses]
WHERE
	[SubscriberId] = @Subscriberid
GO