SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[DeleteSubscriberAddress]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[DeleteSubscriberAddress]
-- Date Generated: Monday, May 11, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[DeleteSubscriberAddress]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [email].[SubscriberAddresses]
WHERE
	[Id] = @Id

--endregion
GO