SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [email].[AddressCustomPropertyInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [email].[AddressCustomPropertyInsert]
-- Date Generated: Monday, June 29, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [email].[AddressFieldCreate]
	@Name nvarchar(200),
	@Addressid int,
	@Typeid int,
	@Value nvarchar(max)

AS

SET NOCOUNT ON

INSERT INTO [email].[AddressCustomProperties] (
	[Name],
	[AddressId],
	[TypeId],
	[Value]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Name,
	@Addressid,
	@Typeid,
	@Value
)

--endregion
GO