SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FolderGetID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT
		FOLDER_ID
		, FOLDER_CREATED
		, FOLDER_CREATEDBYID
		, FOLDER_DESCRIPTION
		, FOLDER_FOLDERID
		, FOLDER_NAME
		, CONVERT(BIGINT, 0) AS [FOLDER_SIZE]
		, FOLDER_USERID
		, FOLDER_ROWVERSION
	FROM
		[file].[Folders]
	WHERE
		FOLDER_ID = @ID;
END
GO