SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[_DataGetByMetaDataID]
	@ID int = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		DATA_ID
		, DATA_DATA
		, DATA_METADATAID		
		, DATA_ROWVERSION		
	FROM 
		[file].[Data]
	WHERE 
		DATA_METADATAID = @ID		
	ORDER BY 
		DATA_ID;
END
GO