SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[ContentTypeGetByID]
	@ID	int
AS
BEGIN
	
	SET NOCOUNT ON;
    
	SELECT 
		CONTENTTYPE_ID
		, CONTENTTYPE_EXTENSION
		, CONTENTTYPE_MIMETYPE
	FROM
		[file].[ContentTypes]
	WHERE
		CONTENTTYPE_ID = @ID;	
END
GO