SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[_MetaDataGetByUserID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		METADATA_ID
		, METADATA_COMPRESSED
		, METADATA_CONTENTTYPEID			
		, METADATA_DESCRIPTION
		, METADATA_FILENAME
		, METADATA_FOLDERID
		, METADATA_SIZE
		, METADATA_TYPEID
		, METADATA_UPLOADED
		, METADATA_USERID
		, METADATA_ROWVERSION		
	FROM 
		[file].[MetaData]
	WHERE 
		METADATA_USERID = @ID
	ORDER BY 
		METADATA_ID;
END
GO