SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FolderPermissionsGetByFolderID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		FOLDERPERMISSION_ID
		, FOLDERPERMISSION_FOLDERID
		, FOLDERPERMISSION_PRIVILEGES
		, FOLDERPERMISSION_USERID
		, FOLDERPERMISSION_ROWVERSION
	FROM
		[file].[FolderPermissions]
	WHERE
		FOLDERPERMISSION_FOLDERID = @ID;
END
GO