SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[CommonSharesGetByUserID]
	@UserID	int
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT DISTINCT
		USER_USERID
		, USER_ADDRESS1
		, USER_ADDRESS2
		, USER_CITY
		, USER_CLIENT_ID
		, USER_CREATED
		, USER_CREATEDBY_ID
		, USER_DEFAULTURL		
		, USER_FAX
    	, USER_FIRSTNAME
		, USER_INACTIVELOGOUT
		, USER_LASTNAME
		, USER_LOCKEDOUT		
		, USER_PHONE
		, USER_POSTALCODE
		, USER_REGION
		, USER_ROLES
		, USER_SECONDARY_EMAIL
		, USER_USERNAME
		, USER_ROWVERSION
	FROM 
		[dbo].[Users] AS u
		INNER JOIN [file].[FolderPermissions] AS p
			ON u.USER_USERID = p.FOLDERPERMISSION_USERID
		INNER JOIN [file].[Folders] AS f
			ON p.FOLDERPERMISSION_FOLDERID = f.FOLDER_ID
	WHERE
		f.FOLDER_USERID = @UserID

	UNION
    
	
	SELECT DISTINCT
		USER_USERID
		, USER_ADDRESS1
		, USER_ADDRESS2
		, USER_CITY
		, USER_CLIENT_ID
		, USER_CREATED
		, USER_CREATEDBY_ID
		, USER_DEFAULTURL		
		, USER_FAX
    	, USER_FIRSTNAME
		, USER_INACTIVELOGOUT
		, USER_LASTNAME
		, USER_LOCKEDOUT		
		, USER_PHONE
		, USER_POSTALCODE
		, USER_REGION
		, USER_ROLES
		, USER_SECONDARY_EMAIL
		, USER_USERNAME
		, USER_ROWVERSION
	FROM 
		[dbo].[Users] AS u
		INNER JOIN [file].[FilePermissions] AS p
			ON u.USER_USERID = p.FILEPERMISSION_USERID
		INNER JOIN [file].[Files] AS f
			ON p.FILEPERMISSION_METADATAID = f.[FILE_ID]
	WHERE
		f.FILE_USERID = @UserID

END
GO