SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FileLinkDownloadsGetByFileID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		d.DOWNLOAD_ID
		, d.DOWNLOAD_DATETIME
		, d.DOWNLOAD_IPADDRESS
		, d.DOWNLOAD_IPCITYNAME
		, d.DOWNLOAD_IPCOUNTRYCODE
		, d.DOWNLOAD_IPLATITUDE
		, d.DOWNLOAD_IPLONGITUDE
		, d.DOWNLOAD_IPPOSTALCODE
		, d.DOWNLOAD_IPREGIONCODE
		, d.DOWNLOAD_LINKID
		, d.DOWNLOAD_USERAGENT
	FROM
		[file].[FileLinkDownloads] AS d
		INNER JOIN [file].[FileLinks] AS l
			ON d.DOWNLOAD_LINKID = l.LINK_ID
	WHERE
		l.LINK_FILEID = @ID;
END
GO