SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FilesGetByFolderID]
	@ID int = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		[FILE_ID]
		, FILE_COMPRESSED
		, FILE_CONTENTTYPEID		
		, FILE_DESCRIPTION
		, [FILE_NAME]
		, FILE_FOLDERID
		, FILE_SIZE
		, FILE_TYPEID
		, FILE_UPLOADED
		, FILE_USERID
		, FILE_ROWVERSION		
	FROM 
		[file].[Files]
	WHERE 
		FILE_FOLDERID = @ID
		OR (FILE_FOLDERID IS NULL AND @ID IS NULL);
END
GO