SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [file].[FilePermissionsGet]
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		FILEPERMISSION_ID
		, FILEPERMISSION_METADATAID
		, FILEPERMISSION_PRIVILEGES
		, FILEPERMISSION_USERID
		, FILEPERMISSION_ROWVERSION
	FROM
		[file].[FilePermissions]
	ORDER BY
		FILEPERMISSION_ID;
END
GO