SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[CommentFileGetByID] 
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		[FILE_ID]
		, FILE_COMPRESSED
		, FILE_CONTENTTYPEID		
		, FILE_DESCRIPTION
		, [FILE_NAME]
		, FILE_SIZE
		, FILE_TYPEID
		, FILE_UPLOADED
		, FILE_ROWVERSION	
	FROM 
		[file].[CommentFiles]
	WHERE 
		[FILE_ID] = @ID;
END
GO