SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FileLinksGetByFileID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		LINK_ID
		, LINK_CREATED
		, LINK_CREATEDBYID
		, LINK_EMAILADDRESS
		, LINK_FILEID
		, LINK_KEY		
	FROM
		[file].[FileLinks]
	WHERE
		LINK_FILEID = @ID;
END
GO