SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[ContentTypeGetByExtension]
	@Key	nvarchar(10)
AS
BEGIN
	
	SET NOCOUNT ON;
    
    SELECT 
		CONTENTTYPE_ID
		, CONTENTTYPE_EXTENSION
		, CONTENTTYPE_MIMETYPE
	FROM
		[file].[ContentTypes]
	WHERE
		CONTENTTYPE_EXTENSION = @Key
		OR (CONTENTTYPE_EXTENSION IS NULL AND @Key IS NULL)
	ORDER BY
		CONTENTTYPE_ID;
END
GO