SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[CommentFilesGet] 
	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		[FILE_ID]
		, FILE_COMPRESSED
		, FILE_CONTENTTYPEID
		, FILE_DESCRIPTION
		, [FILE_NAME]
		, FILE_SIZE
		, FILE_TYPEID
		, FILE_UPLOADED
		, FILE_ROWVERSION	
	FROM 
		[file].[CommentFiles];
END
GO