SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [file].[FilesGetByUserIDByFolderID]
	@ID			int
	, @Filter	int = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		f.[FILE_ID]
		, f.FILE_COMPRESSED
		, f.FILE_CONTENTTYPEID		
		, f.FILE_DESCRIPTION
		, f.[FILE_NAME]
		, f.FILE_FOLDERID
		, f.FILE_SIZE
		, f.FILE_TYPEID
		, f.FILE_UPLOADED
		, f.FILE_USERID
		, f.FILE_ROWVERSION		
	FROM 
		[file].[Files] AS f
		LEFT JOIN [file].[FilePermissions] AS p
			ON f.FILE_ID = p.FILEPERMISSION_METADATAID
	WHERE
		-- owned files 
		(FILE_USERID = @ID
		AND (FILE_FOLDERID = @Filter
			OR (FILE_FOLDERID IS NULL AND @Filter IS NULL)))
		-- shared folders
		OR (p.FILEPERMISSION_USERID = @ID AND p.FILEPERMISSION_PRIVILEGES > 0 AND (f.FILE_FOLDERID = @Filter
				OR (f.FILE_FOLDERID IS NULL AND @Filter IS NULL)));
END
GO