SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [file].[FilePermissionExists]
	@FileID	int
	, @UserID int
AS
BEGIN
	
	IF EXISTS(SELECT FILEPERMISSION_ID FROM [file].[FilePermissions] WHERE FILEPERMISSION_METADATAID = @FileID AND FILEPERMISSION_USERID = @UserID)
		SELECT 1;
	ELSE
		SELECT 0;
END
GO