SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [ip].[LocationGetByNetworkAddress]
	@NetworkAddress	bigint
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT 
		l.LOCATION_ID
		, l.LOCATION_CITY
		, l.LOCATION_COUNTRYCODE
		, l.LOCATION_LATITUDE
		, l.LOCATION_LONGITUDE
		, l.LOCATION_POSTALCODE
		, l.LOCATION_REGIONCODE
	FROM
		[ip].[Locations] AS l
		INNER JOIN [ip].[Blocks] AS b
			ON b.BLOCK_LOCATIONID = l.LOCATION_ID
	WHERE
		@NetworkAddress BETWEEN b.BLOCK_START AND b.BLOCK_END;

END
GO