SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingPersonalizationProductionProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPersonalizationProductionProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPersonalizationProductionProcessGroupInsert]
	@Processid int,
	@Affixingpersonalizationitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[AffixingPersonalizationProductionProcessGroups] (
	[ProcessId],
	[AffixingPersonalizationItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Affixingpersonalizationitemid
)

--endregion

GO