SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[FingerprintUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FingerprintUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FingerprintUpdate]
@Version				timestamp,
	@Id int,
	@Fingertypeid int,
	@Fingertemplate varbinary(max),
	@Operatorid int
    
AS

SET NOCOUNT ON

UPDATE [job].[Fingerprint] SET
	[FingerTypeId] = @Fingertypeid,
	[FingerTemplate] = @Fingertemplate,
	[OperatorId] = @Operatorid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO