SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[FoldingProductionProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldingProductionProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldingProductionProcessGroupInsert]
	@Processid int,
	@Foldingitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[FoldingProductionProcessGroups] (
	[ProcessId],
	[FoldingItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Foldingitemid
)

--endregion

GO