SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[DataProcessingItemsGetByMergePurgeType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[DataProcessingItemsGetByMergePurgeType]
-- Date Generated: Monday, February 29, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[DataProcessingItemsGetByMergePurgeType]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[AnalysisType],
	[DataServiceType],
	[Description],
	[KitId],
  MatchTypeId,
	[MergePurgeType],
	[NcoaDate],
	[NcoaType],
  [ProductionTargetId],
	[ReturnFiles],
	[ReturnFileDescription],
  StartTime,
  EndTime,
	[SuppressionType],
	[RowVersion]
FROM
	[job].[DataProcessingItem]
WHERE
	[MergePurgeType] = @Id

--endregion

GO