SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[PersonalizationItemGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[PersonalizationItemGetById]
-- Date Generated: Thursday, January 14, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InsertionPersonalizationItemGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
  DataType,
	[Description],
	[FeedId],
	[Indicia],
	[InsertItemId],
	[LaserTypeId],
	[LayoutId],
	[ModeId],
	[OrientationId],
  [RunDirectionId],
  StartTime,
  EndTime,
	[TargetId],
	[Rowversion]
FROM
	job.[InsertionPersonalizationItem]
WHERE
	[Id] = @Id

--endregion
GO