SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessGroupDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessGroupDeleteById]
-- Date Generated: Friday, August 26, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessGroupDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [job].[SetupProcessGroups]
WHERE
	[Id] = @Id

--endregion

GO