SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessGroupInsert]
-- Date Generated: Friday, August 26, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessGroupInsert]
	@Setupprocessid int,
	@Kitid int

AS

SET NOCOUNT ON

INSERT INTO [job].[SetupProcessGroups] (
	[SetupProcessId],
	[KitId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Setupprocessid,
	@Kitid
)

--endregion

GO