SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ProductionProcessCountInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ProductionProcessCountInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ProductionProcessCountInsert]
	@Inspectorid int,
	@Count int,
	@Counttime datetime,
	@Productionprocessid int

AS

SET NOCOUNT ON

INSERT INTO [job].[ProductionProcessCounts] (
	[InspectorId],
	[Count],
	[CountTime],
	[ProductionProcessId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Inspectorid,
	@Count,
	@Counttime,
	@Productionprocessid
)

--endregion

GO