SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region job.[CuttingItemDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: job.[CuttingItemDeleteById]
-- Date Generated: Monday, January 18, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CuttingItemDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM job.[CuttingItems]
WHERE
	[Id] = @Id

--endregion
GO