SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[MachineGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[MachineGetById]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[MachineGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[MachineName],
	[MachineTypeId],
	[MachineLocationId],
	[RowVersion]
FROM
	[job].[Machines]
WHERE
	[Id] = @Id

--endregion

GO