SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[CuttingProductionProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[CuttingProductionProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CuttingProductionProcessGroupInsert]
	@Processid int,
	@Cuttingitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[CuttingProductionProcessGroups] (
	[ProcessId],
	[CuttingItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Cuttingitemid
)

--endregion

GO