SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[InsertionProductionProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[InsertionProductionProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InsertionProductionProcessGroupInsert]
	@Processid int,
	@Kitid int

AS

SET NOCOUNT ON

INSERT INTO [job].[InsertionProductionProcessGroups] (
	[ProcessId],
	[KitId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Kitid
)

--endregion

GO