SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ClientSageCustomersDeleteByClientId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ClientSageCustomersDeleteByClientId]
-- Date Generated: Friday, August 12, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ClientSageCustomersDeleteByClientId]
	@Clientid int
AS

SET NOCOUNT ON

DELETE FROM [job].[ClientSageCustomers]
WHERE
	[ClientId] = @ClientId

GO