SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ProductionProcessesGetByOperatorId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ProductionProcessesGetByOperatorId]
-- Date Generated: Friday, September 9, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ProductionProcessesGetByOperatorId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[MachineId],
	[Notes],
	[OperatorId],
	[ProcessType],
	[ScheduledEndTime],
	[ScheduledStartTime],
	[StartTime],
	[StopTime],
	[RowVersion]
FROM
	[job].[ProductionProcesses]
WHERE
	[OperatorId] = @Id

--endregion

GO