SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ProductionProcessUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ProductionProcessUpdate]
-- Date Generated: Friday, September 9, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ProductionProcessUpdate]
@Version				timestamp,
	@Id int,
	@Machineid int,
	@Notes varchar(5000),
	@Operatorid int,
	@Processtype int,
	@Scheduledendtime datetime,
	@Scheduledstarttime datetime,
	@Starttime datetime,
	@Stoptime datetime
    
AS

SET NOCOUNT ON

UPDATE [job].[ProductionProcesses] SET
	[MachineId] = @Machineid,
	[Notes] = @Notes,
	[OperatorId] = @Operatorid,
	[ProcessType] = @Processtype,
	[ScheduledEndTime] = @Scheduledendtime,
	[ScheduledStartTime] = @Scheduledstarttime,
	[StartTime] = @Starttime,
	[StopTime] = @Stoptime
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO