SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[DataProcessingItemGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[DataProcessingItemGetById]
-- Date Generated: Monday, February 29, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[DataProcessingItemGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[AnalysisType],
	[DataServiceType],
	[Description],
	[KitId],
[MatchTypeId],
	[MergePurgeType],
	[NcoaDate],
	[NcoaType],
  [ProductionTargetId],
	[ReturnFiles],
	[ReturnFileDescription],
	[SuppressionType],
  StartTime,
  EndTime,
	[RowVersion]
FROM
	[job].[DataProcessingItem]
WHERE
	[Id] = @Id

--endregion

GO