SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingPostageItemUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPostageItemUpdate]
-- Date Generated: Wednesday, April 27, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPostageItemUpdate]
@Version				timestamp,
	@Id int,
	@Denomination decimal(6, 3),
	@Postagetypeid int,
	@Quantity int,
	@Stamptypeid int,
	@Affixingitemid int
    
AS

SET NOCOUNT ON

UPDATE [job].[AffixingPostageItems] SET
	[Denomination] = @Denomination,
	[PostageTypeId] = @Postagetypeid,
	[Quantity] = @Quantity,
	[StampTypeId] = @Stamptypeid,
	[AffixingItemId] = @Affixingitemid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO