SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SeedItemUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SeedItemUpdate]
-- Date Generated: Tuesday, February 23, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SeedItemUpdate]
@Version				timestamp,
	@Id int,
	@Copies int,
	@Fileid int,
	@Fmiseed bit,
	@Instructions varchar(max),
	@Kitid int,
	@Separate bit
    
AS

SET NOCOUNT ON

UPDATE [job].[SeedItems] SET
	[Copies] = @Copies,
	[FileId] = @Fileid,
	[FmiSeed] = @Fmiseed,
	[Instructions] = @Instructions,
	[KitId] = @Kitid,
	[Separate] = @Separate
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO