SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingPostageItemInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPostageItemInsert]
-- Date Generated: Wednesday, April 27, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPostageItemInsert]
	@Denomination decimal(6, 3),
	@Postagetypeid int,
	@Quantity int,
	@Stamptypeid int,
	@Affixingitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[AffixingPostageItems] (
	[Denomination],
	[PostageTypeId],
	[Quantity],
	[StampTypeId],
	[AffixingItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Denomination,
	@Postagetypeid,
	@Quantity,
	@Stamptypeid,
	@Affixingitemid
)

--endregion

GO