SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[InstructionGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[InstructionGetById]
-- Date Generated: Monday, January 18, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InstructionGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[InsertionItemId],
	[Instructions],
	[Type]
FROM
	[job].[Instructions]
WHERE
	[Id] = @Id

--endregion

GO