SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[ProductionProcessesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ProductionProcessesGetAll]
-- Date Generated: Friday, September 9, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessesGetByScheduledDateRange]
	@From DATETIME,
  @To   DATETIME
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[MachineId],
	[Notes],
	[UserId],
	ProcessTypeId,
	[ScheduledEndTime],
	[ScheduledStartTime],
	[StartTime],
	[StopTime],
	[RowVersion]
FROM
	[job].[SetupProcesses]
WHERE 
  ScheduledStartTime BETWEEN @From AND @To
--endregion
GO