SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[OperatorPunchesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[OperatorPunchesGetAll]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[OperatorPunchesGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[OperatorId],
	[PunchTime],
	[PunchTypeId],
	[RowVersion]
FROM
	[job].[OperatorPunches]

--endregion

GO