SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [job].[JobsGetByUserID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CLIENT_ID int;
	SELECT @CLIENT_ID = USER_CLIENT_ID FROM dbo.Users WHERE USER_USERID = @ID;

	DECLARE @IS_VENDOR int;
	SELECT @IS_VENDOR = CLIENT_VENDOR FROM dbo.Clients WHERE CLIENT_ID = @CLIENT_ID;

	SELECT
		JOB_ID
		, JOB_ACCESSIBILITYLEVEL
		, JOB_CLIENTID
		, JOB_CREATED
		, JOB_CREATEDBYID
		, JOB_DESCRIPTION
      , JOB_INSTRUCTIONS
      , JOB_PASTJOBID
		, JOB_NAME		
    , j.JOB_COMMENTTHREADID
		, JOB_ROWVERSION
	FROM
		[job].[Jobs] AS j
		INNER JOIN [dbo].[Users] AS u
			ON j.JOB_CREATEDBYID = u.USER_USERID
		INNER JOIN [dbo].Relationships AS r
			ON r.RELATIONSHIP_USERID = @ID
				AND r.RELATIONSHIP_CLIENTID = j.JOB_CLIENTID
	WHERE
		@IS_VENDOR = 0 OR (
			u.USER_CLIENT_ID = @CLIENT_ID
			OR j.JOB_CLIENTID = @CLIENT_ID
		);

	--WITH CTE 
	--(
	--	CLIENT_ID
	--)
	--AS
	--(
	--	(SELECT c.CLIENT_ID
	--	FROM [dbo].[Clients] AS c
	--		INNER JOIN [dbo].[Relationships] AS r
	--			ON c.CLIENT_ID = r.RELATIONSHIP_CLIENTID
	--	WHERE 
	--		c.CLIENT_PARENTID IS NULL
	--		AND r.RELATIONSHIP_USERID = @ID

	--		UNION
		
	--	SELECT 
	--		c.CLIENT_ID
	--	FROM [dbo].[Clients] AS c
	--		INNER JOIN [dbo].[Users] AS u
	--			ON c.CLIENT_ID = u.USER_CLIENT_ID
	--	WHERE 
	--		u.USER_USERID = @ID
	--	)
			
	--	UNION ALL

	--	SELECT 
	--		c.CLIENT_ID
	--	FROM [dbo].[Clients] AS c
	--		INNER JOIN [dbo].[Relationships] AS r
	--			ON c.CLIENT_ID = r.RELATIONSHIP_CLIENTID
	--		INNER JOIN CTE
	--			ON CTE.CLIENT_ID = c.CLIENT_PARENTID
	--	WHERE 
	--		c.CLIENT_PARENTID IS NOT NULL
	--		AND r.RELATIONSHIP_USERID = @ID
	--)
 --   SELECT
	--	JOB_ID
	--	, JOB_ACCESSIBILITYLEVEL
	--	, JOB_CLIENTID
	--	, JOB_CREATED
	--	, JOB_CREATEDBYID
	--	, JOB_DESCRIPTION
 --     , JOB_INSTRUCTIONS
 --     , JOB_PASTJOBID
	--	, JOB_NAME		
	--	, JOB_ROWVERSION
	--FROM
	--	[job].[Jobs] AS j
	--	INNER JOIN CTE
	--		ON j.JOB_CLIENTID = CTE.CLIENT_ID
	--ORDER BY
	--	JOB_ID;
END
GO