SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingProductionProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingProductionProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingProductionProcessGroupInsert]
	@Processid int,
	@Affixingitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[AffixingProductionProcessGroups] (
	[ProcessId],
	[AffixingItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Affixingitemid
)

--endregion

GO