SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[PersonalizationProductionProcessGroupUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[PersonalizationProductionProcessGroupUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[PersonalizationProductionProcessGroupUpdate]
@Version				timestamp,
	@Id int,
	@Processid int,
	@Insertionpersonalizationitemid int
    
AS

SET NOCOUNT ON

UPDATE [job].[PersonalizationProductionProcessGroups] SET
	[ProcessId] = @Processid,
	[InsertionPersonalizationItemId] = @Insertionpersonalizationitemid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO