SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[FoldingItemCutInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldingItemCutInsert]
-- Date Generated: Monday, February 22, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldingItemCutInsert]
	@Baseline int,
	@Cuttype int,
	@Foldingitemid int,
	@Measurement decimal(7, 4)

AS

SET NOCOUNT ON

INSERT INTO [job].[FoldingItemCuts] (
	[Baseline],
	[CutType],
	[FoldingItemId],
	[Measurement]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Baseline,
	@Cuttype,
	@Foldingitemid,
	@Measurement
)

--endregion

GO