SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[FoldUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldUpdate]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldUpdate]
@Version				timestamp,
	@Id int,
	@Baselinetypeid int,
	@Distance decimal(7, 4),
	@Foldingitemid INT,
  @FoldNumber INT
    
AS

SET NOCOUNT ON

UPDATE [job].[Folds] SET
	[BaselineTypeId] = @Baselinetypeid,
	[Distance] = @Distance,
	[FoldingItemId] = @Foldingitemid,
  [FoldNumber] = @FoldNumber
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO