SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingPersonalizationSetupProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPersonalizationSetupProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPersonalizationSetupProcessGroupInsert]
	@Affixingpersonalizationsetupprocessid int,
	@Affixingpersonalizationitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[AffixingPersonalizationSetupProcessGroups] (
	[AffixingPersonalizationSetupProcessId],
	[AffixingPersonalizationItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Affixingpersonalizationsetupprocessid,
	@Affixingpersonalizationitemid
)

--endregion

GO