SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingPersonalizationProductionProcessGroupUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPersonalizationProductionProcessGroupUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPersonalizationProductionProcessGroupUpdate]
@Version				timestamp,
	@Id int,
	@Processid int,
	@Affixingpersonalizationitemid int
    
AS

SET NOCOUNT ON

UPDATE [job].[AffixingPersonalizationProductionProcessGroups] SET
	[ProcessId] = @Processid,
	[AffixingPersonalizationItemId] = @Affixingpersonalizationitemid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO