SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SeedItemInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SeedItemInsert]
-- Date Generated: Tuesday, February 23, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SeedItemInsert]
	@Copies int,
	@Fileid int,
	@Fmiseed bit,
	@Instructions varchar(max),
	@Kitid int,
	@Separate bit

AS

SET NOCOUNT ON

INSERT INTO [job].[SeedItems] (
	[Copies],
	[FileId],
	[FmiSeed],
	[Instructions],
	[KitId],
	[Separate]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Copies,
	@Fileid,
	@Fmiseed,
	@Instructions,
	@Kitid,
	@Separate
)

--endregion

GO