SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [job].[JobsGet]
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		JOB_ID
		, JOB_ACCESSIBILITYLEVEL
		, JOB_CLIENTID
		, JOB_CREATED
		, JOB_CREATEDBYID
		, JOB_DESCRIPTION
      , JOB_INSTRUCTIONS
      , JOB_PASTJOBID
		, JOB_NAME		
      , JOB_COMMENTTHREADID
		, JOB_ROWVERSION
	FROM
		[job].[Jobs]
	ORDER BY
		JOB_ID;
END
GO