SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region job.[CuttingItemInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: job.[CuttingItemInsert]
-- Date Generated: Monday, January 18, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CuttingItemInsert]
	@Finalcount int,
	@Finalheight decimal(8, 4),
	@Finalwidth decimal(8, 4),
	@Locationtype int,
  @StartTime DATETIME = NULL,
  @EndTime DATETIME = NULL,
	@Itemid int

AS

SET NOCOUNT ON

INSERT INTO job.[CuttingItems] (
	[FinalCount],
	[FinalHeight],
	[FinalWidth],
	[LocationType],
  StartTime,
  EndTime,
	[ItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Finalcount,
	@Finalheight,
	@Finalwidth,
	@Locationtype,
  @StartTime,
  @EndTime,
	@Itemid
)

--endregion
GO