SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[KitSetupProcessGroupsGetByKitId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[KitSetupProcessGroupsGetByKitId]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[KitSetupProcessGroupsGetByKitId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ProcessId],
	[KitId],
	[RowVersion]
FROM
	[job].[KitSetupProcessGroups]
WHERE
	[KitId] = @Id

--endregion

GO