SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[FoldsGetByBaselineTypeId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldsGetByBaselineTypeId]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldsGetByBaselineTypeId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[BaselineTypeId],
	[Distance],
	[FoldingItemId],
  FoldNumber,
	[Rowversion]
FROM
	[job].[Folds]
WHERE
	[BaselineTypeId] = @Id

--endregion

GO