SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[FoldDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldDeleteById]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [job].[Folds]
WHERE
	[Id] = @Id

--endregion

GO