SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[PersonalizationItemUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[PersonalizationItemUpdate]
-- Date Generated: Thursday, January 14, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InsertionPersonalizationItemUpdate]
	@Id int,
  @DataType INT, 
	@Description varchar(max),
	@Feedid int,
	@Indicia varchar(100),
	@InsertItemId int,
	@LaserTypeId int,
	@Layoutid int,
	@Modeid int,
	@Orientationid int,
  @Rundirectionid int,
  @StartTime DATETIME = NULL,
  @EndTime DATETIME = NULL,
	@Targetid int,
	@Version timestamp
AS

SET NOCOUNT ON

UPDATE job.[InsertionPersonalizationItem] SET
  DataType = @DataType,
	[Description] = @Description,
	[FeedId] = @Feedid,
	[Indicia] = @Indicia,
	[InsertItemId] = @InsertItemId,
	[LaserTypeId] = @LaserTypeId,
	[LayoutId] = @Layoutid,
	[ModeId] = @Modeid,
	[OrientationId] = @Orientationid,
  [RundirectionId] = @Rundirectionid,
  StartTime = @StartTime,
  EndTime = @EndTime,
	[TargetId] = @Targetid
	OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion
GO