SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[InstructionInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[InstructionInsert]
-- Date Generated: Monday, January 18, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InstructionInsert]
	@Insertionitemid int,
	@Instructions varchar(max),
	@Type int

AS

SET NOCOUNT ON

INSERT INTO [job].[Instructions] (
	[InsertionItemId],
	[Instructions],
	[Type]
) 
OUTPUT		
		inserted.Id AS ID
VALUES (
	@Insertionitemid,
	@Instructions,
	@Type
)

--endregion

GO