SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessesGetBySetupProcessTypeId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessesGetBySetupProcessTypeId]
-- Date Generated: Friday, August 26, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessesGetBySetupProcessTypeId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[UserId],
	[StartTime],
	[StopTime],
	[SetupProcessTypeId],
	[Notes],
	[MachineId],
	[RowVersion]
FROM
	[job].[SetupProcess]
WHERE
	[SetupProcessTypeId] = @Id

--endregion

GO