SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ProductionProcessGroupUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ProductionProcessGroupUpdate]
-- Date Generated: Friday, August 26, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ProductionProcessGroupUpdate]
@Version				timestamp,
	@Id int,
	@Insertionitemid int,
	@Productionprocessid int
    
AS

SET NOCOUNT ON

UPDATE [job].[ProductionProcessGroups] SET
	[InsertionItemId] = @Insertionitemid,
	[ProductionProcessId] = @Productionprocessid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO