SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[PersonalizationSetupProcessGroupsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[PersonalizationSetupProcessGroupsGetAll]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[PersonalizationSetupProcessGroupsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ProcessId],
	[InsertionPersonalizationItemId],
	[RowVersion]
FROM
	[job].[PersonalizationSetupProcessGroups]

--endregion

GO