SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ClientSageCustomerUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ClientSageCustomerUpdate]
-- Date Generated: Friday, August 12, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ClientSageCustomerUpdate]
	@Id int,
	@Clientid int,
	@Sagecustomerid varchar(10)
    
AS

SET NOCOUNT ON

UPDATE [job].[ClientSageCustomers] SET
	[ClientId] = @Clientid,
	[SageCustomerId] = @Sagecustomerid
    OUTPUT inserted.Id AS [ID]
WHERE
	[Id] = @Id

--endregion

GO