SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessUpdate]
-- Date Generated: Friday, September 9, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessUpdate]
@Version				timestamp,
	@Id int,
	@Userid int,
	@Machineid int,
	@Notes varchar(5000),
	@Processtypeid int,
	@Scheduledendtime datetime,
	@Scheduledstarttime datetime,
	@Starttime datetime,
	@Stoptime datetime
    
AS

SET NOCOUNT ON

UPDATE [job].[SetupProcesses] SET
	[UserId] = @Userid,
	[MachineId] = @Machineid,
	[Notes] = @Notes,
	[ProcessTypeId] = @Processtypeid,
	[ScheduledEndTime] = @Scheduledendtime,
	[ScheduledStartTime] = @Scheduledstarttime,
	[StartTime] = @Starttime,
	[StopTime] = @Stoptime
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO