SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[InsertionProductionProcessGroupDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[InsertionProductionProcessGroupDeleteById]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InsertionProductionProcessGroupDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [job].[InsertionProductionProcessGroups]
WHERE
	[Id] = @Id

--endregion

GO