SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SeedItemGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SeedItemGetById]
-- Date Generated: Tuesday, February 23, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SeedItemGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Copies],
	[FileId],
	[FmiSeed],
	[Instructions],
	[KitId],
	[Separate],
	[RowVersion]
FROM
	[job].[SeedItems]
WHERE
	[Id] = @Id

--endregion

GO