SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[KitSetupProcessGroupUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[KitSetupProcessGroupUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[KitSetupProcessGroupUpdate]
@Version				timestamp,
	@Id int,
	@Processid int,
	@Kitid int
    
AS

SET NOCOUNT ON

UPDATE [job].[KitSetupProcessGroups] SET
	[ProcessId] = @Processid,
	[KitId] = @Kitid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO