SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[FoldInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldInsert]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldInsert]
	@Baselinetypeid int,
	@Distance decimal(7, 4),
	@Foldingitemid INT,
  @FoldNumber INT

AS

SET NOCOUNT ON

INSERT INTO [job].[Folds] (
	[BaselineTypeId],
	[Distance],
	[FoldingItemId],
  FoldNumber

) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Baselinetypeid,
	@Distance,
	@Foldingitemid,
  @FoldNumber
)

--endregion

GO