SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[DataSetupProcessGroupGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[DataSetupProcessGroupGetById]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[DataSetupProcessGroupGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ProcessId],
	[DataProcessingItemId],
	[RowVersion]
FROM
	[job].[DataSetupProcessGroups]
WHERE
	[Id] = @Id

--endregion

GO