SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [job].[ServiceTypeGetByID] 
	@ID int
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		SERVICETYPE_ID		
		, SERVICETYPE_NAME
		, SERVICETYPE_ROWVERSION 
	FROM 
		[dbo].[ServiceTypes]
	WHERE 
		SERVICETYPE_ID = @ID;
END
GO