SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[OperatorPunchInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[OperatorPunchInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[OperatorPunchInsert]
	@Operatorid int,
	@Punchtime datetime,
	@Punchtypeid int

AS

SET NOCOUNT ON

INSERT INTO [job].[OperatorPunches] (
	[OperatorId],
	[PunchTime],
	[PunchTypeId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Operatorid,
	@Punchtime,
	@Punchtypeid
)

--endregion

GO