SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[CutsGetByCuttingItemId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[CutsGetByCuttingItemId]
-- Date Generated: Tuesday, March 15, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CutsGetByCuttingItemId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[CuttingItemId],
	[CutTypeId],
	[BaselineTypeId],
	[Measurement],
	[Rowversion]
FROM
	[job].[Cuts]
WHERE
	[CuttingItemId] = @Id

--endregion

GO