SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[InstructionUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[InstructionUpdate]
-- Date Generated: Monday, January 18, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InstructionUpdate]
	@Id int,
	@Insertionitemid int,
	@Instructions varchar(max),
	@Type int
AS

SET NOCOUNT ON

UPDATE [job].[Instructions] SET
	[InsertionItemId] = @Insertionitemid,
	[Instructions] = @Instructions,
	[Type] = @Type
WHERE
	[Id] = @Id

--endregion

GO