SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [dbo].[PersonalizationItemsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[PersonalizationItemsGetAll]
-- Date Generated: Thursday, January 14, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[InsertionPersonalizationItemsGetAllReady]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	ipi.[Id],
  DataType,
	ipi.[Description],
	[FeedId],
	[Indicia],
	[InsertItemId],
	[LaserTypeId],
	[LayoutId],
	[ModeId],
	[OrientationId],
  [RunDirectionId],
  ipi.StartTime,
  ipi.EndTime,
	[TargetId],
	ipi.[Rowversion]
FROM
	job.[InsertionPersonalizationItem] ipi
  INNER JOIN job.InsertionItems ii ON ii.Id = ipi.InsertItemId
  INNER JOIN job.Kits AS k ON k.Id = ii.KitId
  INNER JOIN job.KitSetupProcessGroups kspg ON k.Id = kspg.KitId
  INNER JOIN job.ProductionProcesses sp ON kspg.ProcessId = sp.Id
  WHERE sp.StopTime IS NOT NULL

--endregion
GO