SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [job].[JobsGetByClientIDByCreatedDateRange]
	@ID		int
	, @From	datetime = NULL
	, @To	datetime = NULL
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		JOB_ID
		, JOB_ACCESSIBILITYLEVEL
		, JOB_CLIENTID
		, JOB_CREATED
		, JOB_CREATEDBYID
		, JOB_DESCRIPTION
      , JOB_INSTRUCTIONS
      , JOB_PASTJOBID
		, JOB_NAME		
      , JOB_COMMENTTHREADID
		, JOB_ROWVERSION
	FROM
		[job].[Jobs]
	WHERE
		JOB_CLIENTID = @ID
		AND (@From IS NULL OR JOB_CREATED >= @From)
		--AND (@To IS NULL OR JOB_CREATED <= @To)
	ORDER BY
		JOB_ID;
END
GO