SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[CuttingProductionSchedulesGetByProcessGroupId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[CuttingProductionSchedulesGetByProcessGroupId]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CuttingProductionSchedulesGetByProcessGroupId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ScheduledStartTime],
	[ExpectedEndTime],
	[ProcessGroupId],
	[Notes],
	[RowVersion]
FROM
	[job].[CuttingProductionSchedule]
WHERE
	[ProcessGroupId] = @Id

--endregion

GO