SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[OperatorUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[OperatorUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[OperatorUpdate]
@Version				timestamp,
	@Id int,
	@Operatorname varchar(200),
	@Operatortypeid int
    
AS

SET NOCOUNT ON

UPDATE [job].[Operators] SET
	[OperatorName] = @Operatorname,
	[OperatorTypeId] = @Operatortypeid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO