SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[FoldsGetByFoldingItemId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldsGetByFoldingItemId]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldsGetByFoldingItemId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[BaselineTypeId],
	[Distance],
	[FoldingItemId],
  FoldNumber,
	[Rowversion]
FROM
	[job].[Folds]
WHERE
	[FoldingItemId] = @Id

--endregion

GO