SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[TemplatesGetByClientId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[TemplatesGetByClientId]
-- Date Generated: Tuesday, March 15, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[TemplatesGetByUserId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ClientId],
	[Created],
	[CreatedById],
	[Json],
	[Name],
	[TemplateTypeId],
  [RowVersion]
FROM
	[job].[Templates]
WHERE
	[CreatedById] = @Id

--endregion
GO