SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [job].[ServiceTypesGet] 
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		SERVICETYPE_ID		
		, SERVICETYPE_NAME
		, SERVICETYPE_ROWVERSION 
	FROM 
		[dbo].[ServiceTypes]
	ORDER BY
		SERVICETYPE_ID;
END
GO