SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[CutsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[CutsGetAll]
-- Date Generated: Tuesday, March 15, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[CutsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[CuttingItemId],
	[CutTypeId],
	[BaselineTypeId],
	[Measurement],
	[Rowversion]
FROM
	[job].[Cuts]

--endregion

GO