SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[MachinesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[MachinesGetAll]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[MachinesGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[MachineName],
	[MachineTypeId],
	[MachineLocationId],
	[RowVersion]
FROM
	[job].[Machines]

--endregion

GO