SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessGroupsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessGroupsGetAll]
-- Date Generated: Friday, August 26, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessGroupsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[SetupProcessId],
	[KitId],
	[RowVersion]
FROM
	[job].[SetupProcessGroups]

--endregion

GO