SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[PersonalizationSetupProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[PersonalizationSetupProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[PersonalizationSetupProcessGroupInsert]
	@Processid int,
	@Insertionpersonalizationitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[PersonalizationSetupProcessGroups] (
	[ProcessId],
	[InsertionPersonalizationItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Insertionpersonalizationitemid
)

--endregion

GO