SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[SetupProcessesGetByProcessTypeId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SetupProcessesGetByProcessTypeId]
-- Date Generated: Friday, September 9, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SetupProcessesGetByProcessTypeId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[UserId],
	[MachineId],
	[Notes],
	[ProcessTypeId],
	[ScheduledEndTime],
	[ScheduledStartTime],
	[StartTime],
	[StopTime],
	[RowVersion]
FROM
	[job].[SetupProcesses]
WHERE
	[ProcessTypeId] = @Id

--endregion

GO