SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[AffixingProductionProcessGroupsGetByAffixingItemId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingProductionProcessGroupsGetByAffixingItemId]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingProductionProcessGroupsGetByAffixingItemId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ProcessId],
	[AffixingItemId],
	[RowVersion]
FROM
	[job].[AffixingProductionProcessGroups]
WHERE
	[AffixingItemId] = @Id

--endregion

GO