SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[MachineInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[MachineInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[MachineInsert]
	@Machinename varchar(50),
	@Machinetypeid int,
	@Machinelocationid int

AS

SET NOCOUNT ON

INSERT INTO [job].[Machines] (
	[MachineName],
	[MachineTypeId],
	[MachineLocationId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Machinename,
	@Machinetypeid,
	@Machinelocationid
)

--endregion

GO