SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[FoldsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[FoldsGetAll]
-- Date Generated: Friday, March 11, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[FoldsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[BaselineTypeId],
	[Distance],
	[FoldingItemId],
  FoldNumber,
	[Rowversion]
FROM
	[job].[Folds]

--endregion

GO