SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[ClientSageCustomerInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[ClientSageCustomerInsert]
-- Date Generated: Friday, August 12, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[ClientSageCustomerInsert]
	@Clientid int,
	@Sagecustomerid varchar(10)

AS

SET NOCOUNT ON

INSERT INTO [job].[ClientSageCustomers] (
	[ClientId],
	[SageCustomerId]
) 
OUTPUT		
		inserted.Id AS ID
VALUES (
	@Clientid,
	@Sagecustomerid
)

--endregion

GO