SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[DataSetupProcessGroupInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[DataSetupProcessGroupInsert]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[DataSetupProcessGroupInsert]
	@Processid int,
	@Dataprocessingitemid int

AS

SET NOCOUNT ON

INSERT INTO [job].[DataSetupProcessGroups] (
	[ProcessId],
	[DataProcessingItemId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Processid,
	@Dataprocessingitemid
)

--endregion

GO