SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[OperatorPunchUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[OperatorPunchUpdate]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[OperatorPunchUpdate]
@Version				timestamp,
	@Id int,
	@Operatorid int,
	@Punchtime datetime,
	@Punchtypeid int
    
AS

SET NOCOUNT ON

UPDATE [job].[OperatorPunches] SET
	[OperatorId] = @Operatorid,
	[PunchTime] = @Punchtime,
	[PunchTypeId] = @Punchtypeid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO