SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [job].[DataSetupProcessGroupsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[DataSetupProcessGroupsGetAll]
-- Date Generated: Thursday, September 1, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[DataSetupProcessGroupsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[ProcessId],
	[DataProcessingItemId],
	[RowVersion]
FROM
	[job].[DataSetupProcessGroups]

--endregion

GO