SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[SignoffItemGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[SignoffItemGetById]
-- Date Generated: Tuesday, February 23, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[SignoffItemGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Copies],
  Instructions,
	[Random],
	[KitId],
	[Quantity],
  SoDueDate,
	[RowVersion]
FROM
	[job].[SignoffItems]
WHERE
	[Id] = @Id

--endregion

GO