SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[AffixingPersonalizationItemsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[AffixingPersonalizationItemsGetAll]
-- Date Generated: Monday, February 22, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[AffixingPersonalizationItemsGetAllReady]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	api.[Id],
  DataType,
	api.[Description],
	[FeedId],
	[Indicia],
	[AffixingItemId],
	[LaserTypeId],
	[LayoutId],
	[ModeId],
	[OrientationId],
	[RunDirectionId],
  api.StartTime,
  api.EndTime,
	[TargetId],
	api.[RowVersion]
FROM
	[job].[AffixingPersonalizationItem] api
  INNER JOIN job.AffixingItems ai ON ai.Id = api.AffixingItemId
  INNER JOIN job.InsertionItems ii ON ii.Id = ai.InsertItemId
  INNER JOIN job.Kits AS k ON k.Id = ii.KitId
  INNER JOIN job.KitSetupProcessGroups kspg ON k.Id = kspg.KitId
  INNER JOIN job.ProductionProcesses sp ON kspg.ProcessId = sp.Id
  WHERE sp.StopTime IS NOT NULL

--endregion
GO