SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[KitsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[KitsGetAll]
-- Date Generated: Friday, January 8, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[JobsGetAllPending]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT DISTINCT
    JOB_ID
		, JOB_ACCESSIBILITYLEVEL
		, JOB_CLIENTID
		, JOB_CREATED
		, JOB_CREATEDBYID
		, JOB_DESCRIPTION
    , JOB_INSTRUCTIONS
    , JOB_PASTJOBID
		, JOB_NAME		
  , JOB_COMMENTTHREADID
		, JOB_ROWVERSION
	FROM
		[job].[Jobs] j
  LEFT JOIN job.Kits k ON k.JobId = j.JOB_ID
	LEFT JOIN job.KitSetupProcessGroups kspg ON k.Id = kspg.KitId
  LEFT JOIN job.ProductionProcesses sp ON kspg.ProcessId = sp.Id
  WHERE sp.StopTime IS NULL AND k.DropDate < dateadd(dd,7,getdate())

--endregion
GO