SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [job].[TemplateUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [job].[TemplateUpdate]
-- Date Generated: Tuesday, March 15, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [job].[TemplateUpdate]
	@Id int,
	@Clientid int,
	@Created datetime,
	@Createdbyid int,
	@Json nvarchar(max),
	@Name varchar(100),
	@Templatetypeid INT,
	@Version				timestamp
    
AS

SET NOCOUNT ON

UPDATE [job].[Templates] SET
	[ClientId] = @Clientid,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[Json] = @Json,
	[Name] = @Name,
	[TemplateTypeId] = @Templatetypeid
    OUTPUT inserted.ID AS ID, inserted.[RowVersion] AS [VERSION]
WHERE
	[Id] = @Id AND
		([ROWVERSION] = @Version);


--endregion

GO