SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[GetWorkflowParametersAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[GetWorkflowParametersAll]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[GetWorkflowParametersAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[WORKFLOWPARAM_ID],
	[WORKFLOWPARAM_INPUTFILENAME],
	[WORKFLOWPARAM_NUPCOUNTX],
	[WORKFLOWPARAM_NUPCOUNTY],
	[WORKFLOWPARAM_NUPOFFSETX],
	[WORKFLOWPARAM_NUPOFFSETY],
	[WORKFLOWPARAM_DUPLEXTYPE],
	[WORKFLOWPARAM_USERANGEFORPROD],
	[WORKFLOWPARAM_STARTREC],
	[WORKFLOWPARAM_ENDREC],
	[WORKFLOWPARAM_NUMBERUP]
FROM
	[laser].[WorkflowParameters]

--endregion
GO