SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[DeleteReportsByJobid]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[DeleteReportsByJobid]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[DeleteReportsByJobid]
	@JobId int
AS

SET NOCOUNT ON

DELETE FROM [laser].[Reports]
WHERE
	[REPORT_JOBID] = @JobId
GO