SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[GetJobConfig]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[GetJobConfig]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[GetJobConfig]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[JOBCONFIG_ID],
	[JOBCONFIG_REQUESTEDSTARTPAGE],
	[JOBCONFIG_REQUESTEDENDPAGE],
	[JOBCONFIG_REQUESTEDPRINTTOEND],
	[JOBCONFIG_COPYCOUNT],
	[JOBCONFIG_COLLATE],
	[JOBCONFIG_PRINTUSERGROUP1],
	[JOBCONFIG_PRINTUSERGROUP2],
	[JOBCONFIG_PRINTUSERGROUP3],
	[JOBCONFIG_OFFSETX],
	[JOBCONFIG_OFFSETY],
	[JOBCONFIG_SCALEX],
	[JOBCONFIG_SCALEY],
	[JOBCONFIG_PRINTERRESOLUTION]
FROM
	[laser].[JobConfigs]
WHERE
	[JOBCONFIG_ID] = @Id

--endregion
GO