SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[UpdateWorkflowParameter]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[UpdateWorkflowParameter]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[UpdateWorkflowParameter]
	@Id int,
	@Inputfilename nvarchar(300),
	@Nupcountx int,
	@Nupcounty int,
	@Nupoffsetx float,
	@Nupoffsety float,
	@Duplextype int,
	@Userangeforprod bit,
	@Startrec int,
	@Endrec int,
	@Numberup int
AS

SET NOCOUNT ON

UPDATE [laser].[WorkflowParameters] SET
	[WORKFLOWPARAM_INPUTFILENAME] = @Inputfilename,
	[WORKFLOWPARAM_NUPCOUNTX] = @Nupcountx,
	[WORKFLOWPARAM_NUPCOUNTY] = @Nupcounty,
	[WORKFLOWPARAM_NUPOFFSETX] = @Nupoffsetx,
	[WORKFLOWPARAM_NUPOFFSETY] = @Nupoffsety,
	[WORKFLOWPARAM_DUPLEXTYPE] = @Duplextype,
	[WORKFLOWPARAM_USERANGEFORPROD] = @Userangeforprod,
	[WORKFLOWPARAM_STARTREC] = @Startrec,
	[WORKFLOWPARAM_ENDREC] = @Endrec,
	[WORKFLOWPARAM_NUMBERUP] = @Numberup

WHERE
		[WORKFLOWPARAM_ID] = @Id
 

--endregion
GO