SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[DeleteReport]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[DeleteReport]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[DeleteReport]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [laser].[Reports]
WHERE
	[REPORT_ID] = @Id

--endregion
GO