SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[GetReportsByJobid]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[GetReportsByJobid]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[GetReportsByJobid]
	@JobId int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[REPORT_ID],
	[REPORT_TOTALPRINTEDSHEETS],
	[REPORT_TOTALPRINTEDPAGES],
	[REPORT_CLICKCOST],
	[REPORT_PRINTCOST],
	[REPORT_JOBSTARTED],
	[REPORT_JOBLASTFINISHED],
	[REPORT_RUNDURATION],
	[REPORT_PRINTERSUSED],
	[REPORT_JOBID],
	[REPORT_ROWVERSION]
FROM
	[laser].[Reports]
WHERE
	[REPORT_JOBID] = @JobId

--endregion
GO