SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[CreateWorkflowParameter]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[CreateWorkflowParameter]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[CreateWorkflowParameter]
	@Inputfilename nvarchar(300),
	@Nupcountx int,
	@Nupcounty int,
	@Nupoffsetx float,
	@Nupoffsety float,
	@Duplextype int,
	@Userangeforprod bit,
	@Startrec int,
	@Endrec int,
	@Numberup int,
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [laser].[WorkflowParameters] (
	[WORKFLOWPARAM_INPUTFILENAME],
	[WORKFLOWPARAM_NUPCOUNTX],
	[WORKFLOWPARAM_NUPCOUNTY],
	[WORKFLOWPARAM_NUPOFFSETX],
	[WORKFLOWPARAM_NUPOFFSETY],
	[WORKFLOWPARAM_DUPLEXTYPE],
	[WORKFLOWPARAM_USERANGEFORPROD],
	[WORKFLOWPARAM_STARTREC],
	[WORKFLOWPARAM_ENDREC],
	[WORKFLOWPARAM_NUMBERUP]
) 
OUTPUT inserted.WORKFLOWPARAM_ID AS ID
		
VALUES (
	@Inputfilename,
	@Nupcountx,
	@Nupcounty,
	@Nupoffsetx,
	@Nupoffsety,
	@Duplextype,
	@Userangeforprod,
	@Startrec,
	@Endrec,
	@Numberup
)

SET @Id = SCOPE_IDENTITY()

--endregion
GO