SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[DeleteLogsByJobconfigid]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[DeleteLogsByJobconfigid]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[DeleteLogsByJobconfigid]
	@Jobconfigid int
AS

SET NOCOUNT ON

DELETE FROM [laser].[Logs]
WHERE
	[LOG_JOBCONFIGID] = @Jobconfigid
GO