SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[CreateJobConfig]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[CreateJobConfig]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[CreateJobConfig]
	@Requestedstartpage int,
	@Requestedendpage int,
	@Requestedprinttoend bit,
	@Copycount int,
	@Collate bit,
	@Printusergroup1 bit,
	@Printusergroup2 bit,
	@Printusergroup3 bit,
	@Offsetx float,
	@Offsety float,
	@Scalex float,
	@Scaley float,
	@Printerresolution int,
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [laser].[JobConfigs] (
	[JOBCONFIG_REQUESTEDSTARTPAGE],
	[JOBCONFIG_REQUESTEDENDPAGE],
	[JOBCONFIG_REQUESTEDPRINTTOEND],
	[JOBCONFIG_COPYCOUNT],
	[JOBCONFIG_COLLATE],
	[JOBCONFIG_PRINTUSERGROUP1],
	[JOBCONFIG_PRINTUSERGROUP2],
	[JOBCONFIG_PRINTUSERGROUP3],
	[JOBCONFIG_OFFSETX],
	[JOBCONFIG_OFFSETY],
	[JOBCONFIG_SCALEX],
	[JOBCONFIG_SCALEY],
	[JOBCONFIG_PRINTERRESOLUTION]
) 
OUTPUT inserted.JOBCONFIG_ID AS ID
		
VALUES (
	@Requestedstartpage,
	@Requestedendpage,
	@Requestedprinttoend,
	@Copycount,
	@Collate,
	@Printusergroup1,
	@Printusergroup2,
	@Printusergroup3,
	@Offsetx,
	@Offsety,
	@Scalex,
	@Scaley,
	@Printerresolution
)

SET @Id = SCOPE_IDENTITY()

--endregion
GO