SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[DeleteLog]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[DeleteLog]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[DeleteLog]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [laser].[Logs]
WHERE
	[LOG_ID] = @Id

--endregion
GO