SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [laser].[UpdateReport]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [laser].[UpdateReport]
-- Date Generated: Thursday, April 30, 2015
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [laser].[UpdateReport]
	@Id int,
	@TotalPrintedSheets int,
	@TotalPrintedPages int,
	@ClickCost int,
	@PrintCost int,
	@JobStarted datetime,
	@JobLastFinished datetime,
	@RunDuration int,
	@PrintersUsed int,
	@JobId int,
	@Version timestamp
AS

SET NOCOUNT ON

UPDATE [laser].[Reports] SET
	[REPORT_TOTALPRINTEDSHEETS] = @TotalPrintedSheets,
	[REPORT_TOTALPRINTEDPAGES] = @TotalPrintedPages,
	[REPORT_CLICKCOST] = @ClickCost,
	[REPORT_PRINTCOST] = @PrintCost,
	[REPORT_JOBSTARTED] = @JobStarted,
	[REPORT_JOBLASTFINISHED] = @JobLastFinished,
	[REPORT_RUNDURATION] = @RunDuration,
	[REPORT_PRINTERSUSED] = @PrintersUsed,
	[REPORT_JOBID] = @JobId

WHERE
		[REPORT_ID] = @Id
 AND ([REPORT_ROWVERSION] = @Version)

--endregion
GO