SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [mail].[EventListenersGetByUserID]
	@ID			int
	, @Events	int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		EVENTLISTENER_ID		
		, EVENTLISTENER_EVENTS
		, EVENTLISTENER_USERID
		, EVENTLISTENER_ROWVERSION
	FROM
		[mail].[EventListeners]	
	WHERE
		EVENTLISTENER_USERID = @ID		
		AND (@Events & EVENTLISTENER_EVENTS > 0)
	ORDER BY
		EVENTLISTENER_ID;
END
GO