SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[RecipientListDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[RecipientListDeleteById]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[RecipientListDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [messaging].[RecipientLists]
WHERE
	[Id] = @Id

--endregion

GO