SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[CommentUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[CommentUpdate]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[CommentUpdate]
@Version				timestamp,
	@Id int,
	@Content varchar(max),
	@Created datetime,
	@Createdbyadmin bit,
	@Createdbycurrentuser bit,
	@Createdbyid int,
	@Creator int,
	@Deleted bit,
	@Fileid int,
	@Filename varchar(5000),
	@Filesource varbinary(max),
	@Filemimetype varchar(1000),
	@Fileurl varchar(1000),
	@Fullname varchar(1000),
	@Isnew bit,
	@Modified datetime,
	@Pings varchar(max),
	@Parent int,
	@Profileurl varchar(500),
	@Profilepictureurl varchar(500),
	@Threadid int,
	@Upvotecount int,
	@Userhasupvoted bit
    
AS

SET NOCOUNT ON

UPDATE [messaging].[Comments] SET
	[Content] = @Content,
	[Created] = @Created,
	[CreatedByAdmin] = @Createdbyadmin,
	[CreatedByCurrentUser] = @Createdbycurrentuser,
	[CreatedById] = @Createdbyid,
	[Creator] = @Creator,
	[Deleted] = @Deleted,
	[FileId] = @Fileid,
	[FileName] = @Filename,
	[FileSource] = @Filesource,
	[FileMimeType] = @Filemimetype,
	[FileUrl] = @Fileurl,
	[Fullname] = @Fullname,
	[IsNew] = @Isnew,
	[Modified] = @Modified,
	[Pings] = @Pings,
	[Parent] = @Parent,
	[ProfileUrl] = @Profileurl,
	[ProfilePictureUrl] = @Profilepictureurl,
	[ThreadId] = @Threadid,
	[UpVoteCount] = @Upvotecount,
	[UserHasUpvoted] = @Userhasupvoted
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO