SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[InstantMessagesGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[InstantMessagesGetAll]
-- Date Generated: Tuesday, June 6, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[InstantMessagesGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Created],
	[CreatedById],
	[IsRead],
	[Message],
	[RecipientUserId],
	[SenderUserId],
	[RowVersion]
FROM
	[messaging].[InstantMessages]

--endregion

GO