SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [messaging].[PrivateMessagesGetByRecipientListIdPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[PrivateMessagesGetByRecipientListIdPaged]
-- Date Generated: Wednesday, June 7, 2017
------------------------------------------------------------------------------------------------------------------------


CREATE PROCEDURE [messaging].[PrivateMessagesGetByRecipientListIdPaged]
	@Id int,
    @PageNumber INT = 1,
    @PageSize   INT = 10
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

;WITH pg AS
  (
    SELECT main.Id
      FROM [messaging].[PrivateMessages] main
      INNER JOIN messaging.RecipientLists rl ON rl.MessageId = main.Id
      WHERE 	rl.Id = @Id AND (main.IsTrashRecipient IS NULL OR main.IsTrashRecipient = 0)

      ORDER BY Id DESC
      OFFSET @PageSize * (@PageNumber - 1) ROWS
      FETCH NEXT @PageSize ROWS ONLY
  )
  SELECT 	
	[sub].[Id],
	[sub].[AttachmentListId],
	[sub].[Created],
	[sub].[CreatedById],
	[sub].[IsRead],
	[sub].[IsStarredRecipient],
	[sub].[IsStarredSender],
	[sub].[IsTrashRecipient],
	[sub].[IsTrashSender],
	[sub].[Message],
	[sub].[Modified],
	[sub].[ParentId],
	[sub].[RecipientListId],
	[sub].[SenderUserId],
	[sub].[SentDate],
	[sub].[Subject],
	[sub].[TrashedDateRecipient],
	[sub].[TrashedDateSender],
	[sub].[RowVersion]
  FROM [messaging].[PrivateMessages] sub
  WHERE EXISTS (SELECT 1 FROM pg WHERE pg.Id = sub.Id)
  ORDER BY sub.Id DESC OPTION (RECOMPILE);
--endregion

GO