SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [messaging].[InstantMessagesGetBySenderUserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[InstantMessagesGetBySenderUserId]
-- Date Generated: Tuesday, June 6, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[InstantMessagesGetBySenderUserId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Created],
	[CreatedById],
	[IsRead],
	[Message],
	[RecipientUserId],
	[SenderUserId],
	[RowVersion]
FROM
	[messaging].[InstantMessages]
WHERE
	[SenderUserId] = @Id
ORDER BY Created
--endregion

GO