SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[CommentThreadGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[CommentThreadGetById]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[CommentThreadGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id]
FROM
	[messaging].[CommentThreads]
WHERE
	[Id] = @Id

--endregion

GO