SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [messaging].[PrivateMessagesGetByRecipientListId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[PrivateMessagesGetByRecipientListId]
-- Date Generated: Wednesday, June 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[PrivateMessagesGetStarredByRecipientUserIdPaged]
	@Id int,
    @PageNumber INT = 1,
    @PageSize   INT = 10
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

  SELECT 	
	[sub].[Id],
	[sub].[AttachmentListId],
	[sub].[Created],
	[sub].[CreatedById],
	[sub].[IsRead],
	[sub].[IsStarredRecipient],
	[sub].[IsStarredSender],
	[sub].[IsTrashRecipient],
	[sub].[IsTrashSender],
	[sub].[Message],
	[sub].[Modified],
	[sub].[ParentId],
	[sub].[RecipientListId],
	[sub].[SenderUserId],
	[sub].[SentDate],
	[sub].[Subject],
	[sub].[TrashedDateRecipient],
	[sub].[TrashedDateSender],
	[sub].[RowVersion]
  FROM [messaging].[PrivateMessages] sub
  INNER JOIN messaging.RecipientLists rl ON rl.MessageId = sub.Id
  WHERE 	rl.RecipientUserId = @Id AND (sub.IsStarredRecipient = 1) AND (sub.IsTrashRecipient IS NULL OR sub.IsTrashRecipient = 0)
  ORDER BY sub.Id DESC 
  OFFSET @PageSize * (@PageNumber - 1) ROWS
      FETCH NEXT @PageSize ROWS ONLY;

SELECT COUNT(pm.Id) AS TotalRows FROM messaging.PrivateMessages pm
  INNER JOIN messaging.RecipientLists rl2 ON rl2.MessageId = pm.Id
      WHERE 	rl2.RecipientUserId = @Id AND (pm.IsStarredRecipient = 1) AND (pm.IsTrashRecipient IS NULL OR pm.IsTrashRecipient = 0)
--endregion
GO