SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[MessageFileCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[MessageFileCreate]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[MessageFileCreate]
	@Contenttypeid int,
	@Compressed bit,
	@Data varbinary(max),
	@Description nvarchar(200),
	@Name nvarchar(2000),
	@Size bigint,
	@Typeid int,
	@Uploaded datetime

AS

SET NOCOUNT ON

INSERT INTO [messaging].[MessageFiles] (
	[ContentTypeId],
	[Compressed],
	[Data],
	[Description],
	[Name],
	[Size],
	[TypeId],
	[Uploaded]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Contenttypeid,
	@Compressed,
	@Data,
	@Description,
	@Name,
	@Size,
	@Typeid,
	@Uploaded
)

--endregion

GO