SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[InstantMessageGetById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[InstantMessageGetById]
-- Date Generated: Tuesday, June 6, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[InstantMessageGetById]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Created],
	[CreatedById],
	[IsRead],
	[Message],
	[RecipientUserId],
	[SenderUserId],
	[RowVersion]
FROM
	[messaging].[InstantMessages]
WHERE
	[Id] = @Id

--endregion

GO