SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [messaging].[PrivateMessagesGetByRecipientListId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[PrivateMessagesGetByRecipientListId]
-- Date Generated: Wednesday, June 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[PrivateMessagesGetCountByRecipientUserId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT Distinct
COUNT(	pm.[Id])

FROM
	[messaging].[PrivateMessages] AS pm
  INNER JOIN messaging.RecipientLists rl ON rl.MessageId = pm.Id
WHERE
  rl.RecipientUserId = @Id

--endregion
GO