SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [messaging].[PrivateMessagesGetByRecipientListId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[PrivateMessagesGetByRecipientListId]
-- Date Generated: Wednesday, June 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[PrivateMessagesGetByRecipientUserId]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	pm.[Id],
pm.	[AttachmentListId],
	pm.[Created],
	pm.[CreatedById],
	pm.[IsRead],
	pm.[IsStarredRecipient],
	pm.[IsStarredSender],
	pm.[IsTrashRecipient],
	pm.[IsTrashSender],
	pm.[Message],
	pm.[Modified],
	pm.[ParentId],
	pm.[RecipientListId],
	pm.[SenderUserId],
	pm.[SentDate],
  pm.[Subject],
	pm.[TrashedDateRecipient],
	pm.[TrashedDateSender],
	pm.[RowVersion]
FROM
	[messaging].[PrivateMessages] AS pm
  INNER JOIN messaging.RecipientLists rl ON rl.MessageId = pm.Id
WHERE
  rl.RecipientUserId = @Id

--endregion
GO