SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[RecipientListCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[RecipientListCreate]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[RecipientListCreate]
	@Createdbyid int,
	@Messageid int,
	@Recipientuserid int,
	@Created datetime

AS

SET NOCOUNT ON

INSERT INTO [messaging].[RecipientLists] (
	[CreatedById],
	[MessageId],
	[RecipientUserId],
	[Created]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Createdbyid,
	@Messageid,
	@Recipientuserid,
	@Created
)

--endregion

GO