SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[MessageFileUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[MessageFileUpdate]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[MessageFileUpdate]
@Version				timestamp,
	@Id int,
	@Contenttypeid int,
	@Compressed bit,
	@Data varbinary(max),
	@Description nvarchar(200),
	@Name nvarchar(2000),
	@Size bigint,
	@Typeid int,
	@Uploaded datetime
    
AS

SET NOCOUNT ON

UPDATE [messaging].[MessageFiles] SET
	[ContentTypeId] = @Contenttypeid,
	[Compressed] = @Compressed,
	[Data] = @Data,
	[Description] = @Description,
	[Name] = @Name,
	[Size] = @Size,
	[TypeId] = @Typeid,
	[Uploaded] = @Uploaded
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO