SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[MessageFilesGetByFILE_TYPEID]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[MessageFilesGetByFILE_TYPEID]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[MessageFilesGetByFILE_TYPEID]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[FILE_ID],
	[FILE_CONTENTTYPEID],
	[FILE_COMPRESSED],
	[FILE_DATA],
	[FILE_DESCRIPTION],
	[FILE_NAME],
	[FILE_SIZE],
	[FILE_TYPEID],
	[FILE_UPLOADED],
	[FILE_ROWVERSION]
FROM
	[messaging].[MessageFiles]
WHERE
	[FILE_TYPEID] = @Id

--endregion

GO