SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[CommentThreadsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[CommentThreadsGetAll]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[CommentThreadsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id]
FROM
	[messaging].[CommentThreads]

--endregion

GO