SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[AttachmentListCreate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[AttachmentListCreate]
-- Date Generated: Thursday, June 1, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[AttachmentListCreate]
	@Created datetime,
	@Createdbyid int,
	@Messagefileid int,
	@Messageid int

AS

SET NOCOUNT ON

INSERT INTO [messaging].[AttachmentLists] (
	[Created],
	[CreatedById],
	[MessageFileId],
	[MessageId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Created,
	@Createdbyid,
	@Messagefileid,
	@Messageid
)

--endregion

GO