SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [messaging].[PrivateMessageUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [messaging].[PrivateMessageUpdate]
-- Date Generated: Wednesday, June 7, 2017
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [messaging].[PrivateMessageUpdate]
@Version				timestamp,
	@Id int,
	@Attachmentlistid int,
	@Created datetime,
	@Createdbyid int,
	@Isread bit,
	@Isstarredrecipient bit,
	@Isstarredsender bit,
	@Istrashrecipient bit,
	@Istrashsender bit,
	@Message nvarchar(max),
	@Modified datetime,
	@Parentid int,
	@Recipientlistid int,
	@Senderuserid int,
	@Sentdate datetime,
	@Subject nvarchar(1000),
	@Trasheddaterecipient datetime,
	@Trasheddatesender datetime
    
AS

SET NOCOUNT ON

UPDATE [messaging].[PrivateMessages] SET
	[AttachmentListId] = @Attachmentlistid,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[IsRead] = @Isread,
	[IsStarredRecipient] = @Isstarredrecipient,
	[IsStarredSender] = @Isstarredsender,
	[IsTrashRecipient] = @Istrashrecipient,
	[IsTrashSender] = @Istrashsender,
	[Message] = @Message,
	[Modified] = @Modified,
	[ParentId] = @Parentid,
	[RecipientListId] = @Recipientlistid,
	[SenderUserId] = @Senderuserid,
	[SentDate] = @Sentdate,
	[Subject] = @Subject,
	[TrashedDateRecipient] = @Trasheddaterecipient,
	[TrashedDateSender] = @Trasheddatesender
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO