SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [purpleheart].[TemplateZipCodesGetByDepotID]	
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		ZIPCODE_ID
		, ZIPCODE_DEPOTID	
		, ZIPCODE_ITEMID
		, ZIPCODE_PUBLISHED
		, ZIPCODE_ROWVERSION
	FROM
		[purpleheart].[TemplateZipCodes]
	WHERE
		ZIPCODE_DEPOTID = @ID
	ORDER BY
		ZIPCODE_ID;
END
GO