SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [site].[LogonsGetBySiteID] 
	@ID					int	
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		LOGON_ID
		, LOGON_INACTIVELOGOUT
		, LOGON_LOCKEDOUT
		, LOGON_LOGONS
		, LOGON_SITEID
		, LOGON_USERID
		, LOGON_ROWVERSION
	FROM 
		[site].[Logons]	
	WHERE
		LOGON_SITEID = @ID;		
END
GO