SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [site].[PasswordResetRequestsGetByUserID]
	@UserID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		REQUEST_ID
		, REQUEST_DATETIME
		, REQUEST_HOST
		, REQUEST_IPADDRESS
		, REQUEST_KEY
		, REQUEST_TIMESTAMP
		, REQUEST_USERID
		, REQUEST_USERNAME
	FROM
		[site].[PasswordResetRequests]
	WHERE
		REQUEST_USERID = @UserID;	
END
GO