SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [StVincent].[ZipCodeGetCounts]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
	COUNT(*) AS ZIPCODE_SFDU
	,0 AS ZIPCODE_MFDU
	,0 AS ZIPCODE_BUSINESS
	,0 AS ZIPCODE_BOXES
	,0 AS ZIPCODE_TRLR

  FROM [StVincent].Leads as Leads

	
	WHERE RECORD_ZIP = @ID
		
END
GO