SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [StVincent].[CountResultsGetUnordered]
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		COUNT_ID
		, COUNT_CREATED
		, COUNT_CREATEDBYID
		, COUNT_COUNTID
		, COUNT_ORDERID		
		, COUNT_ROWVERSION
	FROM
		StVincent.[CountResults]
	WHERE
		COUNT_ORDERID IS NULL
	ORDER BY
		COUNT_ID;
END
GO