SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [StVincent].[TemplateZipCodeGetByID]
	@ID			int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT
		ZIPCODE_ID		
		, ZIPCODE_CREATED
		, ZIPCODE_CREATEDBYID
		, ZIPCODE_NAME		
		, ZIPCODE_ZIPCODE
		, ZIPCODE_ROWVERSION
	FROM
		[StVincent].[TemplateZipCodes]	
	WHERE
		ZIPCODE_ID = @ID
	ORDER BY
		ZIPCODE_ID;
END
GO