SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [StVincent].[CarrierRoutesGetByZipCodeID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
	1 as CRRT_ID
	,RECORD_CRRT AS CRRT_CRRT
	,CAST(RECORD_ZIP AS int) AS CRRT_ZIPCODEID
	,COUNT(*) AS CRRT_SFDU
	,(acx.CRRT_SFDU + acx.CRRT_BUSINESS + acx.CRRT_MFDU) as RouteTotal
	,(acx.CRRT_SFDU + acx.CRRT_MFDU) as RouteResTotal
	,0 AS CRRT_MFDU
	,0 AS CRRT_BUSINESS
	,0 AS CRRT_BOXES
	,0 AS CRRT_TRLR
	,NULL AS CRRT_AVERAGEAGE
	,NULL AS CRRT_INCOME
	,NULL AS CRRT_MKTMED
	,NULL AS CRRT_PERCENTCHILD
	,map.CRRT_LATITUDE
	,map.CRRT_LONGITUDE
	,NULL AS [CRRT_WKB]
	,map.CRRT_WKT
  FROM [StVincent].Leads as Leads
  inner join acxiom.CarrierRoutes acx on Leads.RECORD_CRRT = acx.CRRT_CRRT and CAST(RECORD_ZIP AS int) = acx.CRRT_ZIPCODEID
  INNER JOIN maponics.CarrierRoutes map ON Leads.RECORD_ZIP=map.CRRT_ZIPCODEID and Leads.RECORD_CRRT= map.CRRT_CRRT  
  WHERE RECORD_ZIP = @ID
  GROUP BY RECORD_CRRT 
			,RECORD_ZIP
			,map.CRRT_LATITUDE
			,map.CRRT_LONGITUDE			
			,map.CRRT_WKT
			,acx.CRRT_SFDU
			,acx.CRRT_MFDU
			,acx.CRRT_BUSINESS
	
END
GO