SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [StVincent].[RecordsGetRotation] 
	@DepotId	int
	, @Week		int
	, @Year		int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT	
		RECORD_DAYOFWEEK
		, RECORD_ZIPCODENAME
		, LEFT(RECORD_ZIPCODE, 5) AS [RECORD_ZIPCODE]
		, RECORD_CARRIERROUTE
		, COUNT(RECORD_CARRIERROUTE) AS [RECORD_COUNT]
	FROM 
		StVincent.[Records]
	WHERE
		RECORD_DEPOTID = @DepotId
		AND RECORD_WEEK = @Week
		AND RECORD_YEAR = @Year
		AND RECORD_SEED = 0
	GROUP BY
		RECORD_DAYOFWEEK
		, RECORD_ZIPCODENAME
		, LEFT(RECORD_ZIPCODE, 5)
		, RECORD_CARRIERROUTE

END
GO