SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[PermitGetByID]
	@ID		int
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT 
		PERMIT_ID
		, PERMIT_ACCOUNTNUMBER
		, PERMIT_ADDRESS1
		, PERMIT_ADDRESS2
		, PERMIT_CITY
		, PERMIT_CLIENTID
		, PERMIT_COMPANY
		, PERMIT_CREATED
		, PERMIT_CREATEDBYID
		, PERMIT_EXPIRATIONDATE		
		, PERMIT_GLOBAL		
		, PERMIT_NUMBER
		, PERMIT_POSTOFFICE				
		, PERMIT_STATE
		, PERMIT_TYPEID
		, PERMIT_ZIPCODE
		, PERMIT_ROWVERSION
	FROM 
		[usps].[Permits]
	WHERE 
		PERMIT_ID = @ID;
END
GO