SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[MailPiecesMerge]
	@ThreadID int
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT [dbo].[MailPieces]
	(
		[MAILPIECE_ADDRESS1]
		, [MAILPIECE_ADDRESS2]
		, [MAILPIECE_ADDRESS3]
		, [MAILPIECE_CITY]
		, [MAILPIECE_COMPANY]
		, [MAILPIECE_CRRT]
		, [MAILPIECE_FINALIZESCANID]
		, [MAILPIECE_FIRSTNAME]
		, [MAILPIECE_FIRSTSCANID]
		, [MAILPIECE_FORWARDSCANID]
		, [MAILPIECE_GROUPID]
		, [MAILPIECE_INDIVIDUALID]
		, [MAILPIECE_LASTNAME]
		, [MAILPIECE_LASTSCANID]		
		, [MAILPIECE_RETURNSCANID]
		, [MAILPIECE_ROUTINGCODE]
		, [MAILPIECE_SCFID]
		, [MAILPIECE_SEGMENTID]
		, [MAILPIECE_STATE]				
		, [MAILPIECE_TITLE]
		, [MAILPIECE_TRACKINGCODE]
		, [MAILPIECE_ZIPCODE]
		, [MAILPIECE_ZIPCODEEXT]
	)
	SELECT
		[MAILPIECE_ADDRESS1]
		, [MAILPIECE_ADDRESS2]
		, [MAILPIECE_ADDRESS3]
		, [MAILPIECE_CITY]
		, [MAILPIECE_COMPANY]
		, [MAILPIECE_CRRT]
		, [MAILPIECE_FINALIZESCANID]
		, [MAILPIECE_FIRSTNAME]
		, [MAILPIECE_FIRSTSCANID]
		, [MAILPIECE_FORWARDSCANID]
		, [MAILPIECE_GROUPID]
		, [MAILPIECE_INDIVIDUALID]
		, [MAILPIECE_LASTNAME]
		, [MAILPIECE_LASTSCANID]		
		, [MAILPIECE_RETURNSCANID]
		, [MAILPIECE_ROUTINGCODE]
		, [MAILPIECE_SCFID]
		, [MAILPIECE_SEGMENTID]
		, [MAILPIECE_STATE]			
		, [MAILPIECE_TITLE]
		, [MAILPIECE_TRACKINGCODE]
		, [MAILPIECE_ZIPCODE]
		, [MAILPIECE_ZIPCODEEXT]
	FROM 
		[usps].[MailPiecesStaging]
	WHERE
		MAILPIECE_THREADID = @ThreadID;

	DELETE 
		[usps].[MailPiecesStaging]
	WHERE
		MAILPIECE_THREADID = @ThreadID;	
END
GO