SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [usps].[PostageRefundsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageRefundsGetAll]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageRefundsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
  Created,
  CreatedById,
	[AccountId],
	[Reason],
	[RefundAmount],
	[RowVersion]
FROM
	[usps].[PostageRefunds]

--endregion

GO