SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[GhostNumbersGetByPermitId] 
	@ID int
AS
BEGIN
	
	SELECT
		GHOSTNUMBER_ID
		, GHOSTNUMBER_CLIENTID
		, GHOSTNUMBER_NUMBER
		, GHOSTNUMBER_PERMITID
	FROM
		[usps].[GhostNumbers] 
	WHERE 
		GHOSTNUMBER_PERMITID = @ID;

END
GO