SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
--region [usps].[PostageAccountUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageAccountUpdate]
-- Date Generated: Wednesday, July 20, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageAccountUpdate]
	@Id int,
	@Clientid int,
	@Name varchar(500),
    @Version timestamp
AS

SET NOCOUNT ON

UPDATE [usps].[PostageAccounts] SET
	[ClientId] = @Clientid,
	[Name] = @Name
    OUTPUT inserted.Id AS [ID]
WHERE
	[Id] = @Id AND [RowVersion] = @Version

--endregion

GO