SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[InsertionItemsGetBySegmentID]
	@ID		int

AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		ITEM_ID
		, ITEM_INDEX
		, ITEM_INVENTORYITEMID
		, ITEM_SEGMENTID
		, ITEM_ROWVERSION
	FROM 
		[usps].[InsertionItems]
	WHERE
		ITEM_SEGMENTID = @ID;
END
GO