SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[GhostNumberGetByClientIDByPermitID] 
	@ClientID	int
	, @PermitID int
AS
BEGIN
	
	SELECT
		GHOSTNUMBER_ID
		, GHOSTNUMBER_CLIENTID
		, GHOSTNUMBER_NUMBER
		, GHOSTNUMBER_PERMITID
	FROM
		[usps].[GhostNumbers] 
	WHERE 
		(GHOSTNUMBER_CLIENTID = @ClientID)
		AND (GHOSTNUMBER_PERMITID = @PermitID);

END
GO