SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [usps].[PostageReceiptUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageReceiptUpdate]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageReceiptUpdate]
@Version				timestamp,
	@Id int,
	@Accountid int,
	@Amountreceived decimal(11, 2),
	@Created datetime,
	@Createdbyid int,
	@Notes nvarchar(1000),
	@Received date,
	@Receivedby int,
	@Reference nvarchar(50),
	@Typeid int
    
AS

SET NOCOUNT ON

UPDATE [usps].[PostageReceipts] SET
	[AccountId] = @Accountid,
	[AmountReceived] = @Amountreceived,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[Notes] = @Notes,
	[Received] = @Received,
	[ReceivedBy] = @Receivedby,
	[Reference] = @Reference,
	[TypeId] = @Typeid
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO