SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [usps].[PostageRequestDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageRequestDeleteById]
-- Date Generated: Wednesday, July 20, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageRequestDeleteByID]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [usps].[PostageRequests]
WHERE
	[Id] = @Id

--endregion

GO