SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[ServiceTypeGetByID]
	@ID	int	
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		SERVICETYPE_ID
		, SERVICETYPE_ACSOPTIONID
		, SERVICETYPE_FULLSERVICE
		, SERVICETYPE_POSTALCLASSID
		, SERVICETYPE_TRACKED
	FROM
		[usps].[ServiceTypes]
	WHERE
		SERVICETYPE_ID = @ID;
	
END
GO