SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[SegmentSequencesGetByMailingID]
	@ID int
AS
BEGIN
	
	SET NOCOUNT ON;
	    
	SELECT
		seq.SEQUENCE_ID
		, seq.SEQUENCE_CREATED
		, seq.SEQUENCE_CREATEDBYID
		, seq.SEQUENCE_CYCLECOUNT
		, seq.SEQUENCE_ENDVALUE
		, seq.SEQUENCE_INCREMENT
		, seq.SEQUENCE_MAILERID
		, seq.SEQUENCE_MAXVALUE
		, seq.SEQUENCE_MINVALUE
		, seq.SEQUENCE_SEGMENTID
		, seq.SEQUENCE_STARTVALUE
	FROM
		[usps].[MailSegmentSequences] AS seq
		INNER JOIN [dbo].[MailSegments] AS seg
			ON seq.SEQUENCE_SEGMENTID = seg.MAILSEGMENT_ID
	WHERE
		seg.MAILSEGMENT_JOBID = @ID;
END
GO