SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[SegmentFilesGetBySegmentID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		[FILE_ID]		
		, FILE_METADATAID		
		, FILE_SEGMENTID
	FROM 
		[usps].[SegmentFiles]
	WHERE
		FILE_SEGMENTID = @ID;
END
GO