SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [usps].[PostageReceiptInsert]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageReceiptInsert]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageReceiptInsert]
	@Accountid int,
	@Amountreceived decimal(11, 2),
	@Created datetime,
	@Createdbyid int,
	@Notes nvarchar(1000),
	@Received date,
	@Receivedby int,
	@Reference nvarchar(50),
	@Typeid int

AS

SET NOCOUNT ON

INSERT INTO [usps].[PostageReceipts] (
	[AccountId],
	[AmountReceived],
	[Created],
	[CreatedById],
	[Notes],
	[Received],
	[ReceivedBy],
	[Reference],
	[TypeId]
) 
OUTPUT		
		inserted.Id AS ID, inserted.Rowversion AS [VERSION]
VALUES (
	@Accountid,
	@Amountreceived,
	@Created,
	@Createdbyid,
	@Notes,
	@Received,
	@Receivedby,
	@Reference,
	@Typeid
)

--endregion

GO