SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[MailPieceScansMerge]
	@ThreadID int
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT [dbo].[MailPieceScans]
	(
		MAILPIECESCAN_CREATED
		, MAILPIECESCAN_DATETIME
		, MAILPIECESCAN_FACILITYID
		, MAILPIECESCAN_MAILPIECEID
		, MAILPIECESCAN_OPERATIONID
	)
	SELECT
		SCAN_CREATED
		, SCAN_DATETIME
		, SCAN_FACILITYID
		, SCAN_MAILPIECEID
		, SCAN_OPERATIONID
	FROM 
		[usps].[MailPieceScansStaging]
	WHERE
		SCAN_THREADID = @ThreadID;

	DELETE 
		[usps].[MailPieceScansStaging]
	WHERE
		SCAN_THREADID = @ThreadID;
	
END
GO