SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[ServiceTypesGetByPostalClassID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		SERVICETYPE_ID
		, SERVICETYPE_ACSOPTIONID
		, SERVICETYPE_FULLSERVICE
		, SERVICETYPE_POSTALCLASSID
		, SERVICETYPE_TRACKED
	FROM
		[usps].[ServiceTypes]
	WHERE
		SERVICETYPE_POSTALCLASSID = @ID;
	
END
GO