SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[ServiceTypesGet]
	
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		SERVICETYPE_ID
		, SERVICETYPE_ACSOPTIONID
		, SERVICETYPE_FULLSERVICE
		, SERVICETYPE_POSTALCLASSID
		, SERVICETYPE_TRACKED
	FROM
		[usps].[ServiceTypes];	
	
END
GO