SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[MailingFilesGetByMailingID]
	@ID int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		[FILE_ID]
		, FILE_MAILINGID
		, FILE_METADATAID		
	FROM 
		[usps].[MailingFiles]
	WHERE
		FILE_MAILINGID = @ID;
END
GO