SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [usps].[PostageUsageItemUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageUsageItemUpdate]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageUsageItemUpdate]
@Version				timestamp,
	@Id int,
	@Accountid int,
	@Actual decimal(11, 2),
	@Billed decimal(11, 2),
	@Created datetime,
	@Createdbyid int,
	@Date date,
	@Jobid int,
	@Notes nvarchar(1000)
    
AS

SET NOCOUNT ON

UPDATE [usps].[PostageUsageItems] SET
	[AccountId] = @Accountid,
	[Actual] = @Actual,
	[Billed] = @Billed,
	[Created] = @Created,
	[CreatedById] = @Createdbyid,
	[Date] = @Date,
	[JobId] = @Jobid,
	[Notes] = @Notes
    OUTPUT inserted.Id AS [ID], inserted.[RowVersion] as [VERSION]
WHERE
	[Id] = @Id
AND [RowVersion] = @Version	

--endregion

GO