SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--region [usps].[PostageRefundDeleteById]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   dlaub using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [usps].[PostageRefundDeleteById]
-- Date Generated: Thursday, July 21, 2016
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [usps].[PostageRefundDeleteById]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [usps].[PostageRefunds]
WHERE
	[Id] = @Id

--endregion

GO