SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[MailSegmentEmailVersionsGetBySegmentID]
	@ID	int
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		VERSION_VERSIONID
		, VERSION_SEGMENTID
		, VERSION_TRIGGEREVENT
	FROM 
		[usps].[MailSegmentEmailVersions]
	WHERE
		VERSION_SEGMENTID = @ID;
	
END
GO