SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[PermitsGetAutoComplete]
	@ID				int
	, @Substring	nvarchar(255)
AS
BEGIN
			
	SET NOCOUNT ON;
	    
	SELECT DISTINCT
		PERMIT_ID
		, PERMIT_ACCOUNTNUMBER
		, PERMIT_ADDRESS1
		, PERMIT_ADDRESS2
		, PERMIT_CITY
		, PERMIT_CLIENTID
		, PERMIT_COMPANY
		, PERMIT_CREATED
		, PERMIT_CREATEDBYID
		, PERMIT_EXPIRATIONDATE
		, PERMIT_GLOBAL
		, PERMIT_NUMBER
		, PERMIT_POSTOFFICE
		, PERMIT_STATE
		, PERMIT_TYPEID
		, PERMIT_ZIPCODE
		, PERMIT_ROWVERSION
	FROM
		[usps].Permits AS p		
		INNER JOIN [dbo].[Clients] AS c
			ON p.PERMIT_CLIENTID = c.CLIENT_ID
		INNER JOIN [dbo].[Relationships] AS r
			ON c.CLIENT_ID = r.RELATIONSHIP_CLIENTID
				AND r.RELATIONSHIP_USERID = @ID
				OR p.PERMIT_GLOBAL = 1
	
	WHERE
		(p.PERMIT_NUMBER LIKE '%' + @Substring + '%')
		OR (p.PERMIT_COMPANY LIKE '%' + @Substring + '%')
		OR (p.PERMIT_POSTOFFICE LIKE '%' + @Substring + '%')
		OR (CLIENT_NAME LIKE '%' + @Substring + '%')
		OR (CLIENT_SHORTNAME LIKE '%' + @Substring + '%')
END
GO