SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[ZipCodeGetByZipCode]
	@ZipCode			char(5)
	, @WithBoundaries	bit	= 0
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		ZIPCODE_ID
		, ZIPCODE_CITY
		, ZIPCODE_COUNTY
		, ZIPCODE_COUNTYFIPS
		, ZIPCODE_LATITUDE
		, ZIPCODE_LONGITUDE
		, ZIPCODE_STATE
		, ZIPCODE_STATEFIPS
		, CASE @WithBoundaries
			WHEN 1 THEN
				ZIPCODE_WKB				
			END AS ZIPCODE_WKB
		, CASE @WithBoundaries
			WHEN 1 THEN
				ZIPCODE_WKT				
			END  AS ZIPCODE_WKT
		, RIGHT('00000' + ISNULL(ZIPCODE_ID,''),5) AS ZIPCODE_ZIPCODE
	FROM
		[maponics].[ZipCodes]
	WHERE
		ZIPCODE_ID = @ZipCode

END
GO