SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [usps].[MailPieceScansUpdatesReturnsMerge]
	
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @key uniqueidentifier;
	
	SET @key = NEWID();

	UPDATE 
		[usps].[MailPieceScanUpdates] WITH (ROWLOCK, UPDLOCK, READPAST)
	SET
		MAILPIECE_UPDATEKEY = @key
	WHERE 
		MAILPIECE_UPDATEKEY IS NULL;
	
	UPDATE
		p
	SET	
		-- GET RETURNED SCAN
		MAILPIECE_RETURNSCANID = (
			SELECT TOP 1 MAILPIECESCAN_ID 
			FROM 
				[dbo].[MailPieceScans] AS s
				INNER JOIN [dbo].[Operations] AS o
					ON s.MAILPIECESCAN_OPERATIONID = o.OPERATION_ID
			WHERE 
				p.MAILPIECE_ID = s.MAILPIECESCAN_MAILPIECEID
				AND (o.OPERATION_CODE = 59 OR o.OPERATION_CODE = 86 OR o.OPERATION_CODE = 91 OR o.OPERATION_CODE = 5091)
			ORDER BY
				s.MAILPIECESCAN_DATETIME
		)
	FROM
		[dbo].[MailPieces] AS p
		INNER JOIN [usps].[MailPieceScanUpdates] AS u
			ON p.MAILPIECE_ID = u.MAILPIECE_ID
	WHERE
		u.MAILPIECE_UPDATEKEY = @key;

	DELETE 
		usps.MailPieceScanUpdates
	WHERE
		MAILPIECE_UPDATEKEY = @key;
	
END
GO