SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [web].[ScreenshotsGet]
	
AS
BEGIN
	
	SET NOCOUNT ON;
	
	SELECT
		SCREENSHOT_ID
		, SCREENSHOT_FULLSIZE
		, SCREENSHOT_THUMBNAIL
		, SCREENSHOT_PAGEID
	FROM
		[web].[Screenshots]
	ORDER BY
		SCREENSHOT_ID;		
END
GO