SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [web].[EventListenersGetByPageIDByEvent]
	@ID			int
	, @Event	int
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		EVENTLISTENER_ID
		, EVENTLISTENER_EVENTS
		, EVENTLISTENER_PAGEID
		, EVENTLISTENER_USERID
		, EVENTLISTENER_ROWVERSION
    FROM
		[web].[EventListeners]
	WHERE
		(EVENTLISTENER_PAGEID = @ID)
		AND (EVENTLISTENER_EVENTS & @Event > 0)
	ORDER BY
		EVENTLISTENER_ID;
END
GO