SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [web].[EventListenersGet]
	
AS
BEGIN
	SET NOCOUNT ON;

    SELECT 
		l.EVENTLISTENER_ID
		, l.EVENTLISTENER_EVENTS
		, l.EVENTLISTENER_PAGEID
		, l.EVENTLISTENER_USERID
		, l.EVENTLISTENER_ROWVERSION
    FROM
		[web].[EventListeners] AS l	
	ORDER BY
		l.EVENTLISTENER_ID;
END
GO