SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [web].[LinkClicksGetByUserID]
	@ID			int
AS
BEGIN
	
    SET NOCOUNT ON;
    
    DECLARE @TrackAnonymous bit;
	SET @TrackAnonymous = 
	(
		SELECT 
			c.CAMPAIGN_TRACKANONYMOUSEVENTS 
		FROM 
			[web].[Campaigns] AS c
			INNER JOIN [web].[Versions] AS v
				ON c.CAMPAIGN_ID = v.VERSION_CAMPAIGNID
			INNER JOIN [web].[Users] AS u
				ON v.VERSION_ID = u.USER_VERSIONID
		WHERE 
			u.[USER_ID] = @ID
	);
	
	IF @TrackAnonymous = 1	
		SELECT 
			c.LINKCLICK_ID
			, c.LINKCLICK_DATETIME
			, c.LINKCLICK_IPADDRESS
			, c.LINKCLICK_IPCITYNAME
			, c.LINKCLICK_IPCOUNTRYCODE
			, c.LINKCLICK_IPLATITUDE
			, c.LINKCLICK_IPLONGITUDE
			, c.LINKCLICK_IPREGIONCODE
			, c.LINKCLICK_IPPOSTALCODE
			, c.LINKCLICK_LINKID
			, c.LINKCLICK_SESSIONID
			, c.LINKCLICK_USERAGENT
		FROM
			[web].[LinkClicks] AS c
			INNER JOIN [web].[UserLinkClicks] AS u
				ON c.LINKCLICK_ID = u.USERLINKCLICK_LINKCLICKID
		WHERE
			u.USERLINKCLICK_USERID = u.USERLINKCLICK_USERID
		ORDER BY
			c.LINKCLICK_ID;
	ELSE
		SELECT 
			c.LINKCLICK_ID
			, c.LINKCLICK_DATETIME
			, c.LINKCLICK_IPADDRESS
			, c.LINKCLICK_IPCITYNAME
			, c.LINKCLICK_IPCOUNTRYCODE
			, c.LINKCLICK_IPLATITUDE
			, c.LINKCLICK_IPLONGITUDE
			, c.LINKCLICK_IPREGIONCODE
			, c.LINKCLICK_IPPOSTALCODE
			, c.LINKCLICK_LINKID
			, c.LINKCLICK_SESSIONID
			, c.LINKCLICK_USERAGENT
		FROM
			[web].[LinkClicks] AS c
			INNER JOIN [web].[UserLinkClicks] AS u
				ON c.LINKCLICK_ID = u.USERLINKCLICK_LINKCLICKID
		WHERE
			u.USERLINKCLICK_USERID = u.USERLINKCLICK_USERID
			AND c.LINKCLICK_ID IN
			(
				SELECT DISTINCT USERLINKCLICK_LINKCLICKID FROM [web].[UserLinkClicks]
			)
		ORDER BY
			c.LINKCLICK_ID;
END
GO