SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [web].[PageGetByURL]
	@URL nvarchar(200)
AS
BEGIN
	
	SET NOCOUNT ON;
    
	SELECT 
		PAGE_ID 		
		, PAGE_LINKSREGISTERED
		, PAGE_NAME
		, PAGE_REQUESTTIMEOUT
		, PAGE_TYPE
		, PAGE_URL
		, PAGE_VERSIONID
		, PAGE_ROWVERSION 
	FROM 
		[web].[Pages] 
	WHERE 
		PAGE_URL = @URL;
END
GO