SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [purpleheart].[GetWeekNumber]
(
	@Date	date
)
RETURNS int
AS
BEGIN
	RETURN CASE WHEN DATEPART(WEEKDAY, @Date) < 2 THEN DATEPART(ISO_WEEK, @Date) + 1 ELSE DATEPART(ISO_WEEK, @Date) END

END
GO