CREATE TABLE [acs].[NixieRecords] (
  [RECORD_ID] [int] IDENTITY (-2147483648, 1),
  [RECORD_ACSTYPEID] [int] NULL,
  [RECORD_CAPTURETYPEID] [int] NULL,
  [RECORD_DELIVERABILITYCODEID] [int] NOT NULL,
  [RECORD_FEENOTIFICATIONTYPEID] [int] NOT NULL,
  [RECORD_FULFILLMENTDATE] [date] NULL,
  [RECORD_HARDCOPYFLAG] [char](1) NULL,
  [RECORD_IDTAG] [char](16) NULL,
  [RECORD_IMPB] [char](35) NULL,
  [RECORD_MAILACTIONCODEID] [int] NULL,
  [RECORD_MAILERID] [char](9) NULL,
  [RECORD_MAILPIECEID] [int] NOT NULL,
  [RECORD_MAILSHAPEID] [int] NULL,
  [RECORD_NOTIFICATIONTYPEID] [int] NULL,
  [RECORD_POSTAGEDUE] [decimal](4, 2) NULL,
  [RECORD_POSTALSERVICESITEID] [int] NOT NULL,
  [RECORD_PROCESSINGTYPEID] [int] NULL,
  CONSTRAINT [PK_NixieRecords] PRIMARY KEY CLUSTERED ([RECORD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_NixieRecords_RECORD_MAILPIECEID]
  ON [acs].[NixieRecords] ([RECORD_MAILPIECEID])
  INCLUDE ([RECORD_ID])
  ON [PRIMARY]
GO

ALTER TABLE [acs].[NixieRecords]
  ADD CONSTRAINT [FK_NixieRecords_DeliverabilityCodes] FOREIGN KEY ([RECORD_DELIVERABILITYCODEID]) REFERENCES [acs].[DeliverabilityCodes] ([DELIVERABILITYCODE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[NixieRecords]
  ADD CONSTRAINT [FK_NixieRecords_FeeNotificationTypes] FOREIGN KEY ([RECORD_FEENOTIFICATIONTYPEID]) REFERENCES [acs].[FeeNotificationTypes] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[NixieRecords] WITH NOCHECK
  ADD CONSTRAINT [FK_NixieRecords_MailPieces] FOREIGN KEY ([RECORD_MAILPIECEID]) REFERENCES [dbo].[MailPieces] ([MAILPIECE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[NixieRecords]
  ADD CONSTRAINT [FK_NixieRecords_NotificationTypes] FOREIGN KEY ([RECORD_NOTIFICATIONTYPEID]) REFERENCES [acs].[NotificationTypes] ([ID]) ON DELETE CASCADE
GO