CREATE TABLE [acs].[CoaRecords] (
  [RECORD_ID] [int] IDENTITY (-2147483648, 1),
  [RECORD_ACSTYPEID] [int] NULL,
  [RECORD_CAPTURETYPEID] [int] NULL,
  [RECORD_COMPANYNAME] [varchar](47) NULL,
  [RECORD_DELIVERABILITYCODEID] [int] NOT NULL,
  [RECORD_EFFECTIVEDATE] [date] NOT NULL,
  [RECORD_FEENOTIFICATIONTYPEID] [int] NOT NULL,
  [RECORD_FIRSTNAME] [varchar](15) NULL,
  [RECORD_FULFILLMENTDATE] [date] NULL,
  [RECORD_HARDCOPYFLAG] [char](1) NULL,
  [RECORD_IDTAG] [char](16) NULL,
  [RECORD_IMPB] [char](35) NULL,
  [RECORD_LASTNAME] [varchar](20) NULL,
  [RECORD_MADEAVAILABLE] [date] NULL,
  [RECORD_MAILACTIONCODEID] [int] NULL,
  [RECORD_MAILERID] [char](9) NOT NULL,
  [RECORD_MAILPIECEID] [int] NOT NULL,
  [RECORD_MAILSHAPEID] [int] NULL,
  [RECORD_MOVETYPEID] [int] NOT NULL,
  [RECORD_NAMEPREFIX] [varchar](6) NULL,
  [RECORD_NAMESUFFIX] [varchar](6) NULL,
  [RECORD_NEWADDRESSTYPEID] [int] NULL,
  [RECORD_NEWCHECKDIGIT] [smallint] NULL,
  [RECORD_NEWCITY] [varchar](28) NULL,
  [RECORD_NEWDELIVERYPOINT] [int] NULL,
  [RECORD_NEWPOSTDIRECTIONAL] [char](2) NULL,
  [RECORD_NEWPREDIRECTIONAL] [char](2) NULL,
  [RECORD_NEWPRIMARYNUMBER] [varchar](10) NULL,
  [RECORD_NEWSECONDARYNUMBER] [varchar](10) NULL,
  [RECORD_NEWSTATE] [char](2) NULL,
  [RECORD_NEWSTREETNAME] [varchar](28) NULL,
  [RECORD_NEWSTREETSUFFIX] [char](4) NULL,
  [RECORD_NEWUNITDESIGNATOR] [char](4) NULL,
  [RECORD_NEWURBANIZATION] [varchar](28) NULL,
  [RECORD_NEWZIPCODE] [char](5) NULL,
  [RECORD_NEWZIPCODEADDON] [char](4) NULL,
  [RECORD_NOTIFICATIONTYPEID] [int] NULL,
  [RECORD_OLDADDRESSTYPEID] [int] NULL,
  [RECORD_OLDCITY] [varchar](28) NULL,
  [RECORD_OLDPOSTDIRECTIONAL] [char](2) NULL,
  [RECORD_OLDPREDIRECTIONAL] [char](2) NULL,
  [RECORD_OLDPRIMARYNUMBER] [varchar](10) NULL,
  [RECORD_OLDSECONDARYNUMBER] [varchar](10) NULL,
  [RECORD_OLDSTATE] [char](2) NULL,
  [RECORD_OLDSTREETNAME] [varchar](28) NULL,
  [RECORD_OLDSTREETSUFFIX] [char](4) NULL,
  [RECORD_OLDUNITDESIGNATOR] [char](4) NULL,
  [RECORD_OLDURBANIZATION] [varchar](28) NULL,
  [RECORD_OLDZIPCODE] [char](5) NULL,
  [RECORD_POSTAGEDUE] [decimal](4, 2) NULL,
  [RECORD_POSTALSERVICESITEID] [int] NOT NULL,
  [RECORD_PRIVATEMAILBOX] [char](8) NULL,
  [RECORD_PROCESSINGTYPEID] [int] NULL,
  CONSTRAINT [PK_ChangeOfAddressRecords] PRIMARY KEY CLUSTERED ([RECORD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_ChangeOfAddressRecords_MailPieceID]
  ON [acs].[CoaRecords] ([RECORD_MAILPIECEID])
  ON [PRIMARY]
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_AddressTypes] FOREIGN KEY ([RECORD_NEWADDRESSTYPEID]) REFERENCES [acs].[AddressTypes] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_DeliverabilityCodes] FOREIGN KEY ([RECORD_DELIVERABILITYCODEID]) REFERENCES [acs].[DeliverabilityCodes] ([DELIVERABILITYCODE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_FeeNotificationTypes] FOREIGN KEY ([RECORD_FEENOTIFICATIONTYPEID]) REFERENCES [acs].[FeeNotificationTypes] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords] WITH NOCHECK
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_MailPieces] FOREIGN KEY ([RECORD_MAILPIECEID]) REFERENCES [dbo].[MailPieces] ([MAILPIECE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_MoveTypes] FOREIGN KEY ([RECORD_MOVETYPEID]) REFERENCES [acs].[MoveTypes] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_ChangeOfAddressRecords_NotificationTypes] FOREIGN KEY ([RECORD_NOTIFICATIONTYPEID]) REFERENCES [acs].[NotificationTypes] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_CoaRecords_CaptureTypes] FOREIGN KEY ([RECORD_CAPTURETYPEID]) REFERENCES [acs].[CaptureTypes] ([ID])
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_CoaRecords_MailActionCodes] FOREIGN KEY ([RECORD_MAILACTIONCODEID]) REFERENCES [acs].[MailActionCodes] ([ID])
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_CoaRecords_MailShapes] FOREIGN KEY ([RECORD_MAILSHAPEID]) REFERENCES [acs].[MailShapes] ([ID])
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_CoaRecords_ProcessingTypes] FOREIGN KEY ([RECORD_PROCESSINGTYPEID]) REFERENCES [acs].[ProcessingTypes] ([ID])
GO

ALTER TABLE [acs].[CoaRecords]
  ADD CONSTRAINT [FK_CoaRecords_Types] FOREIGN KEY ([RECORD_ACSTYPEID]) REFERENCES [acs].[Types] ([ID]) ON DELETE CASCADE
GO