CREATE TABLE [acs].[DeliverabilityCodes] (
  [DELIVERABILITYCODE_ID] [int] IDENTITY,
  [DELIVERABILITYCODE_CODE] [char](1) NOT NULL,
  [DELIVERABILITYCODE_DESCRIPTION] [varchar](100) NOT NULL,
  [DELIVERABILITYCODE_TYPEID] [int] NOT NULL,
  CONSTRAINT [PK_DeliverabilityCodes] PRIMARY KEY CLUSTERED ([DELIVERABILITYCODE_ID])
)
ON [PRIMARY]
GO