CREATE TABLE [acxiom].[ZipCodes] (
  [ZIPCODE_ID] [int] IDENTITY (-2147483648, 1),
  [ZIPCODE_AVERAGEAGE] [decimal](3) NULL,
  [ZIPCODE_CITY] [varchar](28) NOT NULL,
  [ZIPCODE_INCOME] [decimal](8) NULL,
  [ZIPCODE_LATITUDE] [decimal](16, 13) NOT NULL,
  [ZIPCODE_LONGITUDE] [decimal](16, 13) NOT NULL,
  [ZIPCODE_MKTMED] [decimal](8) NULL,
  [ZIPCODE_PERCENTCHILD] [decimal](3) NULL,
  [ZIPCODE_STATE] [char](2) NOT NULL,
  [ZIPCODE_WKB] [geometry] NOT NULL,
  [ZIPCODE_WKT] [varchar](max) NOT NULL,
  CONSTRAINT [PK_ZipCodes] PRIMARY KEY CLUSTERED ([ZIPCODE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE SPATIAL INDEX [IX_ZipCodes_Spatial]
  ON [acxiom].[ZipCodes] ([ZIPCODE_WKB])
USING GEOMETRY_GRID
  WITH (BOUNDING_BOX = (XMIN = -180, YMIN = -90, XMAX = 180, YMAX = 90))
  ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE SPATIAL INDEX [IX_ZipCodes_Spatial]
  ON [acxiom].[ZipCodes] ([ZIPCODE_WKB])
USING GEOMETRY_GRID
  WITH (BOUNDING_BOX = (XMIN = -180, YMIN = -90, XMAX = 180, YMAX = 90))
  ON [PRIMARY]
GO