CREATE TABLE [acxiom].[TemplateZipCodes] (
  [ZIPCODE_ID] [int] IDENTITY (-2147483648, 1),
  [ZIPCODE_CREATED] [datetime] NOT NULL,
  [ZIPCODE_CREATEDBYID] [int] NOT NULL,
  [ZIPCODE_NAME] [char](10) NOT NULL,
  [ZIPCODE_ZIPCODE] [char](5) NOT NULL,
  [ZIPCODE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_ZipCodeItem] PRIMARY KEY CLUSTERED ([ZIPCODE_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [acxiom].[TemplateZipCodes]
  ADD CONSTRAINT [FK_ZipCodeItems_Users] FOREIGN KEY ([ZIPCODE_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO