CREATE TABLE [acxiom].[Leads] (
  [LEAD_ID] [int] IDENTITY (-2147483648, 1),
  [LEAD_ADDRESS] [varchar](200) NOT NULL,
  [LEAD_CARRIERROUTE] [char](4) NOT NULL,
  [LEAD_CHECKDIGIT] [char](1) NULL,
  [LEAD_CITY] [varchar](28) NOT NULL,
  [LEAD_DELIVERYPOINT] [char](2) NULL,
  [LEAD_ORDERID] [int] NOT NULL,
  [LEAD_STATE] [char](2) NOT NULL,
  [LEAD_TITLE] [varchar](100) NULL,
  [LEAD_WALKSEQUENCE] [char](5) NOT NULL,
  [LEAD_ZIP4] [char](4) NULL,
  [LEAD_ZIPCODE] [char](5) NOT NULL,
  CONSTRAINT [PK_Leads] PRIMARY KEY CLUSTERED ([LEAD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Leads_OrderID]
  ON [acxiom].[Leads] ([LEAD_ORDERID])
  INCLUDE ([LEAD_ADDRESS], [LEAD_CARRIERROUTE], [LEAD_CHECKDIGIT], [LEAD_CITY], [LEAD_DELIVERYPOINT], [LEAD_STATE], [LEAD_TITLE], [LEAD_WALKSEQUENCE], [LEAD_ZIP4], [LEAD_ZIPCODE])
  ON [PRIMARY]
GO

ALTER TABLE [acxiom].[Leads] WITH NOCHECK
  ADD CONSTRAINT [FK_Leads_Orders] FOREIGN KEY ([LEAD_ORDERID]) REFERENCES [acxiom].[Orders] ([ORDER_ID]) ON DELETE CASCADE
GO