CREATE TABLE [dbo].[MailStreams] (
  [MAILSTREAM_ID] [int] IDENTITY,
  [MAILSTREAM_NAME] [nchar](50) NOT NULL,
  CONSTRAINT [PK_tblMailStreams] PRIMARY KEY CLUSTERED ([MAILSTREAM_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO