CREATE TABLE [dbo].[PostageTypes] (
  [POSTAGETYPE_ID] [int] IDENTITY,
  [POSTAGETYPE_NAME] [nvarchar](50) NOT NULL,
  [POSTAGETYPE_ATTRIBUTES] [int] NOT NULL CONSTRAINT [DF_tblPostageTypes_POSTAGETYPE_ATTRIBUTES] DEFAULT (0),
  CONSTRAINT [PK_PostageTypes] PRIMARY KEY CLUSTERED ([POSTAGETYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_PostageTypes_Name]
  ON [dbo].[PostageTypes] ([POSTAGETYPE_NAME])
  ON [PRIMARY]
GO