CREATE TABLE [dbo].[ComminglerClients] (
  [COMMINGLERCLIENT_ID] [int] IDENTITY (-2147483648, 1),
  [COMMINGLERCLIENT_CLIENTID] [int] NOT NULL,
  [COMMINGLERCLIENT_COMMINGLERID] [int] NOT NULL,
  [COMMINGLERCLIENT_NONPROFITRATE] [decimal](4, 3) NOT NULL,
  [COMMINGLERCLIENT_STANDARDRATE] [decimal](4, 3) NOT NULL,
  [COMMINGLERCLIENT_VALUE] [int] NOT NULL,
  [COMMINGLERCLIENT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_ComminglerClients] PRIMARY KEY CLUSTERED ([COMMINGLERCLIENT_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_ComminglerClients_ClientID]
  ON [dbo].[ComminglerClients] ([COMMINGLERCLIENT_CLIENTID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_ComminglerClients_ComminglerID]
  ON [dbo].[ComminglerClients] ([COMMINGLERCLIENT_COMMINGLERID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_ComminglerClients_Unqiueness]
  ON [dbo].[ComminglerClients] ([COMMINGLERCLIENT_CLIENTID], [COMMINGLERCLIENT_COMMINGLERID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[ComminglerClients]
  ADD CONSTRAINT [FK_ComminglerClients_Clients] FOREIGN KEY ([COMMINGLERCLIENT_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ComminglerClients]
  ADD CONSTRAINT [FK_ComminglerClients_Comminglers] FOREIGN KEY ([COMMINGLERCLIENT_COMMINGLERID]) REFERENCES [dbo].[Comminglers] ([COMMINGLER_ID]) ON DELETE CASCADE
GO