CREATE TABLE [dbo].[InventoryReceiptItems] (
  [INVENTORYRECEIPTITEM_ID] [int] IDENTITY,
  [INVENTORYRECEIPTITEM_RECEIPTID] [int] NOT NULL,
  [INVENTORYRECEIPTITEM_CONTAINERTYPEID] [int] NOT NULL,
  [INVENTORYRECEIPTITEM_CONTAINERS] [int] NOT NULL,
  [INVENTORYRECEIPTITEM_CONTAINERCOUNT] [int] NOT NULL,
  [INVENTORYRECEIPTITEM_ITEMID] [int] NULL,
  [INVENTORYRECEIPTITEM_NOTE] [varchar](max) NULL,
  [INVENTORYRECEIPTITEM_ROWVERSION] [timestamp] NULL,
  CONSTRAINT [PK_tblInventoryReceiptItems] PRIMARY KEY CLUSTERED ([INVENTORYRECEIPTITEM_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IX_tblInventoryReceiptItems_ReceiptID]
  ON [dbo].[InventoryReceiptItems] ([INVENTORYRECEIPTITEM_RECEIPTID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[InventoryReceiptItems]
  ADD CONSTRAINT [FK_ReceiptItems_Receipts] FOREIGN KEY ([INVENTORYRECEIPTITEM_RECEIPTID]) REFERENCES [dbo].[InventoryReceipts] ([INVENTORYRECEIPT_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO