CREATE TABLE [dbo].[ProcessTypes] (
  [PROCESSTYPE_ID] [int] IDENTITY,
  [PROCESSTYPE_DESCRIPTION] [nvarchar](225) NOT NULL,
  CONSTRAINT [PK_ProcessTypes] PRIMARY KEY CLUSTERED ([PROCESSTYPE_ID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_ProcessTypes_Uniqueness]
  ON [dbo].[ProcessTypes] ([PROCESSTYPE_DESCRIPTION])
  ON [PRIMARY]
GO