CREATE TABLE [dbo].[Relationships] (
  [RELATIONSHIP_ID] [int] IDENTITY,
  [RELATIONSHIP_CLIENTID] [int] NOT NULL CONSTRAINT [DF_tblRelationships_RELATIONSHIP_CLIENTID] DEFAULT (0),
  [RELATIONSHIP_USERID] [int] NOT NULL CONSTRAINT [DF_tblRelationships_RELATIONSHIP_USERID] DEFAULT (0),
  [RELATIONSHIP_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Relationships] PRIMARY KEY CLUSTERED ([RELATIONSHIP_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [_dta_index_Relationships_5_1850489671__K3_K2]
  ON [dbo].[Relationships] ([RELATIONSHIP_USERID], [RELATIONSHIP_CLIENTID])
  ON [PRIMARY]
GO

CREATE INDEX [_dta_index_Relationships_6_1447676205__K3_2]
  ON [dbo].[Relationships] ([RELATIONSHIP_USERID])
  INCLUDE ([RELATIONSHIP_CLIENTID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Relationships_ClientID]
  ON [dbo].[Relationships] ([RELATIONSHIP_CLIENTID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_Relationships_Uniqueness]
  ON [dbo].[Relationships] ([RELATIONSHIP_CLIENTID], [RELATIONSHIP_USERID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_Relationships_UserID]
  ON [dbo].[Relationships] ([RELATIONSHIP_USERID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[Relationships]
  ADD CONSTRAINT [FK_Relationships_Clients] FOREIGN KEY ([RELATIONSHIP_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Relationships]
  ADD CONSTRAINT [FK_tblRelationships_tblUsers] FOREIGN KEY ([RELATIONSHIP_USERID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO