CREATE TABLE [dbo].[PieceTypes] (
  [PIECETYPE_ID] [int] IDENTITY,
  [PIECETYPE_NAME] [nvarchar](50) NOT NULL,
  [PIECETYPE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblPieceSizeTypes] PRIMARY KEY CLUSTERED ([PIECETYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_PieceTypes]
  ON [dbo].[PieceTypes] ([PIECETYPE_NAME])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO