CREATE TABLE [dbo].[JobProcessAssignments] (
  [ASSIGNMENT_ID] [int] IDENTITY,
  [ASSIGNMENT_ASSIGNED] [datetime] NULL,
  [ASSIGNMENT_ASSIGNEEID] [int] NOT NULL CONSTRAINT [DF_tblJobProcesses_PROCESS_ASSIGNEEID] DEFAULT (0),
  [ASSIGNMENT_BILLABLETIME] [nchar](25) NOT NULL CONSTRAINT [DF_tblJobProcessAssignments_ASSIGNMENT_BILLABLETIME] DEFAULT ('0:00:00'),
  [ASSIGNMENT_CANCELLED] [bit] NOT NULL CONSTRAINT [DF_tblJobProcesses_PROCESS_CANCELLED] DEFAULT (0),
  [ASSIGNMENT_CLOSED] [datetime] NULL,
  [ASSIGNMENT_JOBID] [int] NOT NULL CONSTRAINT [DF_tblJobProcesses_PROCESS_JOBID] DEFAULT (0),
  [ASSIGNMENT_PROCESSID] [uniqueidentifier] NOT NULL,
  [ASSIGNMENT_PROCESSTYPE] [int] NOT NULL CONSTRAINT [DF_tblJobProcessAssignments_ASSIGNMENT_PROCESSTYPE] DEFAULT (0),
  [ASSIGNMENT_ROLLEDBACK] [bit] NOT NULL CONSTRAINT [DF_tblJobProcessAssignments_ASSIGNMENT_ROLLEDBACK] DEFAULT (0),
  [ASSIGNMENT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblJobProcessAssignments] PRIMARY KEY CLUSTERED ([ASSIGNMENT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobProcessAssignments_AssigneeIDProcessType]
  ON [dbo].[JobProcessAssignments] ([ASSIGNMENT_ASSIGNEEID], [ASSIGNMENT_PROCESSTYPE])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobProcessAssignments_JobID]
  ON [dbo].[JobProcessAssignments] ([ASSIGNMENT_JOBID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO