CREATE TABLE [dbo].[SCFServiceAreas] (
  [SCFSERVICEAREA_ID] [int] IDENTITY,
  [SCFSERVICEAREA_SCFID] [int] NOT NULL,
  [SCFSERVICEAREA_START] [char](3) NOT NULL,
  [SCFSERVICEAREA_END] [char](3) NOT NULL,
  CONSTRAINT [PK_SCFServiceAreas] PRIMARY KEY CLUSTERED ([SCFSERVICEAREA_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_SCFServiceAreas_ScfID]
  ON [dbo].[SCFServiceAreas] ([SCFSERVICEAREA_SCFID])
  INCLUDE ([SCFSERVICEAREA_START], [SCFSERVICEAREA_END])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SCFServiceAreas_Start]
  ON [dbo].[SCFServiceAreas] ([SCFSERVICEAREA_START])
  INCLUDE ([SCFSERVICEAREA_END], [SCFSERVICEAREA_SCFID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCFServiceAreas]
  ADD CONSTRAINT [FK_SCFServiceAreas_SCFs] FOREIGN KEY ([SCFSERVICEAREA_SCFID]) REFERENCES [dbo].[SCFs] ([SCF_ID]) ON DELETE CASCADE
GO