CREATE TABLE [dbo].[Operations] (
  [OPERATION_ID] [int] IDENTITY,
  [OPERATION_CODE] [int] NOT NULL,
  [OPERATION_CUTOFF] [time](0) NULL,
  [OPERATION_DESCRIPTION] [nvarchar](50) NOT NULL,
  [OPERATION_MACHINEID] [int] NOT NULL,
  [OPERATION_MAILLEVELID] [int] NOT NULL,
  [OPERATION_MAILPHASEID] [int] NOT NULL,
  [OPERATION_MAILTYPEID] [int] NOT NULL,
  [OPERATION_OPERATIONTYPEID] [int] NOT NULL,
  [OPERATION_PROCESSTYPEID] [int] NOT NULL,
  CONSTRAINT [PK_Operations] PRIMARY KEY CLUSTERED ([OPERATION_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Operations_ID_Cutoff]
  ON [dbo].[Operations] ([OPERATION_ID])
  INCLUDE ([OPERATION_CUTOFF])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_Machines] FOREIGN KEY ([OPERATION_MACHINEID]) REFERENCES [dbo].[Machines] ([MACHINE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_MailLevels] FOREIGN KEY ([OPERATION_MAILLEVELID]) REFERENCES [dbo].[MailLevels] ([MAILLEVEL_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_MailPhases] FOREIGN KEY ([OPERATION_MAILPHASEID]) REFERENCES [dbo].[MailPhases] ([MAILPHASE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_MailTypes] FOREIGN KEY ([OPERATION_MAILTYPEID]) REFERENCES [dbo].[MailTypes] ([MAILTYPE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_OperationTypes] FOREIGN KEY ([OPERATION_OPERATIONTYPEID]) REFERENCES [dbo].[OperationTypes] ([OPERATIONTYPE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Operations]
  ADD CONSTRAINT [FK_Operations_ProcessTypes] FOREIGN KEY ([OPERATION_PROCESSTYPEID]) REFERENCES [dbo].[ProcessTypes] ([PROCESSTYPE_ID]) ON DELETE CASCADE
GO