CREATE TABLE [dbo].[MailPieces] (
  [MAILPIECE_ID] [int] IDENTITY (-2147483648, 1),
  [MAILPIECE_ADDRESS1] [nvarchar](60) NULL,
  [MAILPIECE_ADDRESS2] [nvarchar](60) NULL,
  [MAILPIECE_ADDRESS3] [nvarchar](60) NULL,
  [MAILPIECE_CITY] [nvarchar](28) NULL,
  [MAILPIECE_COMPANY] [nvarchar](50) NULL,
  [MAILPIECE_FIRSTNAME] [nvarchar](20) NULL,
  [MAILPIECE_GROUPID] [nvarchar](25) NULL,
  [MAILPIECE_INDIVIDUALID] [nvarchar](25) NULL,
  [MAILPIECE_LASTNAME] [nvarchar](20) NULL,
  [MAILPIECE_SEGMENTID] [int] NOT NULL,
  [MAILPIECE_ROUTINGCODE] [char](11) NOT NULL,
  [MAILPIECE_SCFID] [int] NOT NULL,
  [MAILPIECE_STATE] [char](2) NULL,
  [MAILPIECE_TITLE] [nvarchar](50) NULL,
  [MAILPIECE_TRACKINGCODE] [char](20) NOT NULL,
  [MAILPIECE_ZIPCODE] [char](5) NULL,
  [MAILPIECE_ZIPCODEEXT] [char](4) NULL,
  [MAILPIECE_CRRT] [char](4) NULL,
  [MAILPIECE_FINALIZESCANID] [int] NULL,
  [MAILPIECE_FORWARDSCANID] [int] NULL,
  [MAILPIECE_RETURNSCANID] [int] NULL,
  [MAILPIECE_FIRSTSCANID] [int] NULL,
  [MAILPIECE_LASTSCANID] [int] NULL,
  [MAILPIECE_TARGETID] [int] NULL,
  [MAILPIECE_DELIVERYDATE] [date] NULL,
  CONSTRAINT [PK_MailPieces] PRIMARY KEY CLUSTERED ([MAILPIECE_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_MailPieces_Barcode]
  ON [dbo].[MailPieces] ([MAILPIECE_TRACKINGCODE], [MAILPIECE_ROUTINGCODE])
  INCLUDE ([MAILPIECE_ID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_MailPieces_SegmentID]
  ON [dbo].[MailPieces] ([MAILPIECE_SEGMENTID])
  INCLUDE ([MAILPIECE_ID], [MAILPIECE_ADDRESS1], [MAILPIECE_ADDRESS2], [MAILPIECE_ADDRESS3], [MAILPIECE_CITY], [MAILPIECE_COMPANY], [MAILPIECE_CRRT], [MAILPIECE_DELIVERYDATE], [MAILPIECE_FINALIZESCANID], [MAILPIECE_FIRSTNAME], [MAILPIECE_FIRSTSCANID], [MAILPIECE_FORWARDSCANID], [MAILPIECE_GROUPID], [MAILPIECE_INDIVIDUALID], [MAILPIECE_LASTNAME], [MAILPIECE_LASTSCANID], [MAILPIECE_RETURNSCANID], [MAILPIECE_ROUTINGCODE], [MAILPIECE_SCFID], [MAILPIECE_STATE], [MAILPIECE_TITLE], [MAILPIECE_TRACKINGCODE], [MAILPIECE_ZIPCODE], [MAILPIECE_ZIPCODEEXT])
  ON [PRIMARY]
GO

CREATE INDEX [IX_MailPieces_TargetID]
  ON [dbo].[MailPieces] ([MAILPIECE_TARGETID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_MailPieces_Uniqueness]
  ON [dbo].[MailPieces] ([MAILPIECE_SEGMENTID], [MAILPIECE_TRACKINGCODE], [MAILPIECE_ROUTINGCODE])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[MailPieces]
  ADD CONSTRAINT [FK_MailPieces_CampaignUsers] FOREIGN KEY ([MAILPIECE_TARGETID]) REFERENCES [dbo].[CampaignUsers] ([Id]) ON DELETE SET NULL
GO

ALTER TABLE [dbo].[MailPieces] WITH NOCHECK
  ADD CONSTRAINT [FK_MailPieces_MailSegments] FOREIGN KEY ([MAILPIECE_SEGMENTID]) REFERENCES [dbo].[MailSegments] ([MAILSEGMENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MailPieces] WITH NOCHECK
  ADD CONSTRAINT [FK_MailPieces_SCFs] FOREIGN KEY ([MAILPIECE_SCFID]) REFERENCES [dbo].[SCFs] ([SCF_ID]) ON DELETE CASCADE
GO