CREATE TABLE [dbo].[Machines] (
  [MACHINE_ID] [int] IDENTITY,
  [MACHINE_CODE] [char](10) NOT NULL,
  [MACHINE_DESCRIPTION] [nvarchar](50) NULL,
  CONSTRAINT [PK_MachineTypes] PRIMARY KEY CLUSTERED ([MACHINE_ID])
)
ON [PRIMARY]
GO