CREATE TABLE [dbo].[SegmentTypes] (
  [SEGMENTTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [SEGMENTTYPE_NAME] [varchar](max) NOT NULL,
  CONSTRAINT [PK_SegmentTypes] PRIMARY KEY CLUSTERED ([SEGMENTTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO