CREATE TABLE [dbo].[JobStageAssignments] (
  [ASSIGNMENT_ID] [int] IDENTITY,
  [ASSIGNMENT_ASSIGNED] [datetime] NULL,
  [ASSIGNMENT_CLOSED] [datetime] NULL,
  [ASSIGNMENT_JOBID] [int] NOT NULL CONSTRAINT [DF_tblJobStageAssignments_ASSIGNMENT_JOBID] DEFAULT (0),
  [ASSIGNMENT_STAGEGUID] [uniqueidentifier] NOT NULL,
  [ASSIGNMENT_USERID] [int] NOT NULL CONSTRAINT [DF_tblJobStageAssignments_ASSIGNMENT_USERID] DEFAULT (0),
  [ASSIGNMENT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblJobStageAssignments] PRIMARY KEY CLUSTERED ([ASSIGNMENT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobStageAssignmentsJobID]
  ON [dbo].[JobStageAssignments] ([ASSIGNMENT_JOBID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobStageAssignmentsUserID]
  ON [dbo].[JobStageAssignments] ([ASSIGNMENT_USERID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[JobStageAssignments] WITH NOCHECK
  ADD CONSTRAINT [FK_JobStageAssignments_Jobs] FOREIGN KEY ([ASSIGNMENT_JOBID]) REFERENCES [dbo].[Jobs] ([JOB_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[JobStageAssignments] WITH NOCHECK
  ADD CONSTRAINT [FK_tblJobStageAssignments_tblUsers] FOREIGN KEY ([ASSIGNMENT_USERID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO