CREATE TABLE [dbo].[MailSegments] (
  [MAILSEGMENT_ID] [int] IDENTITY,
  [MAILSEGMENT_BILLINGSTATUS] [int] NULL,
  [MAILSEGMENT_COMMENTTHREADID] [int] NULL,
  [MAILSEGMENT_COMMINGLERID] [int] NULL,
  [MAILSEGMENT_COMMINGLERSEGMENTID] [int] NULL,
  [MAILSEGMENT_COMPLETEMAIL] [bit] NULL,
  [MAILSEGMENT_CREATED] [datetime] NOT NULL,
  [MAILSEGMENT_CREATEDBYID] [int] NOT NULL,
  [MAILSEGMENT_CRIDID] [int] NULL,
  [MAILSEGMENT_DATADUE] [date] NULL,
  [MAILSEGMENT_DESCRIPTION] [nvarchar](500) NULL,
  [MAILSEGMENT_DESTINATIONANALYSIS] [int] NULL,
  [MAILSEGMENT_DROPDATE] [date] NULL,
  [MAILSEGMENT_ENTRYPOINT] [char](5) NULL,
  [MAILSEGMENT_ESTQTY] [int] NULL,
  [MAILSEGMENT_JOBID] [int] NOT NULL,
  [MAILSEGMENT_ISMAILANYWHERE] [bit] NULL,
  [MAILSEGMENT_MAILANYWHEREACCTNO] [varchar](50) NULL,
  [MAILSEGMENT_MAILSTREAMID] [int] NULL,
  [MAILSEGMENT_MATCHMAIL] [bit] NULL,
  [MAILSEGMENT_MATERIALDUE] [date] NULL,
  [MAILSEGMENT_METERRATE] [float] NULL,
  [MAILSEGMENT_NAME] [nvarchar](50) NOT NULL,
  [MAILSEGMENT_NONPROFIT] [bit] NULL,
  [MAILSEGMENT_OUTGOING] [bit] NOT NULL,
  [MAILSEGMENT_PERMITID] [int] NULL,
  [MAILSEGMENT_PIECEHEIGHT] [float] NULL,
  [MAILSEGMENT_PIECELENGTH] [float] NULL,
  [MAILSEGMENT_PIECETHICKNESS] [float] NULL,
  [MAILSEGMENT_PIECETYPEID] [int] NULL,
  [MAILSEGMENT_PIECEWEIGHT] [float] NULL,
  [MAILSEGMENT_POSTAGEAPPLIEDID] [int] NULL,
  [MAILSEGMENT_POSTALCLASSID] [int] NULL,
  [MAILSEGMENT_SPECIALPREPARATION] [int] NULL,
  [MAILSEGMENT_TARGETDATE] [date] NULL,
  [MAILSEGMENT_TRACKINGTYPEID] [int] NOT NULL,
  [MAILSEGMENT_ROWVERSION] [timestamp],
  [MAILSEGMENT_SEGMENTTYPEID] [int] NULL,
  [MAILSEGMENT_ACCESSIBILITYLEVELID] [int] NOT NULL,
  [MAILSEGMENT_FIRSTFINALIZESCANID] [int] NULL,
  [MAILSEGMENT_FIRSTSCANID] [int] NULL,
  [MAILSEGMENT_LASTSCANID] [int] NULL,
  [MAILSEGMENT_LASTFINALIZESCANID] [int] NULL,
  [MAILSEGMENT_PRESORTED] [bit] NULL,
  [MAILSEGMENT_BILLINGINVOICEID] [int] NULL,
  CONSTRAINT [PK_MailSegments] PRIMARY KEY CLUSTERED ([MAILSEGMENT_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [_dta_index_MailSegments_6_1602872827__K1]
  ON [dbo].[MailSegments] ([MAILSEGMENT_ID])
  ON [PRIMARY]
GO

CREATE INDEX [_dta_index_MailSegments_6_631673298__K12_9]
  ON [dbo].[MailSegments] ([MAILSEGMENT_JOBID])
  INCLUDE ([MAILSEGMENT_DROPDATE])
  ON [PRIMARY]
GO

CREATE INDEX [_dta_index_MailSegments_6_631673298__K12_K1_2_3_4_5_6_7_8_9_10_11_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_]
  ON [dbo].[MailSegments] ([MAILSEGMENT_JOBID], [MAILSEGMENT_ID])
  INCLUDE ([MAILSEGMENT_COMMINGLERID], [MAILSEGMENT_COMPLETEMAIL], [MAILSEGMENT_CREATED], [MAILSEGMENT_CREATEDBYID], [MAILSEGMENT_DATADUE], [MAILSEGMENT_DESCRIPTION], [MAILSEGMENT_DESTINATIONANALYSIS], [MAILSEGMENT_DROPDATE], [MAILSEGMENT_ENTRYPOINT], [MAILSEGMENT_ESTQTY], [MAILSEGMENT_MAILSTREAMID], [MAILSEGMENT_MATCHMAIL], [MAILSEGMENT_MATERIALDUE], [MAILSEGMENT_METERRATE], [MAILSEGMENT_NAME], [MAILSEGMENT_NONPROFIT], [MAILSEGMENT_OUTGOING], [MAILSEGMENT_PERMITID], [MAILSEGMENT_PIECEHEIGHT], [MAILSEGMENT_PIECELENGTH], [MAILSEGMENT_PIECETHICKNESS], [MAILSEGMENT_PIECETYPEID], [MAILSEGMENT_PIECEWEIGHT], [MAILSEGMENT_POSTAGEAPPLIEDID], [MAILSEGMENT_POSTALCLASSID], [MAILSEGMENT_SPECIALPREPARATION], [MAILSEGMENT_TARGETDATE], [MAILSEGMENT_TRACKINGTYPEID], [MAILSEGMENT_ROWVERSION], [MAILSEGMENT_SEGMENTTYPEID], [MAILSEGMENT_ACCESSIBILITYLEVELID], [MAILSEGMENT_FIRSTFINALIZESCANID], [MAILSEGMENT_FIRSTSCANID], [MAILSEGMENT_LASTSCANID], [MAILSEGMENT_LASTFINALIZESCANID], [MAILSEGMENT_PRESORTED])
  ON [PRIMARY]
GO

CREATE INDEX [IX_MailSegments_DropDate]
  ON [dbo].[MailSegments] ([MAILSEGMENT_DROPDATE])
  INCLUDE ([MAILSEGMENT_ID], [MAILSEGMENT_JOBID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_MailSegments_MailingID]
  ON [dbo].[MailSegments] ([MAILSEGMENT_JOBID])
  INCLUDE ([MAILSEGMENT_ID], [MAILSEGMENT_COMMINGLERID], [MAILSEGMENT_COMPLETEMAIL], [MAILSEGMENT_CREATED], [MAILSEGMENT_CREATEDBYID], [MAILSEGMENT_ACCESSIBILITYLEVELID], [MAILSEGMENT_POSTALCLASSID], [MAILSEGMENT_PRESORTED], [MAILSEGMENT_SPECIALPREPARATION], [MAILSEGMENT_TRACKINGTYPEID], [MAILSEGMENT_ROWVERSION], [MAILSEGMENT_SEGMENTTYPEID], [MAILSEGMENT_PIECEHEIGHT], [MAILSEGMENT_PIECELENGTH], [MAILSEGMENT_PIECETHICKNESS], [MAILSEGMENT_PIECETYPEID], [MAILSEGMENT_PIECEWEIGHT], [MAILSEGMENT_POSTAGEAPPLIEDID], [MAILSEGMENT_MATERIALDUE], [MAILSEGMENT_METERRATE], [MAILSEGMENT_NAME], [MAILSEGMENT_NONPROFIT], [MAILSEGMENT_OUTGOING], [MAILSEGMENT_PERMITID], [MAILSEGMENT_FIRSTFINALIZESCANID], [MAILSEGMENT_FIRSTSCANID], [MAILSEGMENT_LASTFINALIZESCANID], [MAILSEGMENT_LASTSCANID], [MAILSEGMENT_MAILSTREAMID], [MAILSEGMENT_MATCHMAIL], [MAILSEGMENT_DATADUE], [MAILSEGMENT_DESCRIPTION], [MAILSEGMENT_DESTINATIONANALYSIS], [MAILSEGMENT_DROPDATE], [MAILSEGMENT_ENTRYPOINT], [MAILSEGMENT_ESTQTY])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_MailSegments_Uniqueness]
  ON [dbo].[MailSegments] ([MAILSEGMENT_JOBID], [MAILSEGMENT_NAME])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[MailSegments]
  ADD CONSTRAINT [FK_MailSegments_BillingStatuses] FOREIGN KEY ([MAILSEGMENT_BILLINGSTATUS]) REFERENCES [dbo].[BillingStatuses] ([Id])
GO

ALTER TABLE [dbo].[MailSegments] WITH NOCHECK
  ADD CONSTRAINT [FK_MailSegments_Jobs] FOREIGN KEY ([MAILSEGMENT_JOBID]) REFERENCES [dbo].[Jobs] ([JOB_ID])
GO

ALTER TABLE [dbo].[MailSegments]
  ADD CONSTRAINT [FK_MailSegments_SegmentTypes] FOREIGN KEY ([MAILSEGMENT_SEGMENTTYPEID]) REFERENCES [dbo].[SegmentTypes] ([SEGMENTTYPE_ID])
GO