CREATE TABLE [dbo].[ProjectInventoryItems] (
  [PROJECTINVENTORYITEM_ID] [int] IDENTITY,
  [PROJECTINVENTORYITEM_ITEMID] [int] NOT NULL,
  [PROJECTINVENTORYITEM_PROJECTID] [int] NOT NULL,
  CONSTRAINT [PK_ProjectInventoryItems] PRIMARY KEY CLUSTERED ([PROJECTINVENTORYITEM_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_ProjectInventoryItems_ItemID]
  ON [dbo].[ProjectInventoryItems] ([PROJECTINVENTORYITEM_ITEMID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_ProjectInventoryItems_ProjectID]
  ON [dbo].[ProjectInventoryItems] ([PROJECTINVENTORYITEM_PROJECTID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_ProjectInventoryItems_Uniqueness]
  ON [dbo].[ProjectInventoryItems] ([PROJECTINVENTORYITEM_PROJECTID], [PROJECTINVENTORYITEM_ITEMID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[ProjectInventoryItems]
  ADD CONSTRAINT [FK_ProjectInventoryItems_InventoryItems] FOREIGN KEY ([PROJECTINVENTORYITEM_ITEMID]) REFERENCES [dbo].[InventoryItems] ([ID]) ON DELETE CASCADE
GO