CREATE TABLE [dbo].[PostageRates] (
  [POSTAGERATE_ID] [int] IDENTITY,
  [POSTAGERATE_DESCRIPTION] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblPostageRates_POSTAGERATE_DESCRIPTION] DEFAULT (''),
  [POSTAGERATE_NONPROFIT] [bit] NOT NULL,
  [POSTAGERATE_RATE] [decimal](5, 3) NOT NULL,
  [POSTAGERATE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblPostageRates] PRIMARY KEY CLUSTERED ([POSTAGERATE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO