CREATE TABLE [dbo].[colpenn_SourceRecords] (
  [SOURCERECORD_ID] [int] IDENTITY,
  [SOURCERECORD_TITLE] [nchar](4) NOT NULL,
  [SOURCERECORD_FIRSTNAME] [nchar](20) NOT NULL,
  [SOURCERECORD_MIDDLENAME] [nchar](20) NOT NULL,
  [SOURCERECORD_LASTNAME] [nchar](20) NOT NULL,
  [SOURCERECORD_SUFFIX] [nchar](4) NOT NULL,
  [SOURCERECORD_STREET1] [nchar](30) NOT NULL,
  [SOURCERECORD_STREET2] [nchar](30) NOT NULL,
  [SOURCERECORD_CITY] [nchar](20) NOT NULL,
  [SOURCERECORD_STATE] [nchar](2) NOT NULL,
  [SOURCERECORD_ZIP5] [nchar](5) NOT NULL,
  [SOURCERECORD_ZIP4] [nchar](4) NOT NULL,
  [SOURCERECORD_PHONEAREA] [nchar](3) NOT NULL,
  [SOURCERECORD_PHONEEXCHANGE] [nchar](3) NOT NULL,
  [SOURCERECORD_PHONENUMBER] [nchar](4) NOT NULL,
  [SOURCERECORD_GENDER] [nchar](1) NOT NULL,
  [SOURCERECORD_BIRDTHDATECENTURY] [nchar](2) NOT NULL,
  [SOURCERECORD_BIRTHDATEYEAR] [nchar](2) NOT NULL,
  [SOURCERECORD_BIRTHDATEMONTH] [nchar](2) NOT NULL,
  [SOURCERECORD_BIRTHDATEDAY] [nchar](2) NOT NULL,
  [SOURCERECORD_LINEOFBUSINESS] [nchar](1) NOT NULL,
  [SOURCERECORD_TRANTYPE] [nchar](1) NOT NULL,
  [SOURCERECORD_COVERAGECODE] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE1] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE2] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE3] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE4] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE5] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE6] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE7] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE8] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE9] [nchar](1) NOT NULL,
  [SOURCERECORD_SOURCECODE10] [nchar](1) NOT NULL,
  [SOURCERECORD_PRODUCTCODE] [nchar](2) NOT NULL,
  [SOURCERECORD_REPID] [nchar](9) NOT NULL,
  [SOURCERECORD_MEMBERNUMBER] [nchar](7) NOT NULL,
  [SOURCERECORD_CREATIVECODE] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLLETTER] [nchar](6) NOT NULL,
  [SOURCERECORD_CALLDATECENTURY] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLDATEYEAR] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLDATEMONTH] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLDATEDAY] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLTIMEHOUR] [nchar](2) NOT NULL,
  [SOURCERECORD_CALLTIMEMINUTE] [nchar](2) NOT NULL,
  [SOURCERECORD_TIMEZONE] [nchar](1) NOT NULL,
  [SOURCERECORD_SEQNUMBER] [nchar](7) NOT NULL,
  [SOURCERECORD_REFERRERTITLE] [nchar](4) NOT NULL,
  [SOURCERECORD_REFERRERFIRST] [nchar](20) NOT NULL,
  [SOURCERECORD_REFERRERLAST] [nchar](20) NOT NULL,
  [SOURCERECORD_REFERRERSUFFIX] [nchar](4) NOT NULL,
  [SOURCERECORD_REFERRERUSEIND] [nchar](1) NOT NULL,
  [SOURCERECORD_TRANSACTIONDATE] [datetime] NOT NULL,
  CONSTRAINT [PK_SourceRecords] PRIMARY KEY CLUSTERED ([SOURCERECORD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_CoverageCode]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_COVERAGECODE])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode1]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE1])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode10]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE10])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode2]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE2])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode3]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE3])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode4]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE4])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode5]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE5])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode6]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE6])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode7]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE7])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode8]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE8])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_SourceCode9]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_SOURCECODE9])
  ON [PRIMARY]
GO

CREATE INDEX [IX_SourceRecords_TransactionDate]
  ON [dbo].[colpenn_SourceRecords] ([SOURCERECORD_TRANSACTIONDATE])
  ON [PRIMARY]
GO