CREATE TABLE [dbo].[OutputFiles] (
  [OUTPUTFILE_ID] [int] IDENTITY,
  [OUTPUTFILE_DESCRIPTION] [nvarchar](4000) NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_DESCRIPTION] DEFAULT (''),
  [OUTPUTFILE_FOLDER] [nvarchar](2000) NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_FOLDER] DEFAULT (0),
  [OUTPUTFILE_LINES] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_LINES] DEFAULT (0),
  [OUTPUTFILE_NAME] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_NAME] DEFAULT (''),
  [OUTPUTFILE_PACKAGEID] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_PACKAGEID] DEFAULT (0),
  [OUTPUTFILE_POSTED] [datetime] NULL,
  [OUTPUTFILE_POSTEDBYID] [int] NOT NULL CONSTRAINT [DF_Table_1_OUTPUTFILE_POSTEDBYIF] DEFAULT (0),
  [OUTPUTFILE_PROCESSASSIGNMENTID] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_PROCESSASSIGNMENTID] DEFAULT (0),
  [OUTPUTFILE_QUANTITY] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_QUANTITY] DEFAULT (0),
  [OUTPUTFILE_TARGETID] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_TARGETID] DEFAULT (0),
  [OUTPUTFILE_TYPEID] [int] NOT NULL CONSTRAINT [DF_tblOutputFiles_OUTPUTFILE_TYPEID] DEFAULT (0),
  [OUTPUTFILE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblOutputFiles] PRIMARY KEY CLUSTERED ([OUTPUTFILE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_tblOutputFiles_PackageID]
  ON [dbo].[OutputFiles] ([OUTPUTFILE_PACKAGEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_tblOutputFiles_PostedByID]
  ON [dbo].[OutputFiles] ([OUTPUTFILE_POSTEDBYID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO