CREATE TABLE [dbo].[MailLevels] (
  [MAILLEVEL_ID] [int] IDENTITY,
  [MAILLEVEL_DESCRIPTION] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_MailLevels] PRIMARY KEY CLUSTERED ([MAILLEVEL_ID])
)
ON [PRIMARY]
GO