CREATE TABLE [dbo].[InventoryItemTypes] (
  [INVENTORYITEMTYPE_ID] [int] NOT NULL,
  [INVENTORYITEMTYPE_ISCONTAINER] [bit] NOT NULL CONSTRAINT [DF_tblInventoryItemTypes_INVENTORYITEMTYPE_ISOSE] DEFAULT (0),
  [INVENTORYITEMTYPE_ISSELFMAILER] [bit] NOT NULL,
  [INVENTORYITEMTYPE_NAME] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_InsertItemTypes] PRIMARY KEY CLUSTERED ([INVENTORYITEMTYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_InventoryItemTypes_NameUniqueness]
  ON [dbo].[InventoryItemTypes] ([INVENTORYITEMTYPE_NAME])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO