CREATE TABLE [dbo].[MailTypes] (
  [MAILTYPE_ID] [int] IDENTITY,
  [MAILTYPE_DESCRIPTION] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_MailTypes] PRIMARY KEY CLUSTERED ([MAILTYPE_ID])
)
ON [PRIMARY]
GO