CREATE TABLE [dbo].[JobPriorities] (
  [JOBPRIORITY_ID] [int] IDENTITY,
  [JOBPRIORITY_NAME] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblJobPriorities_JOBPRIORITY_NAME] DEFAULT (''),
  [JOBPRIORITY_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblJobPriorities] PRIMARY KEY CLUSTERED ([JOBPRIORITY_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO