CREATE TABLE [dbo].[Log] (
  [LOG_ID] [int] IDENTITY (-2147483648, 1),
  [LOG_ACTION] [int] NULL,
  [LOG_DATETIME] [datetime] NOT NULL CONSTRAINT [DF_Table_1_LOGIN_DATETIME] DEFAULT (getdate()),
  [LOG_IPADDRESS] [varbinary](8) NULL,
  [LOG_IPCITYNAME] [nvarchar](100) NULL,
  [LOG_IPCOUNTRYCODE] [char](2) NULL,
  [LOG_IPLATITUDE] [decimal](9, 6) NULL,
  [LOG_IPLONGITUDE] [decimal](9, 6) NULL,
  [LOG_IPPOSTALCODE] [varchar](15) NULL,
  [LOG_IPREGIONCODE] [char](2) NULL,
  [LOG_MESSAGE] [nvarchar](500) NOT NULL CONSTRAINT [DF_tblLog_LOG_MESSAGE] DEFAULT (''),
  [LOG_QUERY] [nvarchar](2000) NULL,
  [LOG_SCREEN] [varchar](200) NULL,
  [LOG_SERVERNAME] [nvarchar](50) NULL,
  [LOG_SESSIONID] [nvarchar](24) NULL,
  [LOG_SEVERITY] [int] NOT NULL CONSTRAINT [DF_tblLog_LOG_TYPE] DEFAULT (0),
  [LOG_URL] [nvarchar](2000) NULL,
  [LOG_USERID] [int] NULL CONSTRAINT [DF_Table_1_LOGIN_USERID] DEFAULT (0),
  [LOG_USERAGENT] [nvarchar](500) NULL,
  [LOG_USERAGENTFINGERPRINT] [nvarchar](40) NULL,
  CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED ([LOG_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE STATISTICS [_dta_stat_391672443_18]
  ON [dbo].[Log] ([LOG_USERID])
GO

ALTER TABLE [dbo].[Log] WITH NOCHECK
  ADD CONSTRAINT [FK_Log_Users] FOREIGN KEY ([LOG_USERID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO