CREATE TABLE [dbo].[Facilities] (
  [FACILITY_ID] [int] IDENTITY,
  [FACILITY_AREAID] [int] NOT NULL,
  [FACILITY_NAME] [nvarchar](50) NOT NULL,
  [FACILITY_DISTRICTID] [int] NOT NULL,
  [FACILITY_FACILITYID] [int] NOT NULL,
  [FACILITY_FINANCENUMBER] [int] NOT NULL,
  [FACILITY_LOCALEID] [int] NOT NULL,
  [FACILITY_LATITUDE] [decimal](9, 6) NULL,
  [FACILITY_LONGITUDE] [decimal](9, 6) NULL,
  CONSTRAINT [PK_Facilities] PRIMARY KEY CLUSTERED ([FACILITY_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Facilities_FacilityID]
  ON [dbo].[Facilities] ([FACILITY_FACILITYID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[Facilities]
  ADD CONSTRAINT [FK_Facilities_Areas] FOREIGN KEY ([FACILITY_AREAID]) REFERENCES [dbo].[Areas] ([AREA_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Facilities]
  ADD CONSTRAINT [FK_Facilities_Districts] FOREIGN KEY ([FACILITY_DISTRICTID]) REFERENCES [dbo].[Districts] ([DISTRICT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Facilities]
  ADD CONSTRAINT [FK_Facilities_Locales] FOREIGN KEY ([FACILITY_LOCALEID]) REFERENCES [dbo].[Locales] ([LOCALE_ID]) ON DELETE CASCADE
GO