CREATE TABLE [dbo].[ServiceTypes] (
  [SERVICETYPE_ID] [int] IDENTITY,
  [SERVICETYPE_NAME] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblServiceTypes_SERVICETYPE_NAME] DEFAULT (''),
  [SERVICETYPE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_ServiceTypes] PRIMARY KEY CLUSTERED ([SERVICETYPE_ID])
)
ON [PRIMARY]
GO