CREATE TABLE [dbo].[WarehouseSections] (
  [SECTION_ID] [int] IDENTITY,
  [SECTION_NAME] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblWarehouseSections_WAREHOUSESECTION_NAME] DEFAULT (''),
  [SECTION_WAREHOUSEID] [int] NOT NULL CONSTRAINT [DF_tblWarehouseSections_WAREHOUSESECTION_WAREHOUSEID] DEFAULT (0),
  [SECTION_ROWVERSION] [timestamp],
  CONSTRAINT [PK_WarehouseSections] PRIMARY KEY CLUSTERED ([SECTION_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_WarehouseSections_WarehouseID]
  ON [dbo].[WarehouseSections] ([SECTION_WAREHOUSEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[WarehouseSections]
  ADD CONSTRAINT [FK_WarehouseSections_Warehouses] FOREIGN KEY ([SECTION_WAREHOUSEID]) REFERENCES [dbo].[Warehouses] ([WAREHOUSE_ID]) ON DELETE CASCADE
GO