CREATE TABLE [dbo].[Exceptions] (
  [EXCEPTION_ID] [int] IDENTITY (-2147483648, 1),
  [EXCEPTION_DATA] [nvarchar](max) NULL,
  [EXCEPTION_DATETIME] [datetime] NOT NULL,
  [EXCEPTION_EXCEPTIONSTACK] [nvarchar](max) NULL,
  [EXCEPTION_HOSTNAME] [nvarchar](50) NULL,
  [EXCEPTION_IPADDRESS] [varbinary](8) NOT NULL,
  [EXCEPTION_MESSAGE] [nvarchar](max) NOT NULL,
  [EXCEPTION_QUERY] [nvarchar](2000) NULL,
  [EXCEPTION_RESPONSESTATUS] [int] NULL,
  [EXCEPTION_SERVERNAME] [nvarchar](50) NOT NULL,
  [EXCEPTION_SOURCE] [nvarchar](100) NOT NULL,
  [EXCEPTION_TARGET] [nvarchar](500) NULL,
  [EXCEPTION_TYPE] [nvarchar](50) NOT NULL,
  [EXCEPTION_URL] [nvarchar](4000) NULL,
  [EXCEPTION_USERAGENT] [nvarchar](500) NULL,
  [EXCEPTION_USERID] [int] NULL,
  CONSTRAINT [PK_tblExceptions] PRIMARY KEY CLUSTERED ([EXCEPTION_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO