CREATE TABLE [dbo].[Roles] (
  [ROLE_ID] [int] NOT NULL,
  [ROLE_ISINTERNAL] [bit] NOT NULL,
  [ROLE_NAME] [nvarchar](max) NOT NULL,
  [ROLE_LEVEL] [int] NULL,
  CONSTRAINT [PK_Roles2] PRIMARY KEY CLUSTERED ([ROLE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO