CREATE TABLE [dbo].[WarehouseLocations] (
  [LOCATION_ID] [int] IDENTITY,
  [LOCATION_DESCRIPTION] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblWarehouseLocations_WAREHOUSELOCATION_NAME] DEFAULT (''),
  [LOCATION_HORIZONTALPOS] [int] NOT NULL,
  [LOCATION_SHELFID] [int] NOT NULL CONSTRAINT [DF_tblWarehouseLocations_WAREHOUSELOCATION_SHELFID] DEFAULT (0),
  [LOCATION_ROWVERSION] [timestamp],
  CONSTRAINT [PK_WarehouseLocations] PRIMARY KEY CLUSTERED ([LOCATION_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_WarehouseLocations_ShelfID]
  ON [dbo].[WarehouseLocations] ([LOCATION_SHELFID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[WarehouseLocations]
  ADD CONSTRAINT [FK_WarehouseLocations_WarehouseShelves] FOREIGN KEY ([LOCATION_SHELFID]) REFERENCES [dbo].[WarehouseShelves] ([SHELF_ID]) ON DELETE CASCADE
GO