CREATE TABLE [dbo].[Users] (
  [USER_USERID] [int] IDENTITY,
  [USER_ADDRESS1] [nvarchar](100) NULL,
  [USER_ADDRESS2] [nvarchar](100) NULL,
  [USER_CITY] [nvarchar](50) NULL,
  [USER_CLIENT_ID] [int] NULL CONSTRAINT [DF_tblUsers_USER_CLIENT_ID] DEFAULT (0),
  [USER_CREATED] [datetime] NOT NULL,
  [USER_CREATEDBY_ID] [int] NOT NULL CONSTRAINT [DF_tblUsers_USER_CREATED_BY] DEFAULT (0),
  [USER_DEFAULTURL] [nvarchar](200) NULL,
  [USER_DISPLAYNAME] [nvarchar](50) NULL,
  [USER_FAX] [char](15) NULL,
  [USER_FIRSTNAME] [nvarchar](50) NULL,
  [USER_INACTIVELOGOUT] [int] NOT NULL,
  [USER_LASTNAME] [nvarchar](50) NULL,
  [USER_LOCKEDOUT] [bit] NOT NULL,
  [USER_PASSWORD] [varbinary](max) NOT NULL,
  [USER_PHONE] [char](15) NULL,
  [USER_POSTALCODE] [nchar](15) NULL,
  [USER_REGION] [nvarchar](50) NULL,
  [USER_ROLES] [int] NOT NULL,
  [USER_SECONDARY_EMAIL] [nvarchar](50) SPARSE NULL,
  [USER_USERNAME] [nvarchar](50) NOT NULL,
  [USER_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([USER_USERID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IX_Users_ClientID]
  ON [dbo].[Users] ([USER_CLIENT_ID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_Users_Uniqueness]
  ON [dbo].[Users] ([USER_USERNAME])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO