CREATE TABLE [dbo].[Warehouses] (
  [WAREHOUSE_ID] [int] IDENTITY,
  [WAREHOUSE_CLIENTLOCATIONID] [int] NOT NULL,
  [WAREHOUSE_NAME] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblWarehouses_WAREHOUSE_NAME] DEFAULT (''),
  [WAREHOUSE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Warehouses] PRIMARY KEY CLUSTERED ([WAREHOUSE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Warehouses]
  ADD CONSTRAINT [FK_Warehouses_ClientLocations] FOREIGN KEY ([WAREHOUSE_CLIENTLOCATIONID]) REFERENCES [dbo].[ClientLocations] ([Id])
GO