CREATE TABLE [dbo].[PostageUsageItems] (
  [POSTAGEUSAGEITEM_ID] [int] IDENTITY,
  [POSTAGEUSAGEITEM_DATETIME] [datetime] NOT NULL,
  [POSTAGEUSAGEITEM_PACKAGEID] [int] NOT NULL,
  [POSTAGEUSAGEITEM_QUANTITY] [int] NOT NULL,
  [POSTAGEUSAGEITEM_RATE] [float] NOT NULL,
  [POSTAGEUSAGEITEM_ROWVERSION] [timestamp],
  CONSTRAINT [PK_PostageUsageItems] PRIMARY KEY CLUSTERED ([POSTAGEUSAGEITEM_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_PostageUsageItems]
  ON [dbo].[PostageUsageItems] ([POSTAGEUSAGEITEM_PACKAGEID])
  ON [PRIMARY]
GO