CREATE TABLE [dbo].[NDCServiceAreas] (
  [NDCSERVICEAREA_ID] [int] IDENTITY,
  [NDCSERVICEAREA_NDCID] [int] NOT NULL,
  [NDCSERVICEAREA_START] [char](3) NOT NULL,
  [NDCSERVICEAREA_END] [char](3) NOT NULL,
  CONSTRAINT [PK_NDCServiceAreas] PRIMARY KEY CLUSTERED ([NDCSERVICEAREA_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_NDCServiceAreas]
  ON [dbo].[NDCServiceAreas] ([NDCSERVICEAREA_START], [NDCSERVICEAREA_END])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[NDCServiceAreas]
  ADD CONSTRAINT [FK_NDCServiceAreas_NDCs] FOREIGN KEY ([NDCSERVICEAREA_NDCID]) REFERENCES [dbo].[NDCs] ([NDC_ID]) ON DELETE CASCADE
GO