CREATE TABLE [dbo].[InventoryItemImages] (
  [INVENTORYITEMIMAGE_ID] [int] IDENTITY,
  [INVENTORYITEMIMAGE_CONTENTTYPE] [nvarchar](50) NULL,
  [INVENTORYITEMIMAGE_DATA] [varbinary](max) NOT NULL,
  [INVENTORYITEMIMAGE_FILEEXTENSION] [nvarchar](255) NULL,
  [INVENTORYITEMIMAGE_INDEX] [int] NOT NULL,
  [INVENTORYITEMIMAGE_INVENTORYITEMID] [int] NOT NULL,
  [INVENTORYITEMIMAGE_ISTHUMBNAIL] [bit] NOT NULL,
  [INVENTORYITEMIMAGE_LASTUPDATED] [datetime] NOT NULL,
  CONSTRAINT [PK_InventoryItemImages] PRIMARY KEY CLUSTERED ([INVENTORYITEMIMAGE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryItemImages_InventoryItemID]
  ON [dbo].[InventoryItemImages] ([INVENTORYITEMIMAGE_INVENTORYITEMID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_InventoryItemImages_Uniqueness]
  ON [dbo].[InventoryItemImages] ([INVENTORYITEMIMAGE_INVENTORYITEMID], [INVENTORYITEMIMAGE_INDEX], [INVENTORYITEMIMAGE_ISTHUMBNAIL])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[InventoryItemImages]
  ADD CONSTRAINT [FK_InventoryItemImages_InventoryItems] FOREIGN KEY ([INVENTORYITEMIMAGE_INVENTORYITEMID]) REFERENCES [dbo].[InventoryItems] ([ID]) ON DELETE CASCADE
GO