CREATE TABLE [dbo].[Responses] (
  [RESPONSE_ID] [int] IDENTITY (-2147483648, 1),
  [RESPONSE_ADDRESS1] [nvarchar](100) NULL,
  [RESPONSE_ADDRESS2] [nvarchar](100) NULL,
  [RESPONSE_ADDRESS3] [nvarchar](100) NULL,
  [RESPONSE_CITY] [nvarchar](50) NULL,
  [RESPONSE_COMPANY] [nvarchar](100) NULL,
  [RESPONSE_COUNTRYID] [int] NULL,
  [RESPONSE_EMAILADDRESS] [nvarchar](320) NULL,
  [RESPONSE_FIRSTNAME] [nvarchar](20) NULL,
  [RESPONSE_LASTNAME] [nvarchar](30) NULL,
  [RESPONSE_PHONE] [varchar](15) NULL,
  [RESPONSE_POSTALCODE] [varchar](15) NULL,
  [RESPONSE_REGION] [nvarchar](50) NULL,
  [RESPONSE_TARGETID] [int] NULL,
  [RESPONSE_TITLE] [nvarchar](100) NULL,
  [RESPONSE_UPDATED] [datetime] NOT NULL,
  [RESPONSE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Responses] PRIMARY KEY CLUSTERED ([RESPONSE_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Responses_TargetID]
  ON [dbo].[Responses] ([RESPONSE_TARGETID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[Responses]
  ADD CONSTRAINT [FK_Responses_CampaignTargets] FOREIGN KEY ([RESPONSE_TARGETID]) REFERENCES [dbo].[_CampaignTargets] ([TARGET_ID]) ON DELETE CASCADE
GO