CREATE TABLE [dbo].[Fonts] (
  [FONT_ID] [int] IDENTITY,
  [FONT_NAME] [nvarchar](75) NOT NULL CONSTRAINT [DF_tblFonts_FONT_NAME] DEFAULT (''),
  [FONT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblFonts] PRIMARY KEY CLUSTERED ([FONT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO