CREATE TABLE [dbo].[Requirements] (
  [REQUIREMENT_ID] [int] IDENTITY,
  [REQUIREMENT_TEXT] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblRequirements_REQUIREMENT_TEXT] DEFAULT (N'n""'),
  CONSTRAINT [PK_tblRequirements] PRIMARY KEY CLUSTERED ([REQUIREMENT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO