CREATE TABLE [dbo].[InventoryReceipts] (
  [INVENTORYRECEIPT_ID] [int] IDENTITY,
  [INVENTORYRECEIPT_CREATED] [datetime] NOT NULL,
  [INVENTORYRECEIPT_CREATEDBYID] [int] NOT NULL CONSTRAINT [DF_tblInventoryItemReceipts_INVENTORYITEMRECEIPT_ENTEREDBYID] DEFAULT (0),
  [INVENTORYRECEIPT_DESCRIPTION] [nvarchar](200) NULL,
  [INVENTORYRECEIPT_RECEIVED] [datetime] NOT NULL,
  [INVENTORYRECEIPT_RECEIVEDBY] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblInventoryItemReceipts_INVENTORYITEMRECEIPT_RECEIVEDBYID] DEFAULT (0),
  [INVENTORYRECEIPT_SHIPCOMPANY] [nvarchar](50) NOT NULL,
  [INVENTORYRECEIPT_SUPPLIERCOMPANY] [nvarchar](50) NULL CONSTRAINT [DF_tblInventoryReceipts_INVENTORYRECEIPT_SUPPLIERCOMPANY] DEFAULT (''),
  [INVENTORYRECEIPT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_InventoryItemReceipts] PRIMARY KEY CLUSTERED ([INVENTORYRECEIPT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryReceipts_ReceivedBy]
  ON [dbo].[InventoryReceipts] ([INVENTORYRECEIPT_RECEIVEDBY])
  ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryReceipts_ShipCompany]
  ON [dbo].[InventoryReceipts] ([INVENTORYRECEIPT_SHIPCOMPANY])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryReceipts_SupplierCompany]
  ON [dbo].[InventoryReceipts] ([INVENTORYRECEIPT_SUPPLIERCOMPANY])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[InventoryReceipts] WITH NOCHECK
  ADD CONSTRAINT [FK_InventoryReceipts_Users] FOREIGN KEY ([INVENTORYRECEIPT_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID])
GO