CREATE TABLE [dbo].[SystemAlerts] (
  [ALERT_ID] [int] IDENTITY,
  [ALERT_DISPLAYEND] [datetime] NOT NULL,
  [ALERT_DISPLAYSTART] [datetime] NOT NULL,
  [ALERT_MESSAGE] [nvarchar](500) NOT NULL CONSTRAINT [DF_tblSystemAlerts_ALERT_MESSAGE] DEFAULT (''),
  [ALERT_POSTED] [datetime] NOT NULL CONSTRAINT [DF_tblSystemAlerts_ALERT_POSTED] DEFAULT (getdate()),
  [ALERT_POSTEDBYID] [int] NOT NULL CONSTRAINT [DF_tblSystemAlerts_ALERT_POSTEDBY] DEFAULT (0),
  [ALERT_TITLE] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblSystemAlerts_ALERT_TITLE] DEFAULT (''),
  CONSTRAINT [PK_SystemAlerts] PRIMARY KEY CLUSTERED ([ALERT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO