CREATE TABLE [dbo].[EstimatePostageItems] (
  [ESTIMATEPOSTAGE_ID] [int] IDENTITY,
  [ESTIMATEPOSTAGE_DESCRIPTION] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_DESCRIPTION] DEFAULT (''),
  [ESTIMATEPOSTAGE_ESTIMATEID] [int] NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_ESTIMATEID] DEFAULT (0),
  [ESTIMATEPOSTAGE_EXTENDEDPRICE] [decimal](18, 5) NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_EXTENDEDPRICE] DEFAULT (0.0),
  [ESTIMATEPOSTAGE_NONPROFIT] [bit] NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_NONPROFIT] DEFAULT (0),
  [ESTIMATEPOSTAGE_PIECEWEIGHT] [decimal](5, 4) NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_PIECEWEIGHT] DEFAULT (0.0),
  [ESTIMATEPOSTAGE_QUANTITY] [int] NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_QUANTITY] DEFAULT (0),
  [ESTIMATEPOSTAGE_RATE] [decimal](5, 3) NOT NULL CONSTRAINT [DF_tblEstimatePostageItems_ESTIMATEPOSTAGE_RATE] DEFAULT (0.000),
  [ESTIMATEPOSTAGE_RATEDESCRIPTION] [nvarchar](100) NOT NULL,
  [ESTIMATEPOSTAGE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblEstimatePostageItems] PRIMARY KEY CLUSTERED ([ESTIMATEPOSTAGE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_EstimatePostageItems_EstimateID]
  ON [dbo].[EstimatePostageItems] ([ESTIMATEPOSTAGE_ESTIMATEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[EstimatePostageItems]
  ADD CONSTRAINT [FK_EstimatePostageItems_Estimates] FOREIGN KEY ([ESTIMATEPOSTAGE_ESTIMATEID]) REFERENCES [dbo].[Estimates] ([ESTIMATE_ID]) ON DELETE CASCADE
GO