CREATE TABLE [dbo].[PostOffices] (
  [POSTOFFICE_ID] [int] IDENTITY,
  [POSTOFFICE_PHONE] [nvarchar](10) NULL,
  [POSTOFFICE_FAX] [nvarchar](10) NULL,
  [POSTOFFICE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_PostOffices] PRIMARY KEY CLUSTERED ([POSTOFFICE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO