CREATE TABLE [dbo].[CustomPages] (
  [CUSTOMPAGE_ID] [int] IDENTITY,
  [CUSTOMPAGE_CLIENTID] [int] NOT NULL,
  [CUSTOMPAGE_DESCRIPTION] [nvarchar](2000) NULL,
  [CUSTOMPAGE_TITLE] [nvarchar](200) NOT NULL,
  [CUSTOMPAGE_URL] [nvarchar](2000) NOT NULL,
  [CUSTOMPAGE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_CustomPages] PRIMARY KEY CLUSTERED ([CUSTOMPAGE_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_CustomPages_ClientID]
  ON [dbo].[CustomPages] ([CUSTOMPAGE_CLIENTID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[CustomPages]
  ADD CONSTRAINT [FK_CustomPages_Clients] FOREIGN KEY ([CUSTOMPAGE_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO