CREATE TABLE [dbo].[InventoryAdjustments] (
  [ADJUSTMENT_ID] [int] IDENTITY (-2147483648, 1),
  [ADJUSTMENT_ADJUSTMENT] [int] NOT NULL CONSTRAINT [DF_tblInventoryAdjustments_INVENTORYADJUSTMENT_ADJUSTMENT] DEFAULT (0),
  [ADJUSTMENT_CREATED] [datetime] NOT NULL CONSTRAINT [DF_tblInventoryAdjustments_INVENTORYADJUSTMENT_ADJUSTED] DEFAULT (getdate()),
  [ADJUSTMENT_CREATEDBYID] [int] NOT NULL,
  [ADJUSTMENT_DESCRIPTION] [nvarchar](200) NOT NULL,
  [ADJUSTMENT_INVENTORYITEMID] [int] NOT NULL,
  [ADJUSTMENT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblInventoryAdjustments] PRIMARY KEY CLUSTERED ([ADJUSTMENT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryAdjustments_EnteredByID]
  ON [dbo].[InventoryAdjustments] ([ADJUSTMENT_CREATEDBYID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_InventoryAdjustments_InventoryItemID]
  ON [dbo].[InventoryAdjustments] ([ADJUSTMENT_INVENTORYITEMID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[InventoryAdjustments]
  ADD CONSTRAINT [FK_InventoryAdjustments_InventoryItems] FOREIGN KEY ([ADJUSTMENT_INVENTORYITEMID]) REFERENCES [dbo].[InventoryItems] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[InventoryAdjustments]
  ADD CONSTRAINT [FK_tblInventoryAdjustments_tblUsers] FOREIGN KEY ([ADJUSTMENT_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO