CREATE TABLE [dbo].[TabTypes] (
  [TABTYPE_ID] [int] IDENTITY,
  [TABTYPE_NAME] [nvarchar](20) NOT NULL CONSTRAINT [DF_tblTabTypes_TABTYPE_NAME] DEFAULT (''),
  [TABTYPE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblTabTypes] PRIMARY KEY CLUSTERED ([TABTYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO