CREATE TABLE [dbo].[Estimates] (
  [ESTIMATE_ID] [int] IDENTITY,
  [ESTIMATE_CLIENTID] [int] NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_CLIENTID] DEFAULT (0),
  [ESTIMATE_CONTACT] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_CONTACT] DEFAULT (''),
  [ESTIMATE_CSRID] [int] NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_CSRID] DEFAULT (0),
  [ESTIMATE_DATADUE] [datetime] NOT NULL,
  [ESTIMATE_DROPDATE] [datetime] NOT NULL,
  [ESTIMATE_ENTERED] [datetime] NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_ENTERED] DEFAULT (getdate()),
  [ESTIMATE_ENTEREDBYID] [int] NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_ENTEREDBYID] DEFAULT (0),
  [ESTIMATE_ESTIMATEDQTY] [int] NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_ESTIMATEDQTY] DEFAULT (0),
  [ESTIMATE_JOBNAME] [nvarchar](100) NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_JOBNAME] DEFAULT (''),
  [ESTIMATE_MATERIALDUE] [datetime] NOT NULL,
  [ESTIMATE_REFERENCE] [nvarchar](50) NOT NULL CONSTRAINT [DF_tblEstimates_ESTIMATE_REFERENCE] DEFAULT (''),
  [ESTIMATE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblEstimates] PRIMARY KEY CLUSTERED ([ESTIMATE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Estimates_ClientID]
  ON [dbo].[Estimates] ([ESTIMATE_CLIENTID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Estimates_CsrID]
  ON [dbo].[Estimates] ([ESTIMATE_CSRID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[Estimates]
  ADD CONSTRAINT [FK_Estimates_Clients] FOREIGN KEY ([ESTIMATE_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Estimates]
  ADD CONSTRAINT [FK_Estimates_Users] FOREIGN KEY ([ESTIMATE_CSRID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO