CREATE TABLE [fedex].[PackageTypes] (
  [PACKAGETYPE_ID] [int] NOT NULL,
  [PACKAGETYPE_NAME] [varchar](max) NOT NULL,
  CONSTRAINT [PK_PackageTypes] PRIMARY KEY CLUSTERED ([PACKAGETYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO