CREATE TABLE [fedex].[ServiceTypes] (
  [SERVICETYPE_ID] [int] NOT NULL,
  [SERVICETYPE_NAME] [varchar](max) NOT NULL,
  CONSTRAINT [PK_ServiceTypes_1] PRIMARY KEY CLUSTERED ([SERVICETYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO