CREATE TABLE [file].[FileLinks] (
  [LINK_ID] [int] IDENTITY (-2147483648, 1),
  [LINK_CREATED] [datetime] NOT NULL,
  [LINK_CREATEDBYID] [int] NOT NULL,
  [LINK_EMAILADDRESS] [nvarchar](320) NOT NULL,
  [LINK_KEY] [char](100) NOT NULL,
  [LINK_FILEID] [int] NOT NULL,
  CONSTRAINT [PK_FileDownloadLinks] PRIMARY KEY CLUSTERED ([LINK_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [file].[FileLinks]
  ADD CONSTRAINT [FK_FileLinks_Users] FOREIGN KEY ([LINK_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO