CREATE TABLE [file].[CommentFiles] (
  [FILE_ID] [int] IDENTITY,
  [FILE_CONTENTTYPEID] [int] NOT NULL,
  [FILE_COMPRESSED] [bit] NOT NULL,
  [FILE_DATA] [varbinary](max) NULL,
  [FILE_DESCRIPTION] [nvarchar](200) NULL,
  [FILE_NAME] [nvarchar](2000) NOT NULL,
  [FILE_SIZE] [bigint] NOT NULL CONSTRAINT [DF_FILES_FILE_SIZE_copy] DEFAULT (0),
  [FILE_TYPEID] [int] NOT NULL CONSTRAINT [DF_FILES_FILE_TYPE_ID_copy] DEFAULT (0),
  [FILE_UPLOADED] [datetime] NOT NULL CONSTRAINT [DF_FILES_FILE_UPLOADED_copy] DEFAULT (getdate()),
  [FILE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Files_copy] PRIMARY KEY CLUSTERED ([FILE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [file].[CommentFiles]
  ADD CONSTRAINT [FK_Files_ContentTypes_copy] FOREIGN KEY ([FILE_CONTENTTYPEID]) REFERENCES [file].[ContentTypes] ([CONTENTTYPE_ID])
GO

ALTER TABLE [file].[CommentFiles]
  ADD CONSTRAINT [FK_Files_FileTypes_copy] FOREIGN KEY ([FILE_TYPEID]) REFERENCES [file].[Types] ([TYPE_ID]) ON DELETE CASCADE
GO