CREATE TABLE [file].[Files] (
  [FILE_ID] [int] IDENTITY,
  [FILE_CONTENTTYPEID] [int] NOT NULL,
  [FILE_COMPRESSED] [bit] NOT NULL,
  [FILE_DATA] [varbinary](max) NULL,
  [FILE_DESCRIPTION] [nvarchar](200) NULL,
  [FILE_NAME] [nvarchar](2000) NOT NULL,
  [FILE_FOLDERID] [int] NOT NULL,
  [FILE_SIZE] [bigint] NOT NULL CONSTRAINT [DF_FILES_FILE_SIZE] DEFAULT (0),
  [FILE_TYPEID] [int] NOT NULL CONSTRAINT [DF_FILES_FILE_TYPE_ID] DEFAULT (0),
  [FILE_UPLOADED] [datetime] NOT NULL CONSTRAINT [DF_FILES_FILE_UPLOADED] DEFAULT (getdate()),
  [FILE_USERID] [int] NOT NULL,
  [FILE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED ([FILE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [file].[Files] WITH NOCHECK
  ADD CONSTRAINT [FK_FileMetaData_FileFolders] FOREIGN KEY ([FILE_FOLDERID]) REFERENCES [file].[Folders] ([FOLDER_ID]) ON DELETE CASCADE
GO

ALTER TABLE [file].[Files] WITH NOCHECK
  ADD CONSTRAINT [FK_Files_ContentTypes] FOREIGN KEY ([FILE_CONTENTTYPEID]) REFERENCES [file].[ContentTypes] ([CONTENTTYPE_ID])
GO

ALTER TABLE [file].[Files] WITH NOCHECK
  ADD CONSTRAINT [FK_Files_FileTypes] FOREIGN KEY ([FILE_TYPEID]) REFERENCES [file].[Types] ([TYPE_ID]) ON DELETE CASCADE
GO