CREATE TABLE [file].[FilePermissions] (
  [FILEPERMISSION_ID] [int] IDENTITY (-2147483488, 1),
  [FILEPERMISSION_METADATAID] [int] NOT NULL,
  [FILEPERMISSION_PRIVILEGES] [int] NULL,
  [FILEPERMISSION_USERID] [int] NOT NULL,
  [FILEPERMISSION_ROWVERSION] [timestamp],
  CONSTRAINT [PK_FileRelationships] PRIMARY KEY CLUSTERED ([FILEPERMISSION_ID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_FilePermissions_Uniqueness]
  ON [file].[FilePermissions] ([FILEPERMISSION_METADATAID], [FILEPERMISSION_USERID])
  ON [PRIMARY]
GO

ALTER TABLE [file].[FilePermissions]
  ADD CONSTRAINT [FK_FileRelationships_Files] FOREIGN KEY ([FILEPERMISSION_METADATAID]) REFERENCES [file].[Files] ([FILE_ID]) ON DELETE CASCADE
GO