CREATE TABLE [file].[FolderPermissions] (
  [FOLDERPERMISSION_ID] [int] IDENTITY (-2147483488, 1),
  [FOLDERPERMISSION_FOLDERID] [int] NOT NULL,
  [FOLDERPERMISSION_PRIVILEGES] [int] NULL,
  [FOLDERPERMISSION_USERID] [int] NOT NULL,
  [FOLDERPERMISSION_ROWVERSION] [timestamp],
  CONSTRAINT [PK_FolderPermissions] PRIMARY KEY CLUSTERED ([FOLDERPERMISSION_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [file].[FolderPermissions]
  ADD CONSTRAINT [FK_FolderPermissions_Folders] FOREIGN KEY ([FOLDERPERMISSION_FOLDERID]) REFERENCES [file].[Folders] ([FOLDER_ID]) ON DELETE CASCADE
GO