CREATE TABLE [file].[FileLinkDownloads] (
  [DOWNLOAD_ID] [int] IDENTITY (-2147483488, 1),
  [DOWNLOAD_DATETIME] [datetime] NOT NULL,
  [DOWNLOAD_LINKID] [int] NOT NULL,
  [DOWNLOAD_IPADDRESS] [varbinary](8) NOT NULL,
  [DOWNLOAD_IPCITYNAME] [nvarchar](100) NULL,
  [DOWNLOAD_IPCOUNTRYCODE] [char](2) NULL,
  [DOWNLOAD_IPLATITUDE] [decimal](9, 6) NULL,
  [DOWNLOAD_IPLONGITUDE] [decimal](9, 6) NULL,
  [DOWNLOAD_IPPOSTALCODE] [varchar](15) NULL,
  [DOWNLOAD_IPREGIONCODE] [char](2) NULL,
  [DOWNLOAD_USERAGENT] [nvarchar](4000) NULL,
  CONSTRAINT [PK_FileLinkDownloads] PRIMARY KEY CLUSTERED ([DOWNLOAD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_FileLinkDownloads_LinkID]
  ON [file].[FileLinkDownloads] ([DOWNLOAD_LINKID])
  ON [PRIMARY]
GO

ALTER TABLE [file].[FileLinkDownloads]
  ADD CONSTRAINT [FK_FileLinkDownloads_FileLinks] FOREIGN KEY ([DOWNLOAD_LINKID]) REFERENCES [file].[FileLinks] ([LINK_ID]) ON DELETE CASCADE
GO