CREATE TABLE [ip].[Blocks] (
  [BLOCK_ID] [int] IDENTITY (-2147483648, 1),
  [BLOCK_END] [bigint] NOT NULL,
  [BLOCK_LOCATIONID] [int] NOT NULL,
  [BLOCK_START] [bigint] NOT NULL,
  CONSTRAINT [PK_Blocks] PRIMARY KEY CLUSTERED ([BLOCK_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [_dta_index_Blocks_5_1604916789__K4_K2_K3]
  ON [ip].[Blocks] ([BLOCK_START], [BLOCK_END], [BLOCK_LOCATIONID])
  ON [PRIMARY]
GO

CREATE INDEX [IDX_Blocks_Covering]
  ON [ip].[Blocks] ([BLOCK_LOCATIONID], [BLOCK_END], [BLOCK_START])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Blocks]
  ON [ip].[Blocks] ([BLOCK_END], [BLOCK_START])
  INCLUDE ([BLOCK_LOCATIONID])
  ON [PRIMARY]
GO

ALTER TABLE [ip].[Blocks] WITH NOCHECK
  ADD CONSTRAINT [FK_Blocks_Locations] FOREIGN KEY ([BLOCK_LOCATIONID]) REFERENCES [ip].[Locations] ([LOCATION_ID])
GO