CREATE TABLE [ip].[Locations] (
  [LOCATION_ID] [int] IDENTITY,
  [LOCATION_COUNTRYCODE] [char](2) NOT NULL,
  [LOCATION_REGIONCODE] [char](2) NULL,
  [LOCATION_CITY] [nvarchar](100) NULL,
  [LOCATION_POSTALCODE] [char](15) NULL,
  [LOCATION_LATITUDE] [decimal](9, 6) NOT NULL,
  [LOCATION_LONGITUDE] [decimal](9, 6) NOT NULL,
  CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED ([LOCATION_ID])
)
ON [PRIMARY]
GO