CREATE TABLE [job].[Jobs] (
  [JOB_ID] [int] IDENTITY,
  [JOB_ACCESSIBILITYLEVEL] [int] NOT NULL,
  [JOB_CLIENTID] [int] NOT NULL,
  [JOB_COMMENTTHREADID] [int] NULL,
  [JOB_CREATED] [datetime] NOT NULL CONSTRAINT [DF_tblJobNumbers_JOBNUMBER_CREATED] DEFAULT (getdate()),
  [JOB_CREATEDBYID] [int] NOT NULL,
  [JOB_DESCRIPTION] [nvarchar](max) NULL,
  [JOB_PASTJOBID] [int] NULL,
  [JOB_INSTRUCTIONS] [nvarchar](max) NULL,
  [JOB_NAME] [nvarchar](100) NOT NULL,
  [JOB_PRODUCTIONKEYINDEX] [int] NOT NULL CONSTRAINT [DF_Jobs_JOB_PRODUCTIONKEYINDEX] DEFAULT (0),
  [JOB_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED ([JOB_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [_dta_index_Jobs_5_1748917302__K1_K2_4]
  ON [job].[Jobs] ([JOB_ID], [JOB_CLIENTID])
  INCLUDE ([JOB_CREATEDBYID])
  ON [PRIMARY]
GO

CREATE INDEX [_dta_index_Jobs_6_802869977__K1]
  ON [job].[Jobs] ([JOB_ID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Jobs_ClientID]
  ON [job].[Jobs] ([JOB_CLIENTID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Jobs_Created]
  ON [job].[Jobs] ([JOB_CREATED])
  INCLUDE ([JOB_ID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Jobs_CreatedByID]
  ON [job].[Jobs] ([JOB_CREATEDBYID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Jobs_Name]
  ON [job].[Jobs] ([JOB_NAME])
  ON [PRIMARY]
GO

ALTER TABLE [job].[Jobs] WITH NOCHECK
  ADD CONSTRAINT [FK_Jobs_Clients] FOREIGN KEY ([JOB_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [job].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Users_USER_USERID] FOREIGN KEY ([JOB_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID])
GO