CREATE TABLE [job].[JobStageRoles] (
  [JOBSTAGEROLE_ID] [int] IDENTITY,
  [JOBSTAGEROLE_ROLEID] [int] NOT NULL CONSTRAINT [DF_tblJobStageRoles_JOBSTAGEROLE_ROLEID] DEFAULT (0),
  [JOBSTAGEROLE_STAGEGUID] [uniqueidentifier] NOT NULL,
  [JOBSTAGEROLE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_tblJobStageRoles] PRIMARY KEY CLUSTERED ([JOBSTAGEROLE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobStageRolesRoleID]
  ON [job].[JobStageRoles] ([JOBSTAGEROLE_ROLEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_tblJobStageRolesStageGuid]
  ON [job].[JobStageRoles] ([JOBSTAGEROLE_STAGEGUID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO