CREATE TABLE [laser].[WorkflowParameters] (
  [WORKFLOWPARAM_ID] [int] IDENTITY (-2147483648, 1),
  [WORKFLOWPARAM_INPUTFILENAME] [nvarchar](300) NOT NULL,
  [WORKFLOWPARAM_NUPCOUNTX] [int] NULL,
  [WORKFLOWPARAM_NUPCOUNTY] [int] NULL,
  [WORKFLOWPARAM_NUPOFFSETX] [float] NULL,
  [WORKFLOWPARAM_NUPOFFSETY] [float] NULL,
  [WORKFLOWPARAM_DUPLEXTYPE] [int] NOT NULL,
  [WORKFLOWPARAM_USERANGEFORPROD] [bit] NOT NULL,
  [WORKFLOWPARAM_STARTREC] [int] NOT NULL,
  [WORKFLOWPARAM_ENDREC] [int] NOT NULL,
  [WORKFLOWPARAM_NUMBERUP] [int] NOT NULL,
  CONSTRAINT [PK_WorkflowParameters] PRIMARY KEY CLUSTERED ([WORKFLOWPARAM_ID])
)
ON [PRIMARY]
GO