CREATE TABLE [laser].[Logs] (
  [LOG_ID] [int] IDENTITY (-2147483648, 1),
  [LOG_PNTVERSION] [nvarchar](10) NOT NULL,
  [LOG_JOBFILE] [nvarchar](300) NOT NULL,
  [LOG_PRINTENGINE] [nvarchar](20) NOT NULL,
  [LOG_STARTTIME] [datetime] NOT NULL,
  [LOG_ENDTIME] [datetime] NOT NULL,
  [LOG_ENDPAGE] [int] NOT NULL,
  [LOG_ENDCOPY] [int] NOT NULL,
  [LOG_PAGESPRINTED] [int] NOT NULL,
  [LOG_JOBCONFIGID] [int] NOT NULL,
  [LOG_WORKFLOWPARAMSID] [int] NOT NULL,
  [LOG_REPORTID] [int] NOT NULL,
  [LOG_LOGSTATUS] [int] NOT NULL,
  [LOG_DURATION] [int] NOT NULL,
  [LOG_PRINTER] [int] NOT NULL,
  CONSTRAINT [PK_Logs] PRIMARY KEY CLUSTERED ([LOG_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [laser].[Logs]
  ADD CONSTRAINT [FK_Logs_JobConfigs] FOREIGN KEY ([LOG_JOBCONFIGID]) REFERENCES [laser].[JobConfigs] ([JOBCONFIG_ID])
GO

ALTER TABLE [laser].[Logs]
  ADD CONSTRAINT [FK_Logs_Reports] FOREIGN KEY ([LOG_REPORTID]) REFERENCES [laser].[Reports] ([REPORT_ID])
GO

ALTER TABLE [laser].[Logs]
  ADD CONSTRAINT [FK_Logs_WorkflowParameters] FOREIGN KEY ([LOG_WORKFLOWPARAMSID]) REFERENCES [laser].[WorkflowParameters] ([WORKFLOWPARAM_ID])
GO