CREATE TABLE [laser].[Reports] (
  [REPORT_ID] [int] IDENTITY (-2147483648, 1),
  [REPORT_TOTALPRINTEDSHEETS] [int] NOT NULL,
  [REPORT_TOTALPRINTEDPAGES] [int] NOT NULL,
  [REPORT_CLICKCOST] [int] NOT NULL,
  [REPORT_PRINTCOST] [int] NOT NULL,
  [REPORT_JOBSTARTED] [datetime] NOT NULL,
  [REPORT_JOBLASTFINISHED] [datetime] NOT NULL,
  [REPORT_RUNDURATION] [int] NOT NULL,
  [REPORT_PRINTERSUSED] [int] NOT NULL,
  [REPORT_JOBID] [int] NOT NULL,
  [REPORT_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Reports] PRIMARY KEY CLUSTERED ([REPORT_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [laser].[Reports] WITH NOCHECK
  ADD CONSTRAINT [FK_Reports_Jobs] FOREIGN KEY ([REPORT_JOBID]) REFERENCES [job].[Jobs] ([JOB_ID])
GO