CREATE TABLE [mail].[EventListeners] (
  [EVENTLISTENER_ID] [int] IDENTITY,
  [EVENTLISTENER_EVENTS] [int] NOT NULL,
  [EVENTLISTENER_USERID] [int] NOT NULL,
  [EVENTLISTENER_ROWVERSION] [timestamp],
  CONSTRAINT [PK_EventListeners] PRIMARY KEY CLUSTERED ([EVENTLISTENER_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_EventListeners_UserID]
  ON [mail].[EventListeners] ([EVENTLISTENER_USERID])
  ON [PRIMARY]
GO

ALTER TABLE [mail].[EventListeners]
  ADD CONSTRAINT [FK_EventListeners_Users] FOREIGN KEY ([EVENTLISTENER_USERID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO