CREATE TABLE [maponics].[ZipCodePopulationStaging] (
  [zip] [char](5) NOT NULL,
  [pp_total] [int] NOT NULL,
  [pp_density] [decimal](7, 2) NOT NULL,
  [pp_wt_n_hs] [int] NOT NULL,
  [pp_wt_hs] [int] NOT NULL,
  [pp_bk_n_hs] [int] NOT NULL,
  [pp_bk_hs] [int] NOT NULL,
  [pp_ak_n_hs] [int] NOT NULL,
  [pp_ak_hs] [int] NOT NULL,
  [pp_as_n_hs] [int] NOT NULL,
  [pp_as_hs] [int] NOT NULL,
  [pp_pi_n_hs] [int] NOT NULL,
  [pp_pi_hs] [int] NOT NULL,
  [pp_or_n_hs] [int] NOT NULL,
  [pp_or_hs] [int] NOT NULL,
  [pp_2r_n_hs] [int] NOT NULL,
  [pp_2r_hs] [int] NOT NULL,
  [pp_male] [int] NOT NULL,
  [pp_female] [int] NOT NULL,
  [pp_under5] [int] NOT NULL,
  [pp_5_9] [int] NOT NULL,
  [pp_10_14] [int] NOT NULL,
  [pp_15_19] [int] NOT NULL,
  [pp_20_24] [int] NOT NULL,
  [pp_25_34] [int] NOT NULL,
  [pp_35_44] [int] NOT NULL,
  [pp_45_54] [int] NOT NULL,
  [pp_55_64] [int] NOT NULL,
  [pp_65_74] [int] NOT NULL,
  [pp_75_84] [int] NOT NULL,
  [pp_85_over] [int] NOT NULL,
  [ed_25p_nhs] [int] NOT NULL,
  [ed_25p_shs] [int] NOT NULL,
  [ed_25p_hsd] [int] NOT NULL,
  [ed_25p_sci] [int] NOT NULL,
  [ed_25p_asd] [int] NOT NULL,
  [ed_25p_bdc] [int] NOT NULL,
  [ed_25p_msd] [int] NOT NULL,
  [ed_25p_pfd] [int] NOT NULL,
  [ed_25p_drd] [int] NOT NULL,
  [ei_affhm] [int] NOT NULL,
  [ei_cnstruc] [int] NOT NULL,
  [ei_mfgtng] [int] NOT NULL,
  [ei_ret_who] [int] NOT NULL,
  [ei_t_w_u] [int] NOT NULL,
  [ei_info] [int] NOT NULL,
  [ei_fin_ins] [int] NOT NULL,
  [ei_realest] [int] NOT NULL,
  [ei_p_s_t] [int] NOT NULL,
  [ei_mngmnt] [int] NOT NULL,
  [ei_waste] [int] NOT NULL,
  [ei_educate] [int] NOT NULL,
  [ei_health] [int] NOT NULL,
  [ei_aeraf] [int] NOT NULL,
  [ei_other] [int] NOT NULL,
  [ei_pubamin] [int] NOT NULL,
  [occ_mgmt] [int] NOT NULL,
  [occ_stem] [int] NOT NULL,
  [occ_social] [int] NOT NULL,
  [occ_legal] [int] NOT NULL,
  [occ_edu] [int] NOT NULL,
  [occ_adesm] [int] NOT NULL,
  [occ_health] [int] NOT NULL,
  [occ_protct] [int] NOT NULL,
  [occ_food] [int] NOT NULL,
  [occ_clean] [int] NOT NULL,
  [occ_pcare] [int] NOT NULL,
  [occ_sales] [int] NOT NULL,
  [occ_nr_con] [int] NOT NULL,
  [occ_prtran] [int] NOT NULL,
  [wht_col_pc] [decimal](5, 2) NOT NULL,
  [blu_col_pc] [decimal](5, 2) NOT NULL,
  [ttw_car] [int] NOT NULL,
  [ttw_public] [int] NOT NULL,
  [ttw_taxi] [int] NOT NULL,
  [ttw_mcycle] [int] NOT NULL,
  [ttw_bcycle] [int] NOT NULL,
  [ttw_walk] [int] NOT NULL,
  [ttw_other] [int] NOT NULL,
  [ttw_home] [int] NOT NULL,
  [cmte_u5] [int] NOT NULL,
  [cmte_5_9] [int] NOT NULL,
  [cmte_10_14] [int] NOT NULL,
  [cmte_15_19] [int] NOT NULL,
  [cmte_20_24] [int] NOT NULL,
  [cmte_25_29] [int] NOT NULL,
  [cmte_30_34] [int] NOT NULL,
  [cmte_35_39] [int] NOT NULL,
  [cmte_40_44] [int] NOT NULL,
  [cmte_45_59] [int] NOT NULL,
  [cmte_60_89] [int] NOT NULL,
  [cmte_90o] [int] NOT NULL,
  [ctx_ver] [char](7) NOT NULL,
  [ver] [char](6) NOT NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX_ZipCode]
  ON [maponics].[ZipCodePopulationStaging] ([zip])
  ON [PRIMARY]
GO