CREATE TABLE [maponics].[ZipCodePropertyStaging] (
  [zip] [char](5) NOT NULL,
  [ho_total] [int] NOT NULL,
  [ho_wt] [int] NOT NULL,
  [ho_bk] [int] NOT NULL,
  [ho_ai_ak] [int] NOT NULL,
  [ho_as] [int] NOT NULL,
  [ho_hn_pi] [int] NOT NULL,
  [ho_or] [int] NOT NULL,
  [ho_hs] [int] NOT NULL,
  [rt_total] [int] NOT NULL,
  [rt_wt] [int] NOT NULL,
  [rt_bk] [int] NOT NULL,
  [rt_ai_ak] [int] NOT NULL,
  [rt_as] [int] NOT NULL,
  [rt_hn_pi] [int] NOT NULL,
  [rt_or] [int] NOT NULL,
  [rt_2r] [int] NOT NULL,
  [rt_hs] [int] NOT NULL,
  [ho_15_24] [int] NOT NULL,
  [ho_25_35] [int] NOT NULL,
  [ho_35_44] [int] NOT NULL,
  [ho_45_54] [int] NOT NULL,
  [ho_55_59] [int] NOT NULL,
  [ho_60_64] [int] NOT NULL,
  [ho_65_74] [int] NOT NULL,
  [ho_75_84] [int] NOT NULL,
  [ho_85_o] [int] NOT NULL,
  [hou_un_occ] [int] NOT NULL,
  [hou_un_vac] [int] NOT NULL,
  [hou_un_own] [int] NOT NULL,
  [hou_un_ren] [int] NOT NULL,
  [gr_u100] [int] NOT NULL,
  [gr_100p] [int] NOT NULL,
  [gr_150p] [int] NOT NULL,
  [gr_200p] [int] NOT NULL,
  [gr_250p] [int] NOT NULL,
  [gr_300p] [int] NOT NULL,
  [gr_350p] [int] NOT NULL,
  [gr_400p] [int] NOT NULL,
  [gr_450p] [int] NOT NULL,
  [gr_500p] [int] NOT NULL,
  [gr_550p] [int] NOT NULL,
  [gr_600p] [int] NOT NULL,
  [gr_650p] [int] NOT NULL,
  [gr_700p] [int] NOT NULL,
  [gr_750p] [int] NOT NULL,
  [gr_800p] [int] NOT NULL,
  [gr_900p] [int] NOT NULL,
  [gr_1000p] [int] NOT NULL,
  [gr_1250p] [int] NOT NULL,
  [gr_1500p] [int] NOT NULL,
  [gr_2000p] [int] NOT NULL,
  [gr_ncr] [int] NOT NULL,
  [mocmu200] [int] NOT NULL,
  [mocm200p] [int] NOT NULL,
  [mocm300p] [int] NOT NULL,
  [mocm400p] [int] NOT NULL,
  [mocm500p] [int] NOT NULL,
  [mocm600p] [int] NOT NULL,
  [mocm700p] [int] NOT NULL,
  [mocm800p] [int] NOT NULL,
  [mocm900p] [int] NOT NULL,
  [mocm1000p] [int] NOT NULL,
  [mocm1250p] [int] NOT NULL,
  [mocm1500p] [int] NOT NULL,
  [mocm2000p] [int] NOT NULL,
  [mocm2500p] [int] NOT NULL,
  [mocm3000p] [int] NOT NULL,
  [mocwomu100] [int] NOT NULL,
  [mocwom100p] [int] NOT NULL,
  [mocwom150p] [int] NOT NULL,
  [mocwom200p] [int] NOT NULL,
  [mocwom250p] [int] NOT NULL,
  [mocwom300p] [int] NOT NULL,
  [mocwom350p] [int] NOT NULL,
  [mocwom400p] [int] NOT NULL,
  [mocwom450p] [int] NOT NULL,
  [mocwom500p] [int] NOT NULL,
  [mocwom600p] [int] NOT NULL,
  [mocwom700p] [int] NOT NULL,
  [vhc_pohu] [decimal](3, 2) NOT NULL,
  [rt_burd] [int] NOT NULL,
  [rt_ex_burd] [int] NOT NULL,
  [ownr_burd] [int] NOT NULL,
  [ctx_ver] [char](7) NOT NULL,
  [ver] [char](6) NOT NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX_ZipCode]
  ON [maponics].[ZipCodePropertyStaging] ([zip])
  ON [PRIMARY]
GO