CREATE TABLE [purpleheart].[Records] (
  [RECORD_ID] [int] IDENTITY (-2147483648, 1),
  [RECORD_CARRIERROUTE] [char](4) NOT NULL,
  [RECORD_DAYOFWEEK] [smallint] NOT NULL,
  [RECORD_DEPOTID] [int] NOT NULL,
  [RECORD_DISCOUNT] [decimal](4, 3) NOT NULL,
  [RECORD_RATE] [decimal](4, 3) NULL,
  [RECORD_SCFDISCOUNT] [decimal](4, 3) NOT NULL,
  [RECORD_SCFID] [int] NOT NULL,
  [RECORD_SEED] [bit] NOT NULL,
  [RECORD_STATE] [char](2) NOT NULL,
  [RECORD_WEEK] [smallint] NOT NULL,
  [RECORD_YEAR] [smallint] NOT NULL,
  [RECORD_ZIPCODE] [char](9) NOT NULL,
  [RECORD_ZIPCODENAME] [char](10) NOT NULL,
  CONSTRAINT [PK_Records] PRIMARY KEY CLUSTERED ([RECORD_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Records_DepotID]
  ON [purpleheart].[Records] ([RECORD_DEPOTID])
  INCLUDE ([RECORD_CARRIERROUTE], [RECORD_DISCOUNT], [RECORD_RATE], [RECORD_SCFDISCOUNT], [RECORD_STATE], [RECORD_WEEK], [RECORD_YEAR], [RECORD_ZIPCODE])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Records_DepotIDSeedWeekYear]
  ON [purpleheart].[Records] ([RECORD_DEPOTID], [RECORD_SEED], [RECORD_WEEK], [RECORD_YEAR])
  INCLUDE ([RECORD_CARRIERROUTE], [RECORD_DAYOFWEEK], [RECORD_ZIPCODE], [RECORD_ZIPCODENAME])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Records_Rotation]
  ON [purpleheart].[Records] ([RECORD_DEPOTID], [RECORD_SEED], [RECORD_WEEK], [RECORD_YEAR])
  INCLUDE ([RECORD_CARRIERROUTE], [RECORD_DAYOFWEEK], [RECORD_ZIPCODE])
  ON [PRIMARY]
GO