CREATE TABLE [purpleheart].[TemplateZipCodes] (
  [ZIPCODE_ID] [int] IDENTITY (-2147483648, 1),
  [ZIPCODE_DEPOTID] [int] NOT NULL,
  [ZIPCODE_ITEMID] [int] NOT NULL,
  [ZIPCODE_PUBLISHED] [bit] NOT NULL,
  [ZIPCODE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_ZipCodeItems] PRIMARY KEY CLUSTERED ([ZIPCODE_ID])
)
ON [PRIMARY]
GO