CREATE TABLE [site].[Logons] (
  [LOGON_ID] [int] IDENTITY (-2147483648, 1),
  [LOGON_INACTIVELOGOUT] [int] NOT NULL,
  [LOGON_LOCKEDOUT] [bit] NOT NULL,
  [LOGON_LOGONS] [int] NOT NULL,
  [LOGON_SITEID] [int] NOT NULL,
  [LOGON_USERID] [int] NOT NULL,
  [LOGON_ROWVERSION] [timestamp],
  CONSTRAINT [PK_Logons] PRIMARY KEY CLUSTERED ([LOGON_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Logons_SiteID]
  ON [site].[Logons] ([LOGON_SITEID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Logons_UserID]
  ON [site].[Logons] ([LOGON_USERID])
  ON [PRIMARY]
GO

ALTER TABLE [site].[Logons]
  ADD CONSTRAINT [FK_Logons_Sites] FOREIGN KEY ([LOGON_SITEID]) REFERENCES [site].[Sites] ([SITE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [site].[Logons]
  ADD CONSTRAINT [FK_Logons_Users] FOREIGN KEY ([LOGON_USERID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO