CREATE TABLE [site].[Invitations] (
  [INVITATION_ID] [int] IDENTITY (-2147483648, 1),
  [INVITATION_CLIENTID] [int] NOT NULL CONSTRAINT [DF_tblUserInvitations_INVITE_CLIENT_ID] DEFAULT (0),
  [INVITATION_CREATED] [datetime] NOT NULL,
  [INVITATION_CREATEDBYID] [int] NOT NULL,
  [INVITATION_DEFAULTURL] [nvarchar](200) NULL,
  [INVITATION_HOST] [nvarchar](4000) NOT NULL,
  [INVITATION_KEY] [nvarchar](50) NOT NULL,
  [INVITATION_ROLEID] [int] NOT NULL CONSTRAINT [DF_tblUserInvitations_INVITE_ROLE_ID] DEFAULT (0),
  [INVITATION_SITEID] [int] NOT NULL,
  [INVITATION_USERNAME] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_UserInvitations] PRIMARY KEY CLUSTERED ([INVITATION_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_UserInvitations_Uniqueness]
  ON [site].[Invitations] ([INVITATION_USERNAME])
  ON [PRIMARY]
GO

ALTER TABLE [site].[Invitations]
  ADD CONSTRAINT [FK_Invitations_Clients] FOREIGN KEY ([INVITATION_CLIENTID]) REFERENCES [dbo].[Clients] ([CLIENT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [site].[Invitations]
  ADD CONSTRAINT [FK_Invitations_Sites] FOREIGN KEY ([INVITATION_SITEID]) REFERENCES [site].[Sites] ([SITE_ID]) ON DELETE CASCADE
GO