CREATE TABLE [StVincent].[Records] (
  [RECORD_ID] [int] IDENTITY (-2147483648, 1),
  [RECORD_LEADID] [int] NOT NULL,
  [RECORD_PREFIXTTL] [varchar](4) NULL,
  [RECORD_INDIVIDUALNAME] [varchar](70) NULL,
  [RECORD_FIRSTNAME] [varchar](35) NULL,
  [RECORD_MIDDLENAME] [varchar](1) NULL,
  [RECORD_LASTNAME] [varchar](35) NULL,
  [RECORD_ADDRESS] [varchar](50) NULL,
  [RECORD_ADDRESS2LINE] [varchar](35) NULL,
  [RECORD_CITY] [varchar](30) NULL,
  [RECORD_STATE] [varchar](2) NULL,
  [RECORD_CARRIERROUTE] [char](4) NOT NULL,
  [RECORD_DSFWALKSEQUENCE] [varchar](4) NULL,
  [RECORD_COUNTY] [varchar](3) NULL,
  [RECORD_POSTSUPPPHONE] [varchar](10) NULL,
  [RECORD_SECPHONEFLAG] [varchar](1) NULL,
  [RECORD_DAYOFWEEK] [smallint] NOT NULL,
  [RECORD_DEPOTID] [int] NOT NULL,
  [RECORD_DISCOUNT] [decimal](4, 3) NULL,
  [RECORD_RATE] [decimal](4, 3) NULL,
  [RECORD_SCFDISCOUNT] [decimal](4, 3) NULL,
  [RECORD_SCFID] [int] NULL,
  [RECORD_SEED] [bit] NOT NULL,
  [RECORD_WEEK] [smallint] NOT NULL,
  [RECORD_YEAR] [smallint] NOT NULL,
  [RECORD_ZIPCODE] [char](9) NOT NULL,
  [RECORD_DPBC] [varchar](3) NULL,
  [RECORD_ZIPCODENAME] [char](10) NOT NULL,
  CONSTRAINT [PK_Records] PRIMARY KEY CLUSTERED ([RECORD_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [StVincent].[Records]
  ADD CONSTRAINT [FK_Records_Depots] FOREIGN KEY ([RECORD_DEPOTID]) REFERENCES [StVincent].[Depots] ([DEPOT_ID]) ON DELETE CASCADE
GO