CREATE TABLE [StVincent].[OrderZipDate] (
  [ZIPCODE_ID] [int] IDENTITY (-2147483648, 1),
  [ZIPCODE_DATE] [date] NOT NULL,
  [ZIPCODE_DEPOTID] [int] NOT NULL,
  [ZIPCODE_ITEMID] [int] NOT NULL,
  [ZIPCODE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_OrderZipCodeItems] PRIMARY KEY CLUSTERED ([ZIPCODE_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [StVincent].[OrderZipDate]
  ADD CONSTRAINT [FK_OrderZipCodes_Depots] FOREIGN KEY ([ZIPCODE_DEPOTID]) REFERENCES [purpleheart].[Depots] ([DEPOT_ID]) ON DELETE CASCADE
GO

ALTER TABLE [StVincent].[OrderZipDate]
  ADD CONSTRAINT [FK_OrderZipDate_OrderZipCodes] FOREIGN KEY ([ZIPCODE_ITEMID]) REFERENCES [StVincent].[OrderZipCodes] ([ZIPCODE_ID]) ON DELETE CASCADE
GO