CREATE TABLE [StVincent].[OrderZipCodes] (
  [ZIPCODE_ID] [int] IDENTITY (-2147483648, 1),
  [ZIPCODE_CREATED] [datetime] NOT NULL,
  [ZIPCODE_CREATEDBYID] [int] NOT NULL,
  [ZIPCODE_NAME] [char](10) NOT NULL,
  [ZIPCODE_ZIPCODE] [char](5) NOT NULL,
  [ZIPCODE_ROWVERSION] [timestamp],
  CONSTRAINT [PK_OrderZipCodeItem] PRIMARY KEY CLUSTERED ([ZIPCODE_ID])
)
ON [PRIMARY]
GO