CREATE TABLE [usps].[PostalClasses] (
  [POSTALCLASS_ID] [int] IDENTITY (-2147483648, 1),
  [POSTALCLASS_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_PostalClasses] PRIMARY KEY CLUSTERED ([POSTALCLASS_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO