CREATE TABLE [usps].[SegmentFiles] (
  [FILE_ID] [int] IDENTITY (-2147483648, 1),
  [FILE_METADATAID] [int] NOT NULL,
  [FILE_SEGMENTID] [int] NOT NULL,
  CONSTRAINT [PK_SegmentFiles] PRIMARY KEY CLUSTERED ([FILE_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [usps].[SegmentFiles] WITH NOCHECK
  ADD CONSTRAINT [FK_SegmentFiles_MetaData] FOREIGN KEY ([FILE_METADATAID]) REFERENCES [file].[Files] ([FILE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [usps].[SegmentFiles] WITH NOCHECK
  ADD CONSTRAINT [FK_SegmentFiles_Segments] FOREIGN KEY ([FILE_SEGMENTID]) REFERENCES [dbo].[MailSegments] ([MAILSEGMENT_ID]) ON DELETE CASCADE
GO