CREATE TABLE [usps].[ProcessTypes] (
  [PROCESSTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [PROCESSTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_ProcessTypes] PRIMARY KEY CLUSTERED ([PROCESSTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO