CREATE TABLE [usps].[TrackingTypes] (
  [TRACKINGTYPE_ID] [int] NOT NULL,
  [TRACKINGTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_TrackingTypes] PRIMARY KEY CLUSTERED ([TRACKINGTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO