CREATE TABLE [usps].[AnalysisTypes] (
  [ANALYSISTYPE_ID] [int] NOT NULL,
  [ANALYSISTYPE_NAME] [varchar](max) NOT NULL,
  CONSTRAINT [PK_AnalysisTypes] PRIMARY KEY CLUSTERED ([ANALYSISTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO