CREATE TABLE [usps].[MailTypes] (
  [MAILTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [MAILTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_MailTypes] PRIMARY KEY CLUSTERED ([MAILTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO