CREATE TABLE [usps].[OperationTypes] (
  [OPERATIONTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [OPERATIONTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_OperationTypes] PRIMARY KEY CLUSTERED ([OPERATIONTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO