CREATE TABLE [usps].[MailPieceScans] (
  [MAILPIECESCAN_ID] [int] IDENTITY (-2147483648, 1),
  [MAILPIECESCAN_DATETIME] [datetime] NOT NULL,
  [MAILPIECESCAN_FACILITYID] [int] NOT NULL,
  [MAILPIECESCAN_MAILPIECEID] [int] NOT NULL,
  [MAILPIECESCAN_OPERATIONID] [int] NOT NULL,
  CONSTRAINT [PK_MailPieceScans] PRIMARY KEY CLUSTERED ([MAILPIECESCAN_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [usps].[MailPieceScans]
  ADD CONSTRAINT [FK_MailPieceScans_Facilities] FOREIGN KEY ([MAILPIECESCAN_FACILITYID]) REFERENCES [dbo].[Facilities] ([FACILITY_ID]) ON DELETE CASCADE
GO

ALTER TABLE [usps].[MailPieceScans]
  ADD CONSTRAINT [FK_MailPieceScans_MailPieces] FOREIGN KEY ([MAILPIECESCAN_MAILPIECEID]) REFERENCES [dbo].[MailPieces] ([MAILPIECE_ID]) ON DELETE CASCADE
GO

ALTER TABLE [usps].[MailPieceScans]
  ADD CONSTRAINT [FK_MailPieceScans_Operations] FOREIGN KEY ([MAILPIECESCAN_OPERATIONID]) REFERENCES [dbo].[Operations] ([OPERATION_ID]) ON DELETE CASCADE
GO