CREATE TABLE [usps].[MailSegmentSequences] (
  [SEQUENCE_ID] [int] IDENTITY,
  [SEQUENCE_CREATED] [datetime] NOT NULL,
  [SEQUENCE_CREATEDBYID] [int] NOT NULL,
  [SEQUENCE_CYCLECOUNT] [int] NOT NULL,
  [SEQUENCE_ENDVALUE] [int] NOT NULL,
  [SEQUENCE_INCREMENT] [int] NOT NULL,
  [SEQUENCE_MAILERID] [int] NOT NULL,
  [SEQUENCE_MAILINGID] [int] NOT NULL,
  [SEQUENCE_MAXVALUE] [int] NOT NULL,
  [SEQUENCE_MINVALUE] [int] NOT NULL,
  [SEQUENCE_STARTVALUE] [int] NOT NULL,
  [SEQUENCE_SEGMENTID] [int] NULL,
  CONSTRAINT [PK_Sequences] PRIMARY KEY CLUSTERED ([SEQUENCE_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Sequences_CreatedByID]
  ON [usps].[MailSegmentSequences] ([SEQUENCE_CREATEDBYID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Sequences_MailingID]
  ON [usps].[MailSegmentSequences] ([SEQUENCE_MAILINGID])
  ON [PRIMARY]
GO

ALTER TABLE [usps].[MailSegmentSequences]
  ADD CONSTRAINT [FK_Sequences_Mailers] FOREIGN KEY ([SEQUENCE_MAILERID]) REFERENCES [usps].[Mailers] ([Id]) ON DELETE CASCADE
GO

ALTER TABLE [usps].[MailSegmentSequences]
  ADD CONSTRAINT [FK_Sequences_Mailings] FOREIGN KEY ([SEQUENCE_MAILINGID]) REFERENCES [dbo].[Jobs] ([JOB_ID])
GO

ALTER TABLE [usps].[MailSegmentSequences] WITH NOCHECK
  ADD CONSTRAINT [FK_Sequences_Users] FOREIGN KEY ([SEQUENCE_CREATEDBYID]) REFERENCES [dbo].[Users] ([USER_USERID]) ON DELETE CASCADE
GO