CREATE TABLE [usps].[MailPhases] (
  [MAILPHASE_ID] [int] IDENTITY (-2147483648, 1),
  [MAILPHASE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_MailPhases] PRIMARY KEY CLUSTERED ([MAILPHASE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO