CREATE TABLE [usps].[Facilities] (
  [FACILITY_ID] [int] IDENTITY (-2147483648, 1),
  [FACILITY_ADDRESS] [varchar](100) NULL,
  [FACILITY_CITY] [varchar](30) NULL,
  [FACILITY_FDBID] [int] NULL,
  [FACILITY_FINANCENUMBER] [int] NULL,
  [FACILITY_LATITUDE] [decimal](9, 6) NOT NULL,
  [FACILITY_LOCALEID] [int] NULL,
  [FACILITY_LONGITUDE] [decimal](9, 6) NOT NULL,
  [FACILITY_NAME] [varchar](100) NOT NULL,
  [FACILITY_NASSCODE] [char](5) NULL,
  [FACILITY_PARENTID] [int] NULL,
  [FACILITY_STATE] [char](2) NOT NULL,
  [FACILITY_SUBTYPEID] [int] NOT NULL,
  [FACILITY_ZIPCODE] [char](9) NOT NULL,
  CONSTRAINT [PK_Facility] PRIMARY KEY CLUSTERED ([FACILITY_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_Facility_ParentID]
  ON [usps].[Facilities] ([FACILITY_PARENTID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_Facility_ZipCode]
  ON [usps].[Facilities] ([FACILITY_ZIPCODE])
  ON [PRIMARY]
GO