CREATE TABLE [usps].[RateCategories] (
  [CATEGORY_ID] [int] IDENTITY (-2147483648, 1),
  [CATEGORY_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_RateCategories] PRIMARY KEY CLUSTERED ([CATEGORY_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO