CREATE TABLE [usps].[ContainerTypes] (
  [CONTAINERTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [CONTAINERTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_ContainerTypes] PRIMARY KEY CLUSTERED ([CONTAINERTYPE_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO