CREATE TABLE [usps].[PermitTypes] (
  [PERMITTYPE_ID] [int] IDENTITY (-2147483648, 1),
  [PERMITTYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_tblPermitTypes] PRIMARY KEY CLUSTERED ([PERMITTYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO