CREATE TABLE [usps].[ServiceTypes] (
  [SERVICETYPE_ID] [int] NOT NULL,
  [SERVICETYPE_ACSOPTIONID] [int] NOT NULL,
  [SERVICETYPE_FULLSERVICE] [bit] NOT NULL,
  [SERVICETYPE_POSTALCLASSID] [int] NOT NULL,
  [SERVICETYPE_TRACKED] [bit] NOT NULL,
  CONSTRAINT [PK_ServiceTypes] PRIMARY KEY CLUSTERED ([SERVICETYPE_ID])
)
ON [PRIMARY]
GO

ALTER TABLE [usps].[ServiceTypes]
  ADD CONSTRAINT [FK_ServiceTypes_AddressCorrectionOptions] FOREIGN KEY ([SERVICETYPE_ACSOPTIONID]) REFERENCES [usps].[AddressCorrectionOptions] ([ACSOPTION_ID])
GO

ALTER TABLE [usps].[ServiceTypes]
  ADD CONSTRAINT [FK_ServiceTypes_PostalClasses] FOREIGN KEY ([SERVICETYPE_POSTALCLASSID]) REFERENCES [usps].[PostalClasses] ([POSTALCLASS_ID]) ON DELETE CASCADE
GO