CREATE TABLE [usps].[ServiceLevels] (
  [SERVICELEVEL_ID] [int] IDENTITY (-2147483648, 1),
  [SERVICELEVEL_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_ServiceLevels] PRIMARY KEY CLUSTERED ([SERVICELEVEL_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO