CREATE TABLE [usps].[MailingFiles] (
  [FILE_ID] [int] IDENTITY (-2147483648, 1),
  [FILE_METADATAID] [int] NOT NULL,
  [FILE_MAILINGID] [int] NOT NULL,
  CONSTRAINT [PK_MailingFiles] PRIMARY KEY CLUSTERED ([FILE_ID])
)
ON [PRIMARY]
GO

CREATE INDEX [IX_MailingFiles]
  ON [usps].[MailingFiles] ([FILE_MAILINGID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_MailingFiles_Uniqueness]
  ON [usps].[MailingFiles] ([FILE_METADATAID], [FILE_MAILINGID])
  ON [PRIMARY]
GO

ALTER TABLE [usps].[MailingFiles] WITH NOCHECK
  ADD CONSTRAINT [FK_MailingFiles_Jobs] FOREIGN KEY ([FILE_MAILINGID]) REFERENCES [dbo].[Jobs] ([JOB_ID]) ON DELETE CASCADE
GO

ALTER TABLE [usps].[MailingFiles] WITH NOCHECK
  ADD CONSTRAINT [FK_MailingFiles_MetaData] FOREIGN KEY ([FILE_METADATAID]) REFERENCES [file].[Files] ([FILE_ID]) ON DELETE CASCADE
GO