CREATE TABLE [usps].[PieceTypes] (
  [PIECETYPE_ID] [int] IDENTITY (-2147483648, 1),
  [PIECETYPE_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_tblPieceSizeTypes] PRIMARY KEY CLUSTERED ([PIECETYPE_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO