CREATE TABLE [web].[EventListeners] (
  [EVENTLISTENER_ID] [int] IDENTITY,
  [EVENTLISTENER_EVENTS] [int] NOT NULL,
  [EVENTLISTENER_PAGEID] [int] NOT NULL,
  [EVENTLISTENER_USERID] [int] NOT NULL,
  [EVENTLISTENER_ROWVERSION] [timestamp],
  CONSTRAINT [PK_WebCampaignEventListeners] PRIMARY KEY CLUSTERED ([EVENTLISTENER_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IX_WebCampaignEventListeners_PageID]
  ON [web].[EventListeners] ([EVENTLISTENER_PAGEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_WebCampaignEventListeners_Uniqueness]
  ON [web].[EventListeners] ([EVENTLISTENER_PAGEID], [EVENTLISTENER_USERID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IX_WebCampaignEventListeners_UserID]
  ON [web].[EventListeners] ([EVENTLISTENER_USERID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO