CREATE TABLE [web].[Screenshots] (
  [SCREENSHOT_ID] [int] IDENTITY,
  [SCREENSHOT_FULLSIZE] [varbinary](max) NOT NULL,
  [SCREENSHOT_PAGEID] [int] NOT NULL,
  [SCREENSHOT_THUMBNAIL] [varbinary](max) NOT NULL,
  CONSTRAINT [PK_WebCampaignPageImages] PRIMARY KEY CLUSTERED ([SCREENSHOT_ID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_WebCampaignPageImages_pAGEid]
  ON [web].[Screenshots] ([SCREENSHOT_PAGEID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO